api/controllers/main.cfc, model/service/HibachiUtilityService.cfc
alphabetizing drop down options that are retrieved via api
=> alphabetize all options that run through the server side api

admin/client/js/directives/partials/productbundle/createproductbundle.html, api/views/js/ngslatwall.cfm
fixes to how we inspect the object chain
=> fixing parent level object saves

org/Hibachi/HibachiAssets/js/global.js
fixing Issue - Bundle - hard error when select existing bundle in edit mode, change name and save.
=> removing ng-form if we are preforming a server side submit

api/views/js/ngslatwall.cfm
=> typo fixes object save level

admin/client/js/directives/partials/productbundle/productbundlegroups.html, admin/client/js/directives/swproductbundlegroup.js
Here's one working example.  Can you confirm that this is infact what you were looking for?
=> Starting with sw-product-bundle-group as an example

admin/client/js/directives/partials/collection/editfilteritem.html, admin/client/js/directives/partials/collection/filtergroupitem.html, admin/client/js/directives/partials/entity/slatwall-detail.html, admin/client/js/directives/partials/formfields/formfield.html, admin/client/js/directives/partials/formfields/json.html, admin/client/js/directives/partials/formfields/number.html, admin/client/js/directives/partials/formfields/select.html, admin/client/js/directives/partials/formfields/text.html, admin/client/js/directives/partials/productbundle/productbundlegroup.html, admin/client/js/directives/partials/propertydisplay.html, admin/client/js/directives/partials/workflow/workflowbasic.html, admin/client/js/directives/swpropertydisplay.js, admin/client/js/directives/swrbkey.js, admin/client/js/services/propertydisplayservice.js, admin/layouts/default.cfm, api/views/js/ngslatwall.cfm, config/resourceBundles/en.properties
I made rbkeys run through a directive that works similar to ng-bind
expressions can be run through as long as they end up as strings
example <span sw-rbkey = "'entity.'+variable+'.property'"></span>
The directive checks whether the resource bundles have finished loading. If so then render based on it otherwise set up a listener.
on full resource bundle load broadcast to all waiting listeners. they will render and unbind all listeners.
=> Feature rm rb key

admin/client/js/directives/swcriterianumber.js, admin/client/js/directives/sweditfilteritem.js, model/entity/Collection.cfc
fixes to filtering numbers and separation of logic for number and date range querying
=> Feature rm filteron number

meta/tests/unit/dao/DataDAOTest.cfc, model/dao/CurrencyDAO.cfc, model/dao/PaymentDAO.cfc, model/dao/PhysicalDAO.cfc, model/dao/PromotionDAO.cfc, model/dao/ReportDAO.cfc, model/dao/ScheduleDAO.cfc, org/Hibachi/HibachiReport.cfc
var scoping tool used to fix a number of minor scoping issues.
=> merging var scoping fixes

api/controllers/main.cfc
if we have an empty option value, then make it the top item in the select box
=> if the optionarray contains a value that is empty then make it the first

admin/client/js/directives/sweditfilteritem.js, model/entity/Collection.cfc
used to pass in % via client side string. Now passing in pattern string and allowing coldfusion to handle adding the % to the like filters on the server side
=> like filter fixes

admin/views/entity/detailaccountaddress.cfm, model/entity/AccountAddress.cfc, model/entity/AttributeSet.cfc, model/entity/AttributeValue.cfc
Not 100% sure on the view implementation, let me know.
=> Adding custom attributes to accountAddress. 

admin/client/js/directives/swformfieldselect.js
this line did not belong inside of the select formfield and was preventing saving of product bundles
=> fixing a refactor typo

integrationServices/ups/Integration.cfc
Adds 00 - negotiated rates to customer classification code options
=> Negotiated Rates added to UPS integration

admin/client/js/directives/partials/collection/filteritem.html
Remove the edit icon from the collection filter items.
=> Remove edit icon from collection items

model/process/Order_CreateReturn.cfc, model/service/OrderService.cfc
-User can now create return order with orderItem return quantity of 0
=> Added ability to create return order with orderItemStruct.quantity = 0

model/dao/PaymentDAO.cfc, model/entity/OrderPayment.cfc
=> fixing logic for order payments

admin/views/entity/orderitemtabs/basic.cfm
=> Added new table header for Order Details and a poperty for the

model/process/Order_CreateReturn.cfc, model/validation/Order_CreateReturn.json
Made changes requested for in code review
=> Reverted hasPositiveOrderItemQuantity and instead removed validation

admin/client/js/directives/partials/collection/collection.html, admin/client/js/directives/partials/collection/collectiontable.html, admin/client/js/directives/partials/loading.html, admin/client/js/directives/swloading.js
creating a loading directive that will show a spinny during the period that the data variable is undefined
=> adding a loading directive

admin/client/js/directives/partials/collection/collection.html, admin/client/js/directives/partials/collection/displayitem.html
fixing bug where display options were putting one-to-many and many-to-many options in the display properties list
=> should not be able to select one-to-many and many-to-many for dispaly

admin/client/js/directives/partials/collection/collection.html, admin/client/js/directives/partials/collection/displayoptions.html, admin/client/js/directives/swdisplayoptions.js
fixing reload bugs because button attempts a submit
=> button fixes

admin/client/js/directives/partials/workflow/workflowtriggers.html, admin/client/js/directives/swworkflowtasks.js
buttoning up workflow ui for general testing
=> hiding scheduled triggers. bug fixes to selecting workflowtask

admin/client/js/services/slatwallInterceptor.js
added server side logic to display an error message if data retrieved had a server side error
=> adding a message if there was a problem retrieving server side data

custom/model/entity/readme.md
=> Added an /entity folder to the custom model directory so that ORM

model/entity/WorkflowTaskAction.cfc
removing unsupported task actions
=> Feature rm workflow

admin/client/js/controllers/collections.js, admin/client/js/directives/partials/collection/collection.html
adding loading spinny to collections for searching
=> removing conflict and supporting collection loading

api/views/js/ngcompressor.cfm
handling when there is no js files to compress
=> setting compressed to empty if the the content is empty

model/entity/Collection.cfc
handling when a value property doesn't exist
=> handling when a filter value is missing in the predicate

public/tags/AddressForm.cfm
Corrected case for sw:formField to sw:FormField in AddressForm.cfm
=> Corrected case for sw:formField to sw:FormField in AddressForm.cfm

model/process/SubscriptionUsage_Renew.cfc
Added getOrderPayment to SubscriptionUsage_Renew.cfc to retreive order payment from last subscription
=> Hotfix error renewing subscr payplexpress

admin/layouts/default.cfm
=> fixing hash routes

admin/client/js/directives/partials/collection/collectiontable.html, model/entity/Collection.cfc, model/service/CollectionService.cfc
if a collection cannot retrieve records, this will allow you to still edit the config. This should help with debugging of collecitons
=> allowing the editing of collections even if they break

admin/client/js/directives/partials/collection/criteriamanytomany.html, admin/client/js/directives/partials/collection/criteriamanytoone.html, admin/client/js/directives/partials/collection/criteriaonetomany.html, admin/client/js/directives/partials/collection/editfilteritem.html
adding loading spinnies to collections
=> adding loading spinny for criteria filters

model/entity/Collection.cfc
able to search numbers using keyword
=> able to search numbers using keyword

admin/client/js/directives/partials/collection/displayoptions.html, admin/client/js/services/metadataservice.js
Sort the dropdowns alphabetically and Removed lines from collection filter and display dropdowns.
=> Removed lines from collection filter and display dropdowns.

model/entity/Collection.cfc
excluding order by when using collection hql for Exists
=> excluding orderby HQL when retriving collection of collection

admin/client/js/controllers/create-bundle-controller.js
fixing bug where product bundle group editing was not opening
=> fixing bug where edit bundle group was not working

admin/client/js/directives/partials/workflow/workflowtaskactions.html, admin/client/js/directives/swworkflowtaskactions.js
loading details and object data into list item for taskaction
=> showing object and details for workflow

model/entity/Collection.cfc
setting default order by if one isn't specified
=> adding default order by

admin/client/js/controllers/create-bundle-controller.js, admin/client/js/controllers/slatwall-detail-controller.js, admin/client/js/directives/partials/formfields/formfield.html, admin/client/js/directives/partials/formfields/text.html, admin/client/js/directives/partials/propertydisplay.html, admin/client/js/directives/swcriteriamanytoone.js, admin/client/js/directives/swcriteriaonetomany.js, admin/client/js/directives/swcriteriastring.js, admin/client/js/directives/swfiltergroups.js, admin/client/js/directives/swformfieldsearchselect.js, admin/client/js/directives/swinput.js, admin/client/js/directives/swproductbundlegroup.js, admin/client/js/directives/swvalidate.js, admin/client/js/directives/swvalidationgte.js, admin/client/js/directives/swvalidationlte.js, admin/client/js/directives/swvalidationmaxlength.js, admin/client/js/directives/swvalidationmaxvalue.js, admin/client/js/directives/swvalidationminlength.js, admin/client/js/directives/swvalidationminvalue.js, admin/client/js/directives/swvalidationnumeric.js, admin/client/js/directives/swvalidationregex.js, admin/client/js/directives/swvalidationrequired.js, admin/client/js/directives/swvalidationunique.js, admin/client/js/directives/swworkflowtaskactions.js, admin/client/js/directives/swworkflowtrigger.js, admin/client/js/directives/swworkflowtriggers.js, admin/client/js/services/formservice.js, admin/client/js/services/metadataservice.js, api/views/js/ngslatwall.cfm
Added asterick to form labels when the associated input is a required field
=> Added asterick to form labels when the associated input is a required field

admin/client/js/controllers/pagedialog.js, admin/layouts/default.cfm
=> bug fix for hiding pagedialogs prior to angular being fully loaded

admin/controllers/ajax.cfc, org/Hibachi/HibachiAssets/js/global.js
It then checks to see if the autocomplete name is the one for assigned
account then it adds a where clause to check if the account is an admin
=> Added logic to send the property 'name' of the autocomplete to the ajax.

integrationServices/mura/model/handler/MuraEventHandler.cfc
Use getIsOnDisplay() to determine content that is either display=no or set to off with start/stop dates
=> Hotfix scientific american display no redirect to 404

admin/client/js/directives/partials/collection/criteriadate.html
Made sure that the dates are auto recalculating and they are without issue.
=> Fixes an issue with the last N input being disabled.

model/service/WorkflowService.cfc
fixing workflow bug when saving with a different related object
=> Feature rm workflow bug

model/entity/Collection.cfc
=> Revert "Feature ds collection search issue"

admin/client/css/main.css, admin/client/css/main.less
Fix responsive tables to show content.
Task: https://ten24.teamworkpm.net/tasks/3085129
=> fix responsive table

admin/client/css/main.css, admin/client/css/main.less, admin/layouts/default.cfm, org/Hibachi/HibachiTags/HibachiActionCallerDropdown.cfm
Stop gap measure for nav.  The issue will not be fixed in v4.  The mobile nav need s to have a ton of discussion and work done for it.  I removed the mobile feature and added more horizontal space so the nav works to 958px.
Task: https://ten24.teamworkpm.net/files/1020191
=> Stop gap for mobile nav

admin/client/js/directives/partials/childorderitem.html, admin/client/js/directives/partials/orderitem.html, admin/client/js/directives/partials/orderitemrows.html
This branch is called details but is actually fixing customization issues.
=> Feature ih orderitems customization

admin/client/js/directives/swcriteriastring.js, admin/client/js/directives/sweditfilteritem.js
=> Revert "Created a displayValue at the criteria directive level"

model/service/WorkflowService.cfc
=> fixing workflow bug

admin/client/js/directives/partials/collection/collection.html, admin/client/js/directives/swdisplayoptions.js
adding rbkey concat for column names based on property identifier
TTCR;
make it so orderItem.order.orderstatustype.typename = Order | Order Status | Name
=> Feature collection typerbkeynames

admin/client/js/directives/partials/collection/criteriadate.html, admin/layouts/default.cfm
=> fixing date picker

admin/client/js/directives/partials/productbundle/createproductbundle.html
price was being associated with product because it was in a product object form instead of a sku object form.
=> price was being set at the wrong form level

admin/client/js/directives/swcriteriadate.js
=> clear values for new filteritems

integrationServices/paypalexpress/Payment.cfc
https://github.com/ten24/slatwall/issues/2850
=> Change email address sent to PayPal to be the account email address

admin/client/js/directives/partials/collection/criteriaboolean.html, admin/client/js/directives/partials/collection/criteriadate.html, admin/client/js/directives/partials/collection/criterianumber.html, admin/client/js/directives/partials/collection/criteriastring.html
Set full width forms
Task: https://ten24.teamworkpm.net/tasks/3208823
=> make collections form field full width

api/views/js/ngslatwall.cfm
collection keys for initializing the related object
=> bug fix to the getter methods so that they now use the updated

custom/assets/.gitignore, custom/assets/ckeditor_config.js, org/Hibachi/HibachiAssets/js/global.js, org/Hibachi/ckeditor/config.js
or adding to lines in the ckeditor_config.js file within the custom
folder.
=> Added ability to have a custom config file for ckeditor by uncommenting

model/entity/HibachiEntity.cfc, org/Hibachi/HibachiTags/HibachiFieldDisplay.cfm, org/Hibachi/HibachiTags/HibachiFormField.cfm, tags/SlatwallAdminAttributeSetDisplay.cfm
able to remove pdfs by attributevalue
=> fix for davol allowing removal of pdfs

admin/client/js/controllers/create-bundle-controller.js, admin/client/js/controllers/edit-bundle-controller.js, admin/client/js/directives/partials/productbundle/createproductbundle.html, admin/client/js/directives/swscrolltrigger.js, admin/layouts/default.cfm
were not appearing at various points in the save process. Error/Save messages are now visible to the user.
=> Fixes an issue with creating product bundles where error/save messages

model/service/OrderService.cfc
=> Fix for issue  #2958

model/service/StockService.cfc
Adding in joins on sock smartlist similar to sku smartlist so things are searchable in the admin/order/order items/stock tab
=> beefing up stock smartlist 

config/dbdata/SlatwallLocation.xml.cfm
=> resolving migration bug about duplicate location when upgrading Slatwall

admin/client/css/main.css, admin/client/css/main.less, admin/client/js/directives/partials/productbundle/createproductbundle.html, admin/client/js/directives/partials/productbundle/productbundlegroups.html
Example s-loading on line 120 of
admin/client/js/directives/partials/productbundle/createproductbundle.ht
ml
Task: https://ten24.teamworkpm.net/tasks/3104543
=> Add loading icons to save bundle btn

admin/client/css/main.css, admin/client/css/main.less, admin/client/js/directives/partials/productbundle/createproductbundle.html, admin/client/js/directives/partials/productbundle/productbundlegroups.html
=> Revert "Add loading icons to save bundle btn"

config/resourceBundles/en.properties
=> Revert "Create orderFulfillmentStatusType rb key"

tags/SlatwallAdminAttributeSetDisplay.cfm
=> Fixed error on attribute sets causing hard error due to null

org/Hibachi/HibachiCacheService.cfc
Hold off on merge until we confirm that this resolves the issue.
=> Fix for caching engine for railo update.

model/process/Order_AddPromotionCode.cfc
Ensure a promo code is entered before checking that it has not already applied to order
=> Feature cart add promo code required

admin/client/js/directives/swproductbundlegrouptype.js, api/views/js/ngslatwall.cfm, model/entity/Type.cfc, model/validation/Type.json
=> Revert "Adds validation for productbundlegrouptype."

model/dao/TypeDAO.cfc, model/service/TypeService.cfc
=> adding typeservice and typeDao

admin/client/js/directives/swproductbundlegrouptype.js, api/views/js/ngslatwall.cfm, model/validation/Type.json
Adds a check to close or not the dialog.
=> Removes unique property on typecode (productbundlegrouptype) at the entity level. 

model/service/OrderService.cfc
from the Order before actually deleting the order payment
=> Wrote a Delete Override for Order Payment to remove the orderPayment

admin/client/js/controllers/collections.js, admin/client/js/directives/partials/productbundle/productbundlegroup.html, admin/client/js/directives/swcollectiontable.js, admin/client/js/directives/swproductbundlegroup.js
Abstracts more of the collection table into its own directive so that it
works the same between product bundles and collections.
=> Fix for product bundles filters not displaying.

admin/client/css/main.css, admin/client/css/main.less
Fix workflow form fields width 
https://ten24.teamworkpm.net/tasks/3311610
=> Workflow fix form fields

admin/client/js/directives/swworkflowtriggers.js, model/service/WorkflowService.cfc
if the entity being watched is the entity itself then wipe the objectpropertyidentifier
=> fixing object property Identifier

model/service/TaskService.cfc
=> if the subscriptionusage is not autorenew we need to update the status

meta/tests/unit/entity/CollectionTest.cfc, meta/tests/unit/entity/OrderItemTest.cfc, meta/tests/unit/service/CollectionServiceTest.cfc, meta/tests/unit/service/WorkflowServiceTest.cfc, model/entity/OrderItem.cfc, model/entity/Sku.cfc, model/process/Order_AddOrderItem.cfc
=> Feature rm unittestfix

api/controllers/js.cfc, api/controllers/main.cfc, api/views/js/ngslatwall.cfm, model/entity/Collection.cfc, model/process/Order_AddOrderItem.cfc, model/service/CollectionService.cfc, model/service/LocationService.cfc, org/Hibachi/HibachiService.cfc
adding ability to retrieve process objects
=> Feature rm processobjectsinngslatwall

admin/client/css/main.css, admin/client/css/main.less, admin/layouts/default.cfm
Remove responsive feature on the nav and body under 992px until we build out a responsive navigation solution.
https://ten24.teamworkpm.net/tasks/3153017
=> remove responsive under 920px until we add new nav

org/Hibachi/HibachiTags/HibachiTimeline.cfm
Fixed system table not to go outside of div.
Task: https://ten24.teamworkpm.net/tasks/3345637
=> Fix systems table to not push outside of div

admin/client/css/main.css, admin/client/css/main.less, admin/client/js/directives/partials/productbundle/productbundlegroup.html
Add loading button to the product bundle
Task: https://ten24.teamworkpm.net/tasks/3227733
=> Add load more button to create bundle

admin/client/css/main.css, admin/client/css/main.less, admin/client/js/directives/partials/collection/addfilterbuttons.html, admin/client/js/directives/partials/collection/collection.html, admin/client/js/directives/partials/collection/displayoptions.html, admin/client/js/directives/partials/collection/filteritem.html
There were a ton of issues like missing divs, table header in the wrong place...  I went through and fixed the original task as well as cleaned up.
Task: https://ten24.teamworkpm.net/tasks/3242652
=> fix collections

admin/client/css/main.css, admin/client/css/main.less
Fix z-index for global modals
https://ten24.teamworkpm.net/tasks/3404962
=> fix z-index on modal

admin/client/js/directives/common/swconfirm.js, admin/client/js/directives/partials/productbundle/productbundlegroup.html, admin/client/js/directives/partials/workflow/workflowtaskactions.html, admin/client/js/directives/partials/workflow/workflowtasks.html, admin/client/js/directives/partials/workflow/workflowtrigger.html, admin/client/js/directives/partials/workflow/workflowtriggers.html, admin/client/js/directives/workflow/swworkflowtasks.js, admin/client/js/directives/workflow/swworkflowtrigger.js, admin/client/js/directives/workflow/swworkflowtriggers.js
Implemented delete trigger with confirmation.
Fixed add new to allow adding a new trigger.
Fixed switching between triggers.
Fixed saving for individual triggers.
Fixed toggle on and off.
=> Implemented triggers to look more like tasks.

admin/client/css/main.css, admin/client/css/main.less, admin/client/js/directives/partials/collection/criteriadate.html
Fix date picker style.
Task: https://ten24.teamworkpm.net/tasks/3060068
=> Set style for date picker

admin/client/css/main.css, admin/client/css/main.less
Add fix for global non editable name
Task: https://ten24.teamworkpm.net/tasks/3403110
=> Fix vendor name width

admin/client/css/main.css, admin/client/css/main.less
Change responsive tables to not float right in audit section
=> Make responsive tables stay block

public/controllers/account.cfc
Send out verification email only if the email address has not been verified
=> Account email address verification

meta/tests/unit/entity/CollectionTest.cfc, meta/tests/unit/entity/OrderItemTest.cfc, meta/tests/unit/service/CollectionServiceTest.cfc, meta/tests/unit/service/OrderServiceTest.cfc, meta/tests/unit/service/SubscriptionServiceTest.cfc, meta/tests/unit/service/WorkflowServiceTest.cfc
=> comment out request.debug as it is not recognized by non-coldfusion

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiAssets/js/global.js, org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
Global search fix of icons in tables to set fixed width
=> fix global icons in tables to fixed width

api/views/js/ngslatwall.cfm, model/entity/HibachiEntity.cfc
support for getting settings from a collection via non-persistent properties
=> still create javascript even if a function is called that requires

admin/client/js/controllers/routercontroller.js, admin/client/js/directives/partials/router.html, admin/client/js/slatwalladmin.js, admin/layouts/default.cfm, api/views/js/ngslatwall.cfm, model/entity/Collection.cfc
=> updates to routing

admin/client/js/directives/collection/swcollectiontable.js, admin/client/js/directives/partials/collection/collectiontable.html, admin/client/js/directives/workflow/swworkflowtriggers.js
Adds a check for null workflow trigger records.
=> Hides edit buttons when there is no view to link to.

admin/client/js/directives/collection/swcollectiontable.js, admin/client/js/directives/partials/collection/collectiontable.html, admin/client/js/directives/workflow/swworkflowtriggers.js
=> Revert "Hides edit buttons when there is no view to link to."

model/service/SkuService.cfc
This was causing error when sorting skuSmartlist by properties not part of sku
=> Remove alternate skus search from skuSmartlist

model/service/WorkflowService.cfc
we were checking whether the task was active however not whether its workflow was active
=> check if workflow is active in order to run the task

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/productbundle/productbundlegroup.html
Merge product bundle layout issues with hotfix branch.
Task: https://ten24.teamworkpm.net/tasks/3368426
=> Product Bundle: fix layout in hotfix

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiAssets/js/global.js, org/Hibachi/HibachiTags/HibachiFormField.cfm
Change file attribute not to use js.
Task: https://ten24.teamworkpm.net/tasks/3392191
=> fix file attribute

api/controllers/main.cfc
to get the skus instead of trying to create them from a java array. This
was causing issues in CF9.
=> Updated the get resizedImageByProfileName function to use a skuSmartlist

admin/views/entity/attributetabs/basic.cfm
fix in the case where an attributesetobejct does not exist
=> check if the we have an attribute setobject

admin/controllers/ajax.cfc, admin/views/entity/skutabs/inventory.cfm, assets/js/admin.js
Ensure that mutli-level nested locations collapse corectly
=> Fix expand / collapse of location quantity table rows

admin/client/css/main.css, org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
Always create html for listing pagination but set to display:none for first page
Ensures that there is ux feedback when adding rows to list via ajax call
=> Hotfix ajax listing display pagination

admin/views/entity/detailfile.cfm, model/entity/HibachiEntity.cfc, model/service/FileService.cfc
ability to get files smartlist
=> Hotfix rm filesmartlist

model/entity/Collection.cfc
now loggin error and HQL if a collection fails to retrieve data
=> Hotfix rm logcollections

model/dao/ProductDAO.cfc, model/service/ProductService.cfc
Products can only be assigned to leaf nodes in parent type tree
=> When creating a child product type move products from parent to new child

admin/layouts/default.cfm, gulpfile.Config.js, gulpfile.js
updating gulp workflow to be more performant
=> Hotfix rm gulpworkflow

admin/client/partials/content/contentnode.html, admin/views/entity/contenttabs/basic.cfm, admin/views/entity/preprocesscontent_create.cfm, config/resourceBundles/en.properties, integrationServices/slatwallcms/skeletonapp/Application.cfc, model/entity/Content.cfc, model/process/Content_Create.cfc, model/service/ContentService.cfc, model/service/SiteService.cfc
making Home template render on a blank urlpath. 
able to create content via preprocess method and edit in detailcontent
=> Feature rm cmsdeployment

admin/views/entity/sitetabs/basic.cfm
adding fields for site editing
=> adding fields for site details editing

meta/tests/unit/service/SiteServiceTest.cfc, model/service/AppService.cfc
bug fix where integration package should be loaded via the IntegrationPackage vs the ID
=> get integrationid via integrationpackage

admin/views/entity/settingstabs/site.cfm, config/resourceBundles/en.properties, model/entity/App.cfc, model/entity/Content.cfc, model/entity/Session.cfc, model/entity/Site.cfc, model/service/AppService.cfc, model/service/OrderService.cfc, model/service/SettingService.cfc, model/service/SiteService.cfc
if we have a new order on a cms site then set the order origin by setting if we have one.
bug fix to make sure skeleton app and site are created upon saving of site and app
=> Feature rm order origin site setting

model/entity/Content.cfc
needed add and remove function helper methods to delete attributes when content is deleted
=> need to be able to delete attributes when deleting content

admin/views/entity/detailcontent.cfm, org/Hibachi/HibachiControllerEntity.cfc
adding ngRedirectQS for hashbang redirects
=> adding ngRedirectQS

model/service/SettingService.cfc
=> if the array of options is empty then jsut use the value as the default

org/Hibachi/HibachiAuthenticationService.cfc
API throws an error rather than showing the noaccess page.
=> fixes an error where if you are not a superuser, trying to access the

integrationServices/slatwallcms/skeletonapp/Application.cfc, integrationServices/slatwallcms/skeletonsite/templates/default.cfm, model/service/SiteService.cfc
bad link try to render 404 if exists otherwise abort;
=> add 404 content with default template upon saving. If we navigate to a

model/service/ContentService.cfc
using directoryList query to address showing of the long directory in windows
=> use query to get short directory

admin/views/entity/contenttabs/basic.cfm, config/resourceBundles/en.properties, model/dao/ContentDAO.cfc, model/entity/Content.cfc
=> simplifying code to maintain the "Material Paths" aka URLTitlePath for

meta/tests/unit/service/UpdateServiceTest.cfc, model/service/UpdateService.cfc, org/Hibachi/Hibachi.cfc, org/Hibachi/HibachiUtilityService.cfc
on update replace the all application.cfcs with the skeletonapp application.cfc
=> Feature rm updateintegrations

admin/client/css/main.css, admin/client/css/main.less, admin/views/entity/producttabs/defaultimages.cfm, config/resourceBundles/en.properties, tags/SlatwallAdminImagesDisplay.cfm
I rebuilt the image upload css and added notification messages.
Task:
https://ten24.teamworkpm.net/tasks/3626855
=> Rebuild the image uploaded

model/report/OrderItemReport.cfc
=> Hotfix ih report type fix

admin/client/css/main.css, admin/client/css/main.less
Fix styling on disabled dropdown
Task: https://ten24.teamworkpm.net/tasks/3717828
=> Hotfix rj fix disabled dropdown

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/formfields/radio.html, org/Hibachi/HibachiTags/HibachiFormField.cfm
I went through slatwall and standardized radio buttons because they where being done differently and have been breaking.
Task: https://ten24.teamworkpm.net/tasks/3717786
=> Hotfix rj radio overlap

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/workflow/workflowtriggers.html, config/resourceBundles/en.properties
Fixed the filter search, and made it work like the others in slatwall.
Task: https://ten24.teamworkpm.net/tasks/3719855
=> Hotfix rj fix trigger search

admin/views/entity/contenttabs/basic.cfm
removing title path from detail view
=> making title editable

model/entity/Content.cfc, model/service/SiteService.cfc
able to specify a delimter for title path
=> fix to site service save

integrationServices/slatwallcms/BaseApplication.cfc, model/dao/ContentDAO.cfc, model/entity/Content.cfc
=> able ot pass in forNavigation to the getChildContentsMethod in order to

model/entity/Collection.cfc, model/transient/HibachiScope.cfc, org/Hibachi/HibachiSessionService.cfc, org/Hibachi/HibachiSmartList.cfc, org/Hibachi/HibachiTransient.cfc
=> all getSession and SetSession methods act upon hibachiScope so that they

model/entity/Collection.cfc, model/transient/HibachiScope.cfc, org/Hibachi/HibachiSessionService.cfc, org/Hibachi/HibachiSmartList.cfc, org/Hibachi/HibachiTransient.cfc
able to override session has and set methods
=> making set and has session value overridable

model/service/UpdateService.cfc
fix for when only functions are specified
=> fix for when only properties are specified.

integrationServices/slatwallcms/BaseApplication.cfc, integrationServices/slatwallcms/templates/navTemplate.cfm, org/Hibachi/HibachiUtilityService.cfc
=> updates to nav

admin/views/entity/detailproduct.cfm, org/Hibachi/HibachiDAO.cfc, org/Hibachi/HibachiEntity.cfc
updating the dao method for get#property#count to use smartlist recordsCount
=> Hotfix rm updating dao method for count

model/entity/Content.cfc, org/Hibachi/HibachiUtilityService.cfc
=> replace templates will introspect results for further mustache

admin/layouts/default.cfm
Add instantiation key to main.css
Task: https://ten24.teamworkpm.net/tasks/3816949
=> add instantiation key to main.css

admin/views/entity/subscriptionusagetabs/basic.cfm
removing extra form wrapper which was causing duplicate subscription
=> duplicate form wrapper 

model/service/ContentService.cfc, model/validation/Content.json
with singles and Capitals with lowercase
=> validate entry is alphanumeric and then if it is replace double dashes

meta/tests/unit/entity/CollectionTest.cfc, model/entity/Collection.cfc
adding api for using collections on the backend
=> Feature rm collection

meta/tests/unit/entity/CollectionTest.cfc, meta/tests/unit/service/HibachiServiceTest.cfc, model/entity/Collection.cfc
=> able to get attributes programattically in filters and display

meta/tests/unit/entity/ProductTest.cfc, model/dao/ProductDAO.cfc, model/entity/Product.cfc, model/service/ProductService.cfc
=> updating product review function to use ORM count and avg. adding unit

model/entity/Image.cfc
to fix MS SQL "ORDER BY items must appear in the select list if SELECT DISTINCT is specified"
=> Add optionGroup.sordOrder property to getOptionsSmartlist 

admin/views/main/login.cfm
utilizes same class as password reset
=> added s-login-reset class to fix the floating login button

integrationServices/payflowpro/Payment.cfc, integrationServices/paypalexpress/Payment.cfc
=> Revert "Added Paypal Integration Code"

admin/client/css/main.css, admin/client/css/main.less
=> Raido buttons change

model/service/AccountService.cfc
is calling getters that shouldn't exist on a one-to-many relationship
=> commented out event registration code 

config/resourceBundles/en.properties, model/process/Sku_ChangeEventDates.cfc, model/validation/Sku_ChangeEventDates.json
These getters were calling getSku and retrieving the current sku therefore the ORM couldn't populate with the real date times.
=> False Getters in Sku_ChangeEvent

model/validation/Product.json
button to merchandise products
=> Updated validation file to only show the add sku and add sku bundle

model/dao/OrderDAO.cfc, model/entity/OrderPayment.cfc, model/service/OrderService.cfc
This is a very important hotfix to get merged in ASAP!  Please contact me directly to review in more detail if you like.
=> Added back necessary validation methods

model/dao/OrderDAO.cfc, model/entity/OrderPayment.cfc, model/service/OrderService.cfc
=> Revert "Added back necessary validation methods"

admin/client/css/main.css, admin/client/css/main.less, admin/views/main/noaccess.cfm
Login screen: 
- fixed the layout for the page if an error
Task: https://ten24.teamworkpm.net/tasks/3865302
=> Login error: fix font size

meta/tests/unit/dao/OrderDAOTest.cfc, meta/tests/unit/entity/OrderPaymentTest.cfc, model/dao/OrderDAO.cfc, model/entity/OrderPayment.cfc, model/service/OrderService.cfc
Added functions back in and tested, created unit tests
=> Hotfix jb peerorderpayments

admin/views/entity/sitetabs/basic.cfm, model/entity/Content.cfc, model/validation/Site.json
adding hiding fields and disabling validation based on if the site is
cms or not
=> fixing bug that didn't allow updating of content without descendants.

admin/client/partials/content/contentnode.html
=> link needs to be relative

config/dbdata/SlatwallUpdateScript.xml.cfm, config/scripts/database/v4_1.cfm
which will allow quicker keyword lookupadding migration script to auto write materialized paths for title path which will allow quicker keyword lookup
=> adding migration script to auto write materialized paths for title path

api/controllers/js.cfc, model/entity/Collection.cfc
changing variable property to propertyKey to make transpiler understand
key easier
=> changes to make slatwall more generic.

admin/controllers/main.cfc, config/resourceBundles/en.properties
not sure what's going on with all the white space in this commit line 285 is the change
=> Changed incorrect Rb key and added new one for password update

model/service/ProductService.cfc
=> Revert "Hotfix"

model/service/ProductService.cfc
=> Revert "Revert "Hotfix""

org/Hibachi/HibachiTags/HibachiEntityProcessForm.cfm
Fixed button issue for firefox.
Task: https://ten24.teamworkpm.net/tasks/3896378
=> Global: button missing class

model/dao/AccountDAO.cfc, model/entity/GiftCard.cfc, model/service/OrderService.cfc
order item gift recipients will automagically be linked to accounts if email address matches
=> Feature jb gift card

admin/client/css/main.css, admin/client/css/main.less, meta/prototypes/design-system.html, meta/prototypes/order-items/order-detail.html
Add a dropdown feature to the design guide to allow people to add accounts through admin.
=> Feature rj gift card order

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/collection/collection.html, config/resourceBundles/en.properties
1) added filters on top of table
2) removed filter toggle
3) moved pageing to bottom of table
=> Hotfix rj collection filters

admin/client/css/main.css, admin/client/css/main.less
Changed image path to work down instead of up.  Fixes issue of it not showing on stand alone installs.
=> Change login image path to work up instead of down

admin/views/main/about.cfm, admin/views/main/log.cfm, integrationServices/endicia/model/SyncUtility.cfc, org/Hibachi/HibachiCacheService.cfc, org/Hibachi/HibachiReport.cfc
=> supporting lucee

admin/client/css/main.css, admin/client/css/main.less, meta/prototypes/design-system.html
Updated changes to add recipient to gift card.
=> All design changes to add recip

admin/client/css/main.css, admin/client/css/main.less, admin/layouts/default.cfm
Fix scroll content issue on swipe screen
=> Fix scroll

admin/client/css/main.css, admin/client/css/main.less
=> change path and add quotes

admin/client/css/main.css, admin/client/css/main.less, admin/views/entity/preprocessorder_addorderpayment.cfm
Fix the html and css for payment amount
=> add fix for form layout

model/entity/Collection.cfc, org/Hibachi/HibachiCollectionService.cfc, org/Hibachi/HibachiControllerREST.cfc
=> only show properties that user is allowed to see for filters and display

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/content/contentlist.html, admin/client/partials/content/contentnode.html
Add padding to arrows and set link title
=> Add arrow padding and set link to title

model/entity/GiftCard.cfc, templates/email/giftcard/credited.cfm
Email template and sending event hook along with gift card payment is now an option
=> Feature jb gift card order

org/Hibachi/HibachiTags/HibachiReportConfigureBar.cfm
=> Feature rj reporting buttons

model/entity/AttributeValue.cfc, model/validation/AttributeValue.json, org/Hibachi/HibachiService.cfc, org/Hibachi/HibachiTransient.cfc, org/Hibachi/HibachiUtilityService.cfc, org/Hibachi/HibachiValidationService.cfc, tags/SlatwallAdminAttributeSetDisplay.cfm
=> adding server side validation for custom attributes via regex and

config/scripts/preupdate/v4_1.cfm, model/entity/Site.cfc, model/service/SiteService.cfc
update script to make sure that sitecode is unique on update and going forward
=> Hotfix rm sitecodeindex

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/collection/criteriaonetomany.html
This pull request is to merge reyjay’s html/css changes into Miguel’s branch
=> add collection feature

meta/tests/unit/entity/CollectionTest.cfc, meta/tests/unit/service/CollectionServiceTest.cfc, model/entity/Collection.cfc, org/Hibachi/HibachiAuthenticationService.cfc, org/Hibachi/HibachiCollectionService.cfc, org/Hibachi/HibachiScope.cfc
=> abstracting collection authentication. fixing alias bug with aggregates.

org/Hibachi/HibachiAuthenticationService.cfc
=> Remove extra "."

model/entity/Collection.cfc
removing dependency on metadata lookup and solving case where id don't follow proper casing conventions for getting collection count.
=> Feature rm collection of collection

org/Hibachi/HibachiCollectionService.cfc
=> Checking if any non persistent column exist, and display

admin/client/ts/directives/collection/swdisplayoptions.ts
new column object refactored to prevent lint warnings
added by default search and export enabled
added ormtype to fix search problems
=> collection related property search

admin/client/partials/propertydisplay.html, admin/client/ts/directives/common/swpropertydisplay.ts, admin/client/ts/filters/percentage.ts, admin/client/ts/model/collectionConfig.ts, admin/layouts/default.cfm, gulpfile.js
sw-property-display directive fix/enhancements
=> Feature mt swpropertydisplay

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/collection/criteriamanytoone.html
Fixed the radio button overlap issue on many to one
=> Collections - criteria - many to one: fix radio

admin/client/css/main.css, admin/client/css/main.less, admin/views/entity/preprocessproduct_addsubscriptionsku.cfm, org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
Create a solution for the alternate table listing title and removed inline css
=> Fix listing display alternate title type and remove inline css

admin/client/ts/services/collectionconfigservice.ts
JAVASCRIPT Exemple:
```javascript
'use strict';
angular.module('slatwalladmin')
.controller('importSurgeon', [
'$scope', '$log', 'CollectionConfigService',
function ($scope, $log, CollectionConfigService) {
$scope.myCollectionConfig = CollectionConfigService.newCollectionConfig('Account');
$scope.myCollectionConfig.setDisplayProperties('firstName, lastName');
$scope.myCollectionConfig.addFilter('firstName', 'Miguel');
$log.debug$scope.myCollectionConfig.getCollectionConfig);
}
]
);
```
=> collection config now is a factory

model/dao/OrderDAO.cfc, model/entity/Order.cfc, model/entity/OrderPayment.cfc, model/service/OrderService.cfc, model/service/PaymentService.cfc
Don't know where the order service diff is
=> Fix for gift card payments

admin/client/ts/services/collectionconfigservice.ts, org/Hibachi/HibachiTags/HibachiPropertyList.cfm
Fix padding on add attribute set
=> Feature rj attribute set padding

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/productbundle/productbundlegroup.html, admin/client/partials/productbundle/productbundlegrouptype.html
=> Fix add bundle layout

admin/views/entity/listorderdelivery.cfm
Add edit functionality to order delivery listing view.
=> add edit function on order delivery listing

admin/layouts/default.cfm
Fixed style on disabled pop up
=> change button style for modal pop

admin/client/css/main.css, admin/client/css/main.less, admin/views/main/login.cfm
Changed the text on the super user login header & added darker font to input text so they don't look like placeholder.
=> Change super user text and make input text darker

admin/client/css/main.css, admin/client/css/main.less, admin/views/entity/detailsetting.cfm
=> Fix file upload red button

model/service/AppService.cfc
verify that the directory exists in case the directory was deleted
=> when updating cms applications with a new baseapplication. We need to

admin/views/entity/detailproduct.cfm
adding count to listingpages tab on product detail
=> Feature rm prodlistcount

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiTags/HibachiReportDataTable.cfm
Fix the pagination on dashboard
=> Feature rj style pagination

model/entity/Collection.cfc
- Added [""] to all collection keys to prevent it to be uppercase
- Added function setDistinct
- Added option to override the ormtype with hb_formatType
=> Added [""] to all collection keys to prevent it to be uppercase

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/listingdisplay.html, admin/client/partials/paginationbar.html
Fix search icon and remove extra no results message
=> remove search no results and fix icon

admin/client/css/main.css, admin/client/css/main.less
I fixed the padding on gift card recipient and also fixed a button issue on the same view
=> fix modal padding and button on gift card recipient

admin/client/partials/listingdisplay.html, admin/client/ts/services/collectionconfigservice.ts
Display aggregate column & CollectionConfig Cleanup
=> Feature mt sw listing display aggregate

model/service/AccountService.cfc
=> Needed to remove the account account from the accountAddress and the

admin/views/entity/stockadjustmenttabs/stockadjustmentitems.cfm
=> Revert "Fixes stockAdjustmentItems display for physicals"

model/service/PromotionService.cfc
=> update to promotion qualifier bug. This allows qualifiers that have a

model/entity/OrderItem.cfc
and not just the ones on that specific orderItem
=> Smartlist was returning all active registrations

admin/views/entity/detailtype.cfm
=> fixing back action for types defaults to detail of parent type

model/entity/HibachiEntity.cfc
a getCustomProperty instead of a setCustomProperty
=> The setAttributeValue function was calling

org/Hibachi/Hibachi.cfc, org/Hibachi/HibachiControllerREST.cfc
fixes collection calls not working from admin. also made same request into feature
=> Hotfix ih update hibachi controller

org/Hibachi/Hibachi.cfc, org/Hibachi/HibachiControllerREST.cfc
fixes issue where collections call not working in admin.
=> Feature ih update hibachi controller

model/entity/Product.cfc
=> when adding a sku set the skucode to the product Code + skucount if a

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiTags/HibachiTabGroup.cfm
Fix image count style and insure it does not break responsibly with number.
=> Add style to badges and make size responsive to number.

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiTags/HibachiFieldDisplay.cfm
Task: https://ten24.teamworkpm.net/tasks/5098711
=> Add class to change selector path

model/entity/Category.cfc
right now
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/3976)
=> can't make urltitle unique without migration. urltitle is driven by mura

org/Hibachi/HibachiValidationService.cfc
redundant functions. normalizing functions
=> fixing bug expecting properties now that param is gone. Consolidating

model/service/UpdateService.cfc
=> Updated the linebreak used in custom properties to work in linux

admin/client/css/main.css, admin/client/css/main.less, admin/views/entity/producttabs/defaultimages.cfm, tags/SlatwallAdminImagesDisplay.cfm
Change images to show thumb for new image
=> Fix global add images

admin/client/css/main.css, admin/client/css/main.less, admin/views/entity/orderitemtabs/basic.cfm
The images in order items views were broke in well.  Replaced well with custom class to re-use
=> Fix images well

model/process/Order_AddOrderItem.cfc
are actually custom properties.
=> Added condtional to the attribute Value check to handle attributes that

model/service/ProductService.cfc
sku code of the skuBundle was being created with the old arrayLen code. Update to use the product.getNextSkuCodeCount() function
=> processProduct_addEventSchedule

admin/client/css/main.css, admin/client/css/main.less, admin/client/src/content/components/contentlist.html, admin/views/entity/listcategory.cfm, admin/views/main/about.cfm, admin/views/main/auditlog.cfm, admin/views/main/default.cfm, admin/views/main/encryptionreencryptdata.cfm, admin/views/main/encryptionupdatepassword.cfm, admin/views/main/log.cfm, admin/views/main/update.cfm, admin/views/report/default.cfm, meta/prototypes/pick-pack-listing.html, org/Hibachi/HibachiTags/HibachiEntityActionBar.cfm, org/Hibachi/client/src/core/components/entityactionbar.html, org/Hibachi/client/src/entity/components/detail.html, org/Hibachi/client/src/entity/components/list.html
This is the same change I did to hotfix.  It removes the blank ul in header and fixes categories header
=> Fix header bar globally and add back to category like on hotfix

model/entity/Sku.cfc
=> making subscription baseproduct type fail safe when searching if we

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiTags/HibachiFormField.cfm
Needed to fix the checkboxes for hibachi
=> Hotfix rj radio attribute checkboxes

model/service/HibachiUtilityService.cfc, model/transient/HibachiScope.cfc
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4061)
=> if we are on slatwallcms then remove missing keys

model/service/ProductService.cfc
Moves resized image function to service.
=> added resized images function in productService

admin/client/css/main.css, admin/client/css/main.less, admin/client/src/giftcard/components/addorderitemgiftrecipient.html
=> Add css fix for dropdown

admin/client/css/main.css, admin/client/css/main.less, admin/client/partials/orderitems.html, config/resourceBundles/en.properties
Added rb key to display no items in table for order items.  Also fixed html structure and commented out unused code within file.
=> Fix order items layout

model/service/OrderService.cfc
=> Revert "fixing emails not going out"

model/service/OrderService.cfc
=> Revert "Revert "fixing emails not going out""

admin/client/css/main.css, admin/client/css/main.less
=> Add pointer to trash icon

admin/client/css/main.css, admin/client/css/main.less
=> Fix pagination

admin/client/src/bundle.js, admin/views/entity/producttabs/listingpages.cfm
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4078)
=> requires editaction

model/entity/HibachiEntity.cfc, model/service/HibachiService.cfc
in this case, use the attributeName instead of rbkey but still get the
data from the property entity. Also no duplicates
=> collections able to detect custom properties that have attributes.

model/dao/PriceGroupDAO.cfc
=> Added checks to make sure there was an arrayLen before trying to grab te

admin/views/entity/accounttabs/productreviews.cfm, admin/views/entity/detailproductreview.cfm, admin/views/entity/producttabs/productreviews.cfm
=> Added reviewTitle and rating to listing displays. Updated detail display

admin/views/entity/pricegrouptabs/assignedaccounts.cfm, org/Hibachi/HibachiEntity.cfc
=> Updated how we are getting the values

admin/views/entity/typetabs/childtypes.cfm, org/Hibachi/HibachiAssets/js/global.js
=> sortContenxt missing for child type sorting.

org/Hibachi/HibachiEventService.cfc
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4097)
=> supporting legacy event handlers

admin/client/css/main.css, admin/client/css/main.less, config/resourceBundles/en.properties, org/Hibachi/client/src/collection/components/editfilteritem.html
Added validation to not allow edit/submit on content unless valid
=> Hotfix rj collactions add message filter

admin/views/entity/producttabs/defaultimages.cfm, tags/SlatwallAdminImagesDisplay.cfm
Fix entire add image area.  Style
=> Fix add image

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiTags/HibachiTimeline.cfm
Fix to resolve spacing issue in header bar and also fix dash table width
=> Hotfix rj header spacing issue

model/service/PublicService.cfc
Adds some methods to public service.
=> Update Public service to latest

model/service/PublicService.cfc
=> Revert "Update Public service to latest"

model/dao/OrderDAO.cfc, model/entity/Order.cfc, model/entity/OrderItem.cfc, model/service/OrderService.cfc
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4108)
=> fix to max and min order quantity issue

model/service/TaxService.cfc
Adding hotfix for Sumit for issue causing error when Slatwall touches order.
=> fix new property being null and not checked so throwing error.

model/service/TaxService.cfc
=> another tax service null check

admin/client/css/main.css, admin/client/css/main.less
Fix pagination align issue in firefox
=> Fix pagination in firefox

integrationServices/mura/model/handler/MuraEventHandler.cfc
Fixes a bug introduced in this commit: https://github.com/ten24/slatwall/commit/a3ede37ed97d96a5dac1b9906e35fe8b00a59211
=> Fixes missing comma bug

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/client/src/core/components/expandablerecord.html, org/Hibachi/client/src/core/components/listingdisplay.html
=> fix levels in contents listing

readme.md
This just ads the travis build status, ga-beacon & fixes a some urls.
=> Simple fix to Readme

model/service/PublicService.cfc
Create account once again just creates an account. I removed the chained call to login and the ormFlush that was commented on.
=> Removed the chained login from public service as well as the ormFlush.

org/Hibachi/client/src/collection/services/collectionconfigservice.ts, org/Hibachi/client/src/core/components/listingcontrols.html, org/Hibachi/client/src/core/components/listingdisplay.html, org/Hibachi/client/src/core/components/selection.html, org/Hibachi/client/src/core/components/swlistingcontrols.ts, org/Hibachi/client/src/core/components/swlistingdisplay.ts, org/Hibachi/client/src/core/components/swlistingfilter.ts, org/Hibachi/client/src/core/components/swlistingfiltergroup.ts, org/Hibachi/client/src/core/components/swselection.ts, org/Hibachi/client/src/core/core.module.ts, org/Hibachi/client/src/core/services/hibachiinterceptor.ts
```
<sw-listing-filter-group>
<sw-listing-filter {...}></sw-listing-filter>
<sw-listing-filter {...}></sw-listing-filter>
</sw-listing-filter-group>
<sw-listing-filter {...}></sw-listing-filter>
```
Radio button in listing display fixed
=> ability to have filtergroups:

meta/tests/unit/service/OrderServiceTest.cfc
fulfillment logic here was unnecessary and throwing populate errors on order
=> fixing order service test

admin/views/entity/detailshippingmethodrate.cfm, admin/views/entity/shippingmethodratetabs/shippingmethodratepricegroups.cfm, config/resourceBundles/en.properties, model/entity/PriceGroup.cfc, model/entity/ShippingMethodRate.cfc, model/service/ShippingService.cfc
This is tested working. I was able to set price groups on shipping rates and have my account only qualify for those rates when my account had price groups associated with it.
=> Feature shipping rate price groups

model/transient/HibachiScope.cfc
=> fixes a typo in hibachiScope where was pulling process object from

meta/tests/unit/core/EntityFormatTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Review on Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4255)
=> to-many require singularname property

org/Hibachi/client/src/basebootstrap.ts
=> fixes bug where switching from mura to slatwall returned a bad app

model/service/AddressService.cfc, model/service/ShippingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4264)
=> Hotfix rm addorder itemperformance

org/Hibachi/HibachiEventService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4267)
=> bug fix that supports legacy event handlers

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiAssets/js/global.js
Fix accordion tabs and arrow js
=> Fix js on accord arrows and fix underline

integrationServices/slatwallcms/BaseApplication.cfc
updated per sumit and ryans comments.
=> Hotfix team get content body by url title new

api/controllers/docs.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4323)
=> adding description metadata

api/controllers/docs.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4330)
=> fixing typo

api/controllers/docs.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4331)
=> should be checking for == not !-

model/entity/Product.cfc, model/entity/SubscriptionUsage.cfc, model/service/HibachiSessionService.cfc, org/Hibachi/Hibachi.cfc, org/Hibachi/HibachiScope.cfc, org/Hibachi/HibachiSessionService.cfc, org/Hibachi/client/src/core/components/swlistingdisplay.ts
fixed a couple spelling issues that I had noticed in the codebase.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4341)
=> Hotfix ih misspellnigs

model/entity/Product.cfc
Reverts ten24/slatwall#4304
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4345)
=> Revert "removing non cf9 compatible closure"

admin/views/entity/detailshippingmethod.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4347)
=> fixing cancel action for shipping method

model/process/Order_AddOrderPayment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4346)
=> adding filter on previous order payment to only list active payments

org/Hibachi/HibachiReport.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4353)
=> fixing reporting dereference scalar value error

org/Hibachi/client/src/collection/components/displayoptions.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4302)
=> Display options columns in alphabetical order

model/validation/Option.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4360)
=> making option code required

model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4367)
=> support for cf10 cfml

org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4369)
=> fixing lucee bug on price groups

meta/ci/version_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4371)
=> upload the bleeding edge hash

org/Hibachi/client/src/collection/components/displayoptions.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4368)
=> Only enable save buttons if is a valid display option

org/Hibachi/HibachiEventService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4366)
=> "Select" removed from first item in typeahead

org/Hibachi/client/src/workflow/components/swworkflowtriggers.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4365)
=> clear Event typeahead after save trigger

model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4372)
=> bug fix where the zip was not unzipping.

admin/views/entity/preprocessproduct_addeventschedule.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4374)
=> adjusting back action for add event schedule

admin/views/entity/detailproductschedule.cfm, model/entity/ProductSchedule.cfc
replicating view from sections of the add event product page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4377)
=> fixing the product schedule detail page

org/Hibachi/HibachiValidationService.cfc
The previous way that his works would be only to ADD rules to existing validation.  The new logic allows you to actually target existing rules and change their behavior as well.
**USE CASE**
Account Create, disable requirement of the "confirm email address" field.
=> Allows for validation rules to actually be overridden in custom file

model/service/OrderService.cfc
Error was being throw on trying to purchase a $0.00 subscription renewal product because some values were null. This pull allows the validation to appear.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4298)
=> Update order service to fix hard error

model/dao/PromotionDAO.cfc
this was the fix for this query so it could work on Oracle as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4375)
=> Hotfix promotiondao updates

integrationServices/slatwallcms/BaseApplication.cfc, integrationServices/slatwallcms/BaseEventHandler.cfc, integrationServices/slatwallcms/model/handler/SlatwallCMSHandler.cfc, model/entity/Session.cfc, model/service/SiteService.cfc, model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4390)
=> Hotfix rm currentsitetohibachiscope

org/Hibachi/HibachiTagService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4394)
=> simplifying cfcoookie fix

integrationServices/ups/Shipping.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4396)
=> Updated ups url

org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4400)
=> no need to remove property if we define  columns on setCollectionObject

admin/views/entity/detailaccountpaymentmethod.cfm, org/Hibachi/HibachiAssets/js/global.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4397)
=> please select option was breaking load visible

admin/client/src/formbuilder/components/formresponselisting.html, admin/views/entity/listform.cfm, org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4398)
=> fixing form listing having angular links and export woes

model/validation/Product_AddEventSchedule.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4401)
=> Event Price is not required

meta/ci/version_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4407)
=> Supplying a message so that CI isn't ever asked to provide one.

config/dbdata/SlatwallSetting.xml.cfm, model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4405)
=> adding default value for accountPaymentTerm

org/Hibachi/HibachiAssets/js/global.js
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4406)
=> provisional fix for reporting dashboard export

org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4415)
=> fixing attributes throwing errors in collections

admin/views/entity/listpaymentterm.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4416)
=> removing detail action as delete for payment term

org/Hibachi/HibachiReport.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4420)
=> converting concat statements to increments for spreadsheetrowcount

model/entity/Order.cfc, model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4418)
=> making semantic and logical adjustments to order.hasSavableOrderPaymentForSubscription

meta/ci/version_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4419)
=> Fixes issue with BE release not having new version# or JS in it

circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4426)
=> Sets up circle to only run browser tests if this is not a fork

admin/views/entity/settingstabs/globaladvanced.cfm, config/resourceBundles/en.properties, meta/tests/integration/admin/navigation_main_settings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4425)
=> fixing incorrect setting name in global advanced partial

meta/docker/slatwall-lucee-nginx/Dockerfile, meta/docker/slatwall-lucee-nginx/docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4428)
=> Fixes the docker auto-build

model/entity/AccountPaymentMethod.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4434)
=> adjusting accountpaymentmethod.isexpired logic to use the truncated year

admin/views/entity/detailaccountpaymentmethod.cfm, model/entity/AccountPaymentMethod.cfc, org/Hibachi/HibachiAssets/js/global.js
HibachiDisplayToggle will now disable and re-enable form inputs when hiding to prevent non-intentional form posting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4430)
=> fixing null-related errrors in account payment method and HibachiDisplayToggle improvement

admin/client/css/main.css, admin/client/css/main.less, admin/client/src/content/components/contentlist.html, admin/layouts/default.cfm, org/Hibachi/HibachiTags/HibachiListingDisplay.cfm, org/Hibachi/client/src/core/components/listingdisplay.html
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4429)
=> Global: Fix missing table row

admin/layouts/default.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4431)
=> instantiation key for js is now based on version number to prevent unwanted caching

meta/tests/unit/service/HibachiUtilityServiceTest.cfc, org/Hibachi/HibachiUtilityService.cfc
unit test for sorted array of structure.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4442)
=> Hotfix ss arrayof sorts testing

org/Hibachi/HibachiAssets/js/global.js
prevents script tags in the view from executing twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4450)
=> adjusting the modal load angular compile to only call .html once

admin/views/entity/listproducttype.cfm, config/resourceBundles/en.properties
the Product Type page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4452)
=> add the Gift Card Product Type under the 'create' down-down button in

model/dao/OptionDAO.cfc
removed AS keyword
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4464)
=> [IN_PROGRESS]Update OptionDAO

admin/views/entity/preprocessaccount_addaccountpayment.cfm
Override the backAction in ActionBar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4468)
=> The Add_Account_Payment_Preprocess, Point Back to Account action Issue.

integrationServices/paypalexpress/Payment.cfc, integrationServices/paypalexpress/controllers/main.cfc
paypalexpress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4470)
=> Added error handling and update how which price we are sending over in

org/Hibachi/HibachiTagService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4473)
=> cfcookie bug fix

model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4477)
=> Hotfix rm custompropertieslinebreakreadonly

model/dao/WorkflowDAO.cfc, model/service/EmailService.cfc, model/service/WorkflowService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4458)
=> Workflow Fixes: Events Cache and SendFromEntityAndEmailTemplate

integrationServices/stripe/Payment.cfc
updates the Stripe integration to use meta data (max 20) and to display the orderitems in the description section. I was able to place an order using my Stripe test account and have that show up on Stripe as meta data fields.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4457)
=> updated the payment.cfc to get inc stripe updates into core.

org/Hibachi/client/src/frontend/frontend.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4487)
=> driving frontend module with hibachiconfig

model/entity/OrderFulfillment.cfc, model/service/OrderService.cfc
fixes problem with auto fulfillment happening on nonpayment capture
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4484)
=> Prevent Auto Fulfillment went setting parameters not met

model/dao/OptionDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4490)
=> Remove AS keyword from queries.

model/service/OrderService.cfc
This is a bug that Tashi had fixed. His fix was slightly different but dicussed with Ryan and he wanted it fixed this way.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4488)
=> move logic for tracking number and label inside the if for shipping

meta/tests/integration/admin/brand_create_no_name_error.json, meta/tests/integration/admin/brand_create_success.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4494)
=> Hotfix gm seltestexample

circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4506)
=> Added 3 more VM's so that test will run quicker

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4507)
=> Remove mura as a requirement from the readme.

org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4510)
=> HasManyRelationFilter fix setter and getter

org/Hibachi/client/src/collection/controllers/collections.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4511)
=> Group by undefined check in SaveCollection

admin/views/entity/detailshippingmethodrate.cfm, model/entity/ShippingMethodRate.cfc, org/Hibachi/HibachiTags/HibachiPropertyDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4516)
=> fixing bug where decimal was not allowing placeholder to work

admin/views/entity/detailproductreview.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4519)
=> show product name and reviewer name in product review

admin/views/entity/detailproduct.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4520)
=> show related product and review count in product detail

admin/views/entity/accounttabs/basic.cfm, org/Hibachi/HibachiTags/HibachiFieldDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4525)
=> able to ignore html edit format

admin/views/entity/subscriptionusagetabs/subscriptionusageaccounts.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4526)
=> Fix edit link for non angular route

model/entity/Product.cfc, org/Hibachi/HibachiValidationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4528)
=> Develop rm skusperformance

admin/views/entity/preprocessaccount_addaccountpayment.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4529)
=> fixing bull error when payment term does not exist

config/resourceBundles/en.properties, model/entity/Form.cfc, public/controllers/form.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4535)
=> Making adjustments to form to support workflow actions

meta/tests/unit/entity/AccountTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4537)
=> example of testing a settings

model/entity/ShippingMethodOption.cfc
This is a revert until a different solution is found here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4539)
=> Update Shipping Method Name

integrationServices/slatwallcms/BaseApplication.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4542)
=> invalidating setting cache for multiple sites

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4543)
=> adding npm script to simplify build process

org/Hibachi/HibachiAssets/js/global.js, org/Hibachi/HibachiTags/HibachiFormField.cfm, org/Hibachi/ckfinder/config.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4546)
=> Hotfix rm ckeditorapplicationkey

custom/assets/.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4548)
=> remove overwriting of custom ckeditor

model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4551)
=> should work for all sites

custom/assets/.gitignore
Reverts ten24/slatwall#4548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4552)
=> Revert "remove overwriting of custom ckeditor"

admin/views/entity/stockadjustmenttabs/stockadjustmentitems.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4555)
=> saving work

org/Hibachi/ckfinder/config.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4556)
=> look up ckfinderaccess by key and then use it

meta/tests/integration/admin/navigation_main_settings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4560)
=> Feature gm seleniumfixes

admin/client/src/optiongroup/components/swoptionsforoptiongroup.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4559)
=> Hotfix ck add sort order to add options

admin/views/entity/formtabs/basic.cfm, admin/views/entity/listform.cfm, config/resourceBundles/en.properties, integrationServices/slatwallcms/skeletonsite/templates/slatwall-form.cfm, model/entity/Form.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4562)
=> adding form name to the form

public/tags/AttributeSetDisplay.cfm, public/tags/FormField.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4570)
=> Develop rm hibachiscopeformura

org/Hibachi/client/src/core/services/hibachiservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4572)
=> fixing auth route in hibachiservice

admin/client/css/main.css, admin/client/css/main.less, org/Hibachi/HibachiTags/HibachiPropertyTableBreak.cfm
Removed inline classes
Fixed table header color
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4568)
=> Detail Pages: fix table styles

config/resourceBundles/en.properties, model/process/Account_Create.cfc, model/service/AccountService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4554)
=> Hotfix ck add access id to create account

org/Hibachi/HibachiTags/HibachiActionCaller.cfm, org/Hibachi/HibachiTransient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4577)
=> fixing hibachiHtmleditformat bug

integrationServices/merchantesolutions/Payment.cfc
Closing curly brace from first half of statement missing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4582)
=> Missing curly brace in if else

model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4585)
=> reversing getter

model/service/TaxService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4584)
=> Add setting service to property list in taxService

config/resourceBundles/en.properties, org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4581)
=> semantic change to form response created time

model/validation/Form.json
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4587)
=> adding validation to form

integrationServices/fedex/Shipping.cfc, integrationServices/ups/Shipping.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4599)
=> failing gracefully

model/service/EventRegistrationService.cfc
not include cancelled registrations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4596)
=> Updated getNonWaitlistedCountBySku to use systemCode as filters and to

meta/tests/unit/SlatwallUnitTestBase.cfc, meta/tests/unit/entity/ProductTest.cfc
.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4588)
=> Write the createTestFile() function in SlatwallUnitTestBase.cfc to test image files 

model/entity/Product.cfc
In the getImageGalleryArray() function. 
Just a small mistake, but override the thisImage.name by the description.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4606)
=> This line should be thisImage.description not thisImage.name

model/service/AttributeService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4608)
=> adding a delete override to attribute value so that files will be deleted

admin/client/src/formbuilder/components/formresponselisting.html, org/Hibachi/client/src/pagination/components/paginationbar.html
add curser type to pagination and fix missing content message
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4607)
=> Develop rj forms response styles

admin/views/entity/detailform.cfm, integrationServices/slatwallcms/BaseApplication.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4612)
=> Develop jb form builder view improvements (in progress)

model/service/FileService.cfc, org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4622)
=> Fix wrong extension

integrationServices/avatax/model/handler/AvataxEventHandler.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4610)
=> added try catch to tax commit funciont

model/entity/Sku.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4611)
=> Added the skuName to the skuDefinition generator

model/entity/AttributeOption.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4615)
=> check to make sure that getAttributeOptionValue is defined

model/entity/Product.cfc
variables is there, but miss the RETURN keyword.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4618)
=> getQuantity() function misses the return in one of its IF statements

model/service/GiftCardService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4630)
=> Changed the get errors to call on the correct var

meta/ci/version_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4640)
=> circleci merge only for integrations

model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4641)
=> Ability to override the available cart and account property

meta/tests/unit/dao/SubscriptionDAOTest.cfc
Create this file to test the SubscriptionDAO.cfc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4638)
=> Create a new test file in meta/tests/unit/dao

meta/tests/unit/service/HibachiUtilityServiceTest.cfc, model/service/HibachiUtilityService.cfc
Make a new branch of this test file, delete those changes of the SlatwallUnitTestBase.cfc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4637)
=> Hotfix yy hibachi utiltiy service query to struct of structures test function

org/Hibachi/client/src/core/services/publicservice.ts, org/Hibachi/client/src/form/components/swform.ts, org/Hibachi/client/src/form/components/swformfield.ts, org/Hibachi/client/src/form/components/swinput.ts, org/Hibachi/client/src/form/components/swpropertydisplay.ts, public/views/templates/partials/login.html
custom events for inputs
bug fix for onErrors and onSuccess not being present
editing true by default for front end
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4644)
=> Develop rm formrevisions

integrationServices/ups/Shipping.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4646)
=> fixing addmessage bug

model/service/PriceGroupService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4649)
=> price group var scope bug

integrationServices/fedex/Shipping.cfc, integrationServices/ups/Shipping.cfc, model/transient/ResponseBean.cfc
being set
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4651)
=> can't use structkey exists on transient because variables scope not

meta/tests/unit/dao/SkuDAOTest.cfc, model/dao/SkuDAO.cfc
Create the SkuDAOTest.cfc file to test getTransactionExistsFlag() function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4643)
=> Hotfix yy suppressed unit tests in sku dao from productcfc

meta/tests/unit/entity/AccountTest.cfc
The deleted one is just the example to show how to change the setting values in unit test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4647)
=> Delete the duplicated functions in AccountTest.cfc

admin/client/src/formbuilder/components/formresponselisting.html, admin/client/src/formbuilder/components/swformresponselisting.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4653)
=> Rbkey and datetime fix for form response(s) listing

model/entity/Content.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4656)
=> can't cascade on many-to-many

admin/views/entity/contenttabs/content.cfm, org/Hibachi/HibachiTags/HibachiPropertyDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4657)
=> allowing preview in content detail

integrationServices/slatwallcms/BaseApplication.cfc, integrationServices/slatwallcms/model/handler/SlatwallCMSHandler.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4660)
=> fixing var scope bug

meta/tests/unit/core/EntityFormatTest.cfc, model/entity/AddressZone.cfc
Write a function to check the delete cascade in many-to-many relationships. Add an annotation of a delete cascade allowed property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4658)
=> Hotfix yy check cascade delete

admin/views/entity/contenttabs/content.cfm, integrationServices/slatwallcms/BaseApplication.cfc, org/Hibachi/HibachiTags/HibachiPropertyDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4662)
=> render content

model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4663)
=> fixing a typo in collection cfc

org/Hibachi/client/src/core/services/hibachivalidationservice.ts, org/Hibachi/client/src/form/components/formfield.html, org/Hibachi/client/src/form/components/propertydisplay.html, org/Hibachi/client/src/form/components/swform.ts, org/Hibachi/client/src/form/components/swformfield.ts, org/Hibachi/client/src/form/components/swinput.ts, org/Hibachi/client/src/workflow/components/workflowtriggers.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4664)
=> Develop rm datetimebug

model/entity/AccountPhoneNumber.cfc, org/Hibachi/client/src/collection/components/swdisplayoptions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4665)
=> join problems in Many to One Display properties & Fix typo in AccountPhoneNumber.cfc

model/service/PublicService.cfc
Fixes errors not showing on frontend. Fixes trying to save the shipping as billing when not needed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4668)
=> Update Public Service

admin/layouts/default.cfm, integrationServices/BaseIntegration.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4667)
=> Ability to create custom integration menu items

org/Hibachi/client/src/collection/components/swdisplayoptions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4669)
=> Fixes RBKey creation for Many to One

model/entity/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4672)
=> custom props fix

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4680)
=> Brands in Product Detail droopdown now ordering alphabetically

model/entity/Collection.cfc, model/entity/HibachiEntity.cfc, org/Hibachi/client/src/collection/components/swdisplayoptions.ts, org/Hibachi/client/src/core/services/metadataservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4674)
=> Fix attribute Collection Display Options and Filters

integrationServices/slatwallcms/BaseApplication.cfc, meta/tests/mxunit/tests/bugs/bug126.cfc, model/entity/Collection.cfc, model/entity/Content.cfc, model/entity/Location.cfc, model/entity/PriceGroup.cfc, model/entity/ProductType.cfc, model/entity/Type.cfc, org/Hibachi/Hibachi.cfc, org/Hibachi/client/src/core/model/transient/basetransient.ts, org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4681)
=> All double semicolons removed

api/controllers/workflow.cfc, org/Hibachi/client/src/workflow/components/swworkflowtrigger.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4684)
=> workflow fixes

model/entity/ProductReview.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4685)
=> product review should have createDatetime in it

admin/views/entity/preprocessorderdelivery_create.cfm, admin/views/entity/settingstabs/globaladvanced.cfm, config/resourceBundles/en.properties, model/service/SettingService.cfc
integration for tracking
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4689)
=> adding a setting to be able to turn off the option to use shippint

org/Hibachi/client/src/collection/components/collectiontable.html, org/Hibachi/client/src/collection/components/sweditfilteritem.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4690)
=> bug fixes for collections

integrationServices/usps/Integration.cfc, integrationServices/usps/RatesV4RequestTemplate.cfm, integrationServices/usps/Shipping.cfc, integrationServices/usps/config/resourceBundles/en.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4691)
=> fixing usps integration

org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4699)
=> caching the serialization step for getConfig

model/entity/Sku.cfc, model/service/PriceGroupService.cfc, org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4702)
=> bug fix for currency

admin/views/entity/settingstabs/globaladvanced.cfm, config/resourceBundles/en.properties, model/service/SettingService.cfc, org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4704)
=> able to define all button threshold

admin/views/entity/detailbrand.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4700)
=> adding count to brand detail

model/dao/OptionDAO.cfc, model/service/OptionService.cfc, model/service/ProductService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4712)
=> performnace update to options

meta/tests/unit/entity/ProductTest.cfc, model/entity/Product.cfc, model/service/ImageService.cfc, org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4713)
=> optimizing the image gallery

meta/tests/unit/entity/ProductTest.cfc, model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4714)
=> optimizing options on product

integrationServices/slatwallcms/BaseApplication.cfc, integrationServices/slatwallcms/skeletonsite/config/rewritemaps.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4715)
=> Develop rm cmsrewrites

org/Hibachi/HibachiTags/HibachiFormField.cfm, public/tags/FormField.cfm, public/views/templates/slatwall-shoppingcart.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4716)
=> fix for double encoded ampersand bug

config/resourceBundles/en.properties, model/validation/Order_AddOrderItem.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4718)
=> sku must be active to add order item 

admin/client/src/orderitem/components/childorderitem.html, admin/client/src/orderitem/components/sworderitemdetailstamp.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4711)
=> adding detail stamps to child order items in product bundles

org/Hibachi/client/src/core/controllers/globalsearch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4719)
=> adding order to the global search

model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4721)
=> supporting default values when searching attributes in collections

admin/views/entity/preprocessproduct_create.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4730)
=> adding site name to contentAccess

admin/views/entity/listsku.cfm, admin/views/entity/skutabs/basic.cfm, meta/tests/unit/service/ProductServiceTest.cfc, meta/tests/unit/service/SkuServiceTest.cfc, model/dao/ProductDAO.cfc, model/service/ProductService.cfc, model/service/SkuService.cfc
skus inactive and published false
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4727)
=> if a product is marked inactive when it used to be active then set all

model/service/GiftCardService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4723)
=> updating calculated properties when adding transactions to gift card

admin/client/src/product/controllers/preprocessproduct_create.ts, admin/views/entity/preprocessproduct_create.cfm, org/Hibachi/client/src/core/components/listingcontrols.html, org/Hibachi/client/src/core/components/listingdisplay.html, org/Hibachi/client/src/core/components/swlistingcontrols.ts, org/Hibachi/client/src/core/components/swlistingdisplay.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4729)
=> fixing product create so that the displayed options reflect parent product types

admin/controllers/ajax.cfc, org/Hibachi/HibachiAssets/js/global.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4733)
=> fixing the limit on all for ajax

meta/tests/unit/entity/ProductTest.cfc, model/entity/Product.cfc, model/entity/Sku.cfc
In Product.cfc and ProductTest.cfc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4673)
=> Edit Suppress annotation and function description format.

model/service/SettingService.cfc, org/Hibachi/HibachiCacheService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4735)
=> Develop rm setting needs

admin/layouts/default.cfm, public/views/templates/slatwall-angular.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4738)
=> updating the js to be driven by reloadkey

org/Hibachi/HibachiSmartList.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4741)
=> Develop pj optimize keyword search in smartlist

org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4742)
=> updating path to json

meta/tests/unit/entity/ScheduleTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4717)
=> Hotfix ss schedule test

model/entity/OrderFulfillment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4703)
=> ensuring update order fulfillment shipping methods is called for up to date rates

model/service/AccountService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4744)
=> adding account address delete fix prevent remove account from being called multiple times

admin/views/entity/preprocessorderdelivery_create.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4747)
=> order delivery create fix

org/Hibachi/HibachiValidationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4752)
=> fixing bug with delete validation

integrationServices/paypalexpress/Payment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4745)
=> Fix in paypal express when using promotion

admin/views/entity/ordertabs/promotions.cfm, config/resourceBundles/en.properties, model/entity/Order.cfc
that were added to the order but didn't get applied
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4753)
=> modifying promotion code tab so that is also shows promotion codes 

admin/client/src/giftcard/components/addorderitemgiftrecipient.html, admin/client/src/giftcard/components/swaddorderitemgiftrecipient.ts, admin/client/src/giftcard/components/sworderitemgiftrecipientrow.ts, admin/client/src/giftcard/controllers/preprocessorderitem_addorderitemgiftrecipient.ts, admin/client/src/giftcard/models/giftrecipient.ts, org/Hibachi/HibachiTags/HibachiFormField.cfm, org/Hibachi/client/src/core/model/transient/adminrequest.ts, org/Hibachi/client/src/core/services/baseentityservice.ts, org/Hibachi/client/src/core/services/hibachiservicedecorator.ts, org/Hibachi/client/src/core/services/observerservice.ts, org/Hibachi/client/src/form/components/swformfield.ts, org/Hibachi/client/src/form/components/swinput.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4758)
=> Develop rm bindingupdatesandgiftcard

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4760)
=> defualt sku image gallery

model/entity/Audit.cfc, model/entity/FileRelationship.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4759)
=> adding baseID indexes

admin/views/entity/contenttabs/content.cfm, admin/views/entity/preprocessaudit_rollback.cfm, model/entity/Content.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4761)
=> don't sanitize audit wysiwyg

model/process/OrderDelivery_Create.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4762)
=> tracking bug fix

org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4763)
=> if we don't have a baseURL defined default it to /

org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4765)
=> updating how we use path

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4767)
=> only include active skus in getSkuOptionDetails

meta/tests/unit/entity/LocationConfigurationTest.cfc, model/entity/Location.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4756)
=> Hotfix ss location configuration test

org/Hibachi/HibachiController.cfc
this.publicMethods = ""; was listed twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4768)
=> Removed duplicate line of code

meta/tests/unit/service/InventoryServiceTest.cfc
* Unit test two functions getQATS() & getQIATS() in InventoryService.cfc that are suppressed from Product.cfc
* Unit test other quantity related functions in InventoryDAO.cfc
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4769)
=> Create the InventoryServiceTest.cfc and unit test InventoryOrder.cfc

model/process/Order_AddOrderItem.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4754)
=> Ability to add order item by skucode

custom/config/.gitignore
These should be in gitignore as they are generated at runtime.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4771)
=> Added custom config.json and resoucesBundles to gitignore

meta/ci/version_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4775)
=> Fixes versioning

integrationServices/fedex/Shipping.cfc, integrationServices/ups/Shipping.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4777)
=> udating to not use the url variable as it causes confusion for lucee

readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4782)
=> Updating readme to include Lucee

org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4783)
=> bug fix for email templates

admin/views/entity/preprocessproduct_create.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4781)
=> fix for pagination when searching the option listing while creating a product

org/Hibachi/client/src/form/components/propertydisplay.html, org/Hibachi/client/src/form/components/swinput.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4786)
=> Fix propertyDisplay update when "editing" flag changes

org/Hibachi/client/src/core/services/observerservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4789)
=> ObserverService Events not case sensitive

model/entity/OrderFulfillment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4794)
=> preventing null error if the order fulfillments order lacks an account

model/entity/OrderFulfillment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4796)
=> missing paren

admin/layouts/default.cfm, org/Hibachi/HibachiTags/HibachiActionCaller.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4799)
=> ignoring htmledit format on change language

admin/layouts/default.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4800)
=> making reload slatwall dynamic

model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4804)
=> Removing default from email reply to

admin/views/entity/detailorderdelivery.cfm, admin/views/entity/ordertabs/orderdeliveries.cfm, admin/views/entity/preprocessorderdelivery_create.cfm, admin/views/entity/preprocessorderfulfillment_fulfillitems.cfm, config/resourceBundles/en.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4802)
=> ux improvement in the order fulfillment and delivery areas

model/service/EventRegistrationService.cfc
=> Updated getNonWaitlistedCountBySku to not include the notPlaced

admin/views/entity/listorder.cfm, admin/views/main/default.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4805)
=> adding filters to order listings

admin/views/entity/preprocessproduct_create.cfm, config/resourceBundles/en.properties, model/process/Product_Create.cfc, model/service/ProductService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4806)
=> Adding List Price to Product Create

org/Hibachi/client/src/collection/components/swdisplayoptions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4815)
=> Fix property identifier creation in Collections Display Options

org/Hibachi/client/src/collection/components/displayitem.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4817)
=>  Display options sorted alphabetically  

org/Hibachi/client/src/core/components/swselection.ts, org/Hibachi/client/src/core/services/selectionservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4826)
=> selection core changes from pricing manager - merchandising

org/Hibachi/client/src/core/components/modallauncher.html, org/Hibachi/client/src/core/components/modalwindow.html, org/Hibachi/client/src/core/components/swmodallauncher.ts, org/Hibachi/client/src/core/components/swmodalwindow.ts, org/Hibachi/client/src/core/core.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4825)
=> Modal Directives

org/Hibachi/client/src/core/components/swdraggable.ts, org/Hibachi/client/src/core/components/swdraggablecontainer.ts, org/Hibachi/client/src/core/core.module.ts, org/Hibachi/client/src/core/services/draggableservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4824)
=> Draggable Directives and Service for Core

org/Hibachi/client/src/core/components/swtypeaheadinputfield.ts, org/Hibachi/client/src/core/components/swtypeaheadmultiselect.ts, org/Hibachi/client/src/core/components/swtypeaheadremoveselection.ts, org/Hibachi/client/src/core/components/swtypeaheadsearch.ts, org/Hibachi/client/src/core/components/typeaheadinputfield.html, org/Hibachi/client/src/core/components/typeaheadmultiselect.html, org/Hibachi/client/src/core/components/typeaheadremoveselection.html, org/Hibachi/client/src/core/components/typeaheadsearch.html, org/Hibachi/client/src/core/core.module.ts, org/Hibachi/client/src/core/services/typeaheadservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4822)
=> Pricing Manager + Merchandising Typeahead Changes

org/Hibachi/client/src/core/filters/swcurrency.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4823)
=> fixing null errors in swcurrency filter

org/Hibachi/client/src/core/components/swclickoutside.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4820)
=> swclickoutside fix

org/Hibachi/client/src/core/components/swcollectioncolumn.ts, org/Hibachi/client/src/core/components/swcollectionconfig.ts, org/Hibachi/client/src/core/components/swcollectionfilter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4821)
=> Bringing in changes to the collection column config and filter directives

org/Hibachi/client/src/collection/services/collectionservice.ts, org/Hibachi/client/src/workflow/services/scheduleservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4813)
=> Custom Services Extends baseService to prevent newEntity error

model/dao/WorkflowDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4828)
=> Fix whitespace in hql select clause

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4829)
=> fixes to product cfc missing from hotfix merge, fixes develop build

model/dao/InventoryDAO.cfc
add to cart or sku detail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4834)
=> fixes some queries in inventoryDAO that make it so skus will error on

org/Hibachi/HibachiTransient.cfc, org/Hibachi/HibachiValidationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4831)
=> Safeguarding against unexpected validation success/failure with floating point

model/entity/Session.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4835)
=> adding index for cookie lookup

config/scripts/preupdate/v4_5.cfm, model/entity/Account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4836)
=> only run the preupdate script if and only if  we have the table

config/scripts/preupdate/v4_5.cfm, model/entity/Account.cfc
Reverts ten24/slatwall#4836
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4837)
=> Revert "only run the preupdate script if and only if  we have the table"

model/entity/Account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4838)
=> removing custom proprety goof

org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4840)
=> attributemodel https bug fix

org/Hibachi/client/src/collection/components/collectiontable.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4847)
=> Fix aggregate column order and remove unnecessary loop

custom/config/.gitignore
Just changed it to only ignore .json files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4849)
=> Updated .gitIgnore for custom properties

org/Hibachi/HibachiSmartList.cfc
object instead of an array.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4844)
=> Created smartlist function for getFirst record which only returns one

model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4852)
=> bug fix for integrations that have settingoptions hardcoded

config/scripts/preupdate/v4_5.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4859)
=> preupdate fix for when the column is not present

model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4860)
=> setting service patch

org/Hibachi/client/src/collection/components/collectiontable.html, org/Hibachi/client/src/collection/components/columnitem.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4863)
=> truncating display item title

admin/controllers/entity.cfc, admin/views/entity/subscriptionusagetabs/orderitems.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4865)
=> able to navigate to order from orderitem

model/entity/SubscriptionUsage.cfc
arraylen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4866)
=> updating function to get items from subscription usage and to not use

admin/views/entity/detailcollection.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4867)
=> http to https

model/entity/SubscriptionUsage.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4868)
=> Simplified Methods

model/service/TemplateService.cfc
This is needed in regards to Ryan's hotfix on baseURL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4870)
=> Removed leading / from getTemplateFileIncludePath

admin/client/src/formbuilder/components/formresponselisting.html, admin/controllers/entity.cfc, model/entity/AttributeValue.cfc, model/entity/FormResponse.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4871)
=> able to delete formresponse

integrationServices/paypalexpress/Payment.cfc
so the correct amount is charged
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4858)
=> adding a line item for gift card in the paypal express integration 

model/validation/OrderFulfillment.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4856)
=> making sure we have a shipping method when fulfilling items

model/entity/Order.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4855)
=> fixing order tax calculation for bundles

admin/client/src/orderitem/components/childorderitem.html, model/entity/Order.cfc, model/entity/OrderItem.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4854)
=> fixing to discount calculation and display with product bundles

model/validation/Form.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4862)
=> making form name required

model/entity/Address.cfc, model/entity/AttributeSet.cfc, model/entity/AttributeValue.cfc
Moved this to hotfix per Ryans request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4872)
=> Hotfix address as attribute object

model/entity/WorkflowTrigger.cfc, org/Hibachi/HibachiEventService.cfc, org/Hibachi/client/src/core/services/hibachiservicedecorator.ts, org/Hibachi/client/src/form/components/swinput.ts, org/Hibachi/client/src/workflow/components/swworkflowtriggers.ts, org/Hibachi/client/src/workflow/components/workflowtriggers.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4877)
=> Hotfix rm workflowbugfixes

model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4879)
=> Hotfix rm emailservice

config/configORM.cfm, integrationServices/mura/Integration.cfc, integrationServices/slatwallcms/skeletonsite/tags/AddressForm.cfm, integrationServices/slatwallcms/skeletonsite/templates/slatwall-product.cfm, model/service/ImageService.cfc, model/service/UpdateService.cfc, org/Hibachi/HibachiAssets/js/global.js, org/Hibachi/HibachiAssets/js/hibachi-scope.js, org/Hibachi/HibachiScope.cfc, org/Hibachi/HibachiTags/HibachiEntityDetailForm.cfm, org/Hibachi/HibachiTags/HibachiEntityProcessForm.cfm, org/Hibachi/HibachiTags/HibachiReportViewer.cfm, org/Hibachi/ckeditor/config.js, public/tags/AddressForm.cfm, public/views/templates/slatwall-product.cfm, tags/SlatwallAddressDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4881)
=> Hotfix ck base url slash issue

org/Hibachi/HibachiService.cfc
I had abstracted this method into its own function for another project. adding it here to make update safe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4884)
=> updates the export function and adds a new helper.

model/service/UpdateService.cfc
adding service function for migrating custom properties
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4885)
=> Hotfix rm custompropertymigrator

config/configORM.cfm, integrationServices/mura/Integration.cfc, integrationServices/slatwallcms/skeletonsite/tags/AddressForm.cfm, integrationServices/slatwallcms/skeletonsite/templates/slatwall-product.cfm, model/service/ImageService.cfc, model/service/UpdateService.cfc, org/Hibachi/HibachiAssets/js/global.js, org/Hibachi/HibachiAssets/js/hibachi-scope.js, org/Hibachi/HibachiScope.cfc, org/Hibachi/HibachiTags/HibachiEntityDetailForm.cfm, org/Hibachi/HibachiTags/HibachiEntityProcessForm.cfm, org/Hibachi/HibachiTags/HibachiReportViewer.cfm, org/Hibachi/ckeditor/config.js, public/tags/AddressForm.cfm, public/views/templates/slatwall-product.cfm, tags/SlatwallAddressDisplay.cfm
Reverts ten24/slatwall#4881
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4888)
=> Revert "Hotfix ck base url slash issue"

org/Hibachi/Hibachi.cfc, org/Hibachi/client/src/basebootstrap.ts, org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4889)
=> Hotfix rm revertbaseurl

admin/controllers/main.cfc, admin/views/entity/settingstabs/globaladvanced.cfm, admin/views/main/update.cfm, config/resourceBundles/en.properties, meta/ci/version_merge.sh, model/service/SettingService.cfc, model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4891)
=> Hotfix rm dlhotfixandcustombranches

model/process/Order_AddOrderItem.cfc
adds the ability to use skuCode to add orderItems instead of skuID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4875)
=> add an orderitem using skuCode instead of skuID

org/Hibachi/client/src/core/components/swlistingdisplay.ts, org/Hibachi/client/src/workflow/components/swworkflowtaskactions.ts, org/Hibachi/client/src/workflow/components/workflowtaskactions.html
ids correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4895)
=> bug fixes for listing display. making attach observers unique. detaching

org/Hibachi/client/src/workflow/components/workflowtriggers.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4896)
=> removing rogue binding

meta/tests/integration/se-interpreter/step_types/include.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4894)
=> simplifying include

org/Hibachi/client/src/core/services/hibachiinterceptor.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4902)
=> template cache is based on instantiationkey

model/service/WorkflowService.cfc, org/Hibachi/client/src/core/services/hibachivalidationservice.ts, org/Hibachi/client/src/workflow/components/swworkflowtrigger.ts, org/Hibachi/client/src/workflow/components/workflowtrigger.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4901)
=> Remove orm flush from Workflow Events when saving history

model/service/TemplateService.cfc
=> Revert "Removed leading / from getTemplateFileIncludePath"

model/process/SubscriptionUsage_Renew.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4904)
=> Null and date check for expiration date

model/entity/ShippingMethodOption.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4903)
=> Fix for entity case

meta/tests/unit/entity/CollectionTest.cfc, model/entity/Collection.cfc, org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4913)
=> Hotfix rm bad collectionfix

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4917)
=> Fixes issue with "size" not being part of the resizeSizes argument.

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4918)
=> Additional struct key checking on resizing images

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4919)
=> forgot semi-colon

circle.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4920)
=> Creates backup of db after setup complete

meta/tests/integration/se-interpreter/utils/se_sauce_junit_listener.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4921)
=> Sets db back to snapshot after every test

model/service/SettingService.cfc
fixing stale cache bug for setting
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4923)
=> clear cache when deleting setting

api/controllers/public.cfc, org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4924)
=> Hotfix rm applicationjsonforcontenttypeonpublicservice

model/validation/Product.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4930)
=> Removed event from addSku context

integrationServices/mura/model/handler/MuraEventHandler.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4935)
=> Added sku name setter in mura event handler

model/service/HibachiService.cfc, org/Hibachi/HibachiControllerREST.cfc, org/Hibachi/HibachiEntity.cfc, org/Hibachi/client/src/collection/components/swcriterianumber.ts, org/Hibachi/client/src/core/services/hibachiservice.ts, org/Hibachi/client/src/workflow/components/swworkflowcondition.ts, org/Hibachi/client/src/workflow/components/swworkflowtaskactions.ts, org/Hibachi/client/src/workflow/components/swworkflowtasks.ts, org/Hibachi/client/src/workflow/components/swworkflowtrigger.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4914)
=> Non persistent properties in Workflow conditions & more Numeric condition filters

model/dao/ProductDAO.cfc, model/entity/ProductSchedule.cfc, model/service/ProductScheduleService.cfc, model/service/SkuService.cfc
product. Also added a delete override to make sure that if the last sku
is being deleted then we need to delete the product schedule as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4929)
=> Created new non-persistent property to get the first scheduled sku of a

admin/views/entity/listcategory.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4925)
=> adds the delete action to the category listing

model/service/OrderService.cfc
Updates orderservice to fix hard error found in custom project on updating to latest stable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4916)
=> Updates OrderService

model/service/ShippingService.cfc
Found this on startup of latest stable in a custom project. Wrapping it fixes it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4915)
=> Update Shipping Service

model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4934)
=> Fixes resizeImageData variable to be consistent with pre 4.5

admin/client/css/main.less, org/Hibachi/client/src/collection/components/columnitem.html, org/Hibachi/client/src/core/core.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4940)
=> extracting reyjays changes

org/Hibachi/DI1/ioc.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4947)
=> di/1 update to 1.1

org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4948)
=> Develop rm di1update

model/service/EncryptionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4949)
=> bug fix for encyptionservice

config/resourceBundles/en.properties, model/entity/OrderPayment.cfc, model/validation/OrderPayment.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4950)
=> prevent duplicate gift card order payments on an order

model/entity/Sku.cfc
configuration
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4957)
=> Updated skuDefinition to not apply <br> to the end of every location

admin/views/entity/detailproductreview.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4954)
=> Update hb:HibachiTabGroup to hb:HibachiEntityDetailGroup

templates/email/order/confirmation.cfm, templates/print/order/invoice.cfm
invoice templates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4944)
=> Added orderPayment status type check to the order confirmation and

config/configORM.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4958)
=> Fixes bug with Mura7 datasource defaults

meta/tests/unit/entity/CollectionTest.cfc, model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4963)
=> able to removefilter from collection

config/configORM.cfm, model/service/IntegrationService.cfc, org/Hibachi/HibachiObject.cfc, org/Hibachi/HibachiService.cfc, org/Hibachi/HibachiUtilityService.cfc
Extracting Ryans work:
- integration service Entities
- isThread helper
- List of Process Methods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4968)
=> integration Model, isThread helper, List of Process Methods

admin/views/main/update.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4969)
=> fixing the local.customBranchType is undefined error

org/Hibachi/HibachiDataService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4966)
=> ability to convert csvs directly to queries to prevent problems with cfspreadsheet memory errors

admin/views/main/update.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4971)
=>  style custom branch input in update.cfm

model/entity/Collection.cfc, model/transient/data/DataRequestBean.cfc, model/transient/data/DataResponseBean.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4979)
=> updates from elastic

admin/views/entity/preprocessaudit_rollback.cfm, model/entity/Audit.cfc, org/Hibachi/HibachiAuditService.cfc, org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4980)
=> Hotfix rm bugfixfortimelineauditandsystemstab

integrationServices/slatwallcms/BaseApplication.cfc, model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4981)
=> Hotfix rm templateformatting

model/entity/OrderFulfillment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4976)
=> fetching the name of the integration that was used to get the rate

model/transient/fulfillment/ShippingRequestBean.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4977)
=> Puerto rico is considered to be a US rate request by USPS

model/dao/HibachiDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4983)
=> endless loop fixed

public/tags/Recaptcha.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4984)
=> making function unique to form

meta/tests/unit/service/ImageServiceTest.cfc, org/Hibachi/HibachiTransient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4986)
=> Hotfix rm alternativeimagevalidation

integrationServices/usps/Shipping.cfc, model/transient/fulfillment/ShippingRequestBean.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4989)
=> Fixes for USPS international shipping functionality

org/Hibachi/client/lib/angular-lazy-bootstrap/bootstrap.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4994)
=> if angular fials then bootstrap ui.bootstrap exclusively

model/entity/Collection.cfc, org/Hibachi/client/src/collection/components/swconditioncriteria.ts, org/Hibachi/client/src/collection/components/swcriteriadate.ts, org/Hibachi/client/src/collection/components/sweditfilteritem.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4993)
=> Exact N days, months, years Filters in Collections

model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5001)
=> Added isNew check to clear cart before deleting the order

org/Hibachi/HibachiTransient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5008)
=> removing form default to fix attribute save bug

model/entity/Account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5009)
=> making full name a calculated field

meta/tests/unit/entity/AccountTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5012)
=> updating tests

model/entity/EntityQueue.cfc, model/entity/EntityQueueHistory.cfc, org/Hibachi/HibachiEntityQueueDao.cfc, org/Hibachi/HibachiEntityQueueService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5015)
=> updates to entityqueue

model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5017)
=> use formatValues in string replace for emails

config/dbdata/SlatwallUpdateScript.xml.cfm, config/resourceBundles/en.properties, config/scripts/database/v4_5.022.cfm, config/scripts/database/v4_5.cfm, model/entity/Address.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5018)
=> updating address simple rep to a calculated field

admin/views/entity/detailsku.cfm, admin/views/entity/producttabs/skusettings.cfm, admin/views/entity/producttypetabs/skusettings.cfm, admin/views/entity/settingstabs/sku.cfm, admin/views/entity/skutabs/skusettings.cfm, config/resourceBundles/en.properties, model/entity/Sku.cfc, model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5020)
=> able to disable event conflicts by sku setting

public/tags/Recaptcha.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5025)
=> Replace parent with find to resolve form-group warpper issue

org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5024)
=> ModifiedByAccount Fixes

meta/tests/unit/entity/CollectionTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5023)
=> Exact date filter Unit test

model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5014)
=> Smtp fixes to emailService

integrationServices/mura/model/handler/MuraEventHandler.cfc, model/dao/ContentDAO.cfc, model/service/ContentService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5028)
=> bug fix for mura for when we move categories

model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5030)
=> bug fix for cross platform parsing

org/Hibachi/HibachiEntityParser.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5031)
=> fixes bug for windows precommits

config/resourceBundles/en.properties, meta/tests/unit/entity/ProductTest.cfc, model/dao/ProductDAO.cfc, model/entity/Product.cfc, model/service/ProductService.cfc
it updated on saveProductReview
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5027)
=> Added code to turn getProductRating into a calculated property and have

model/transient/payment/TransactionResponseBean.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5034)
=> changed getavscode method to public

admin/views/entity/listorderitem.cfm, model/dao/TypeDAO.cfc, model/service/TypeService.cfc
is specified as the second argument. Also updated the listOrderItem view
to include any created orderStatusTypes as well in the filter
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5033)
=> Updated getTypeBySystemCode to return the default type unless a typeCode

org/Hibachi/HibachiAuditService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5007)
=> Check if application is in thread before run Audit in thread.

model/service/HibachiUtilityService.cfc, org/Hibachi/HibachiService.cfc
This moves the better version of this function into core hibachi and delegates to it from slatwall.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5003)
=> updates to hibachi and slatwall export.

org/Hibachi/HibachiSessionService.cfc
logged out. Also fixes an issue with login between Mura and slatwall. Also fixes a persist order error on save at the end of the request. This is in use in another project and I'm also using it locally to stop the issues in my local develop branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5037)
=> updates develop to stop the issues with showing that your are partially

model/entity/AccountRelationship.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5038)
=> fixing casing issue

integrationServices/usps/Shipping.cfc
Also, we don't need to run rate request in test mode
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5039)
=> shipping request bean doesn't have order in it

model/service/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5042)
=> fix for null active flag

meta/tests/unit/core/SmartListTest.cfc, org/Hibachi/HibachiSmartList.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5043)
=> filteroptions can use parent propertyIdentifier

org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5041)
=> Moved timeout setting up in application startup

admin/client/src/content/components/swsiteselector.ts, admin/client/src/sku/components/swimagedetailmodallauncher.ts, admin/client/src/sku/components/swskupriceedit.ts, admin/client/src/slatwall/components/swcurrencyformatter.ts, org/Hibachi/client/src/core/components/swnumbersonly.ts, org/Hibachi/client/src/form/components/swformfieldreverthelper.ts, org/Hibachi/client/src/form/components/swinput.ts, org/Hibachi/client/src/form/components/swpropertydisplay.ts, org/Hibachi/client/src/workflow/components/swworkflowconditiongroupitem.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5045)
=> updating typings

admin/client/src/productbundle/services/productbundleservice.ts, org/Hibachi/client/src/core/services/cacheservice.ts, org/Hibachi/client/src/core/services/draggableservice.ts, org/Hibachi/client/src/core/services/expandableservice.ts, org/Hibachi/client/src/core/services/filterservice.ts, org/Hibachi/client/src/core/services/historyservice.ts, org/Hibachi/client/src/core/services/scopeservice.ts, org/Hibachi/client/src/core/services/typeaheadservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5052)
=> making the cacheservice and typeahead service minification safe along with others

admin/client/src/content/components/swassignedproducts.ts, meta/tests/unit/service/ProductServiceTest.cfc, model/entity/Content.cfc, model/entity/Product.cfc, model/entity/ProductListingPage.cfc, model/service/ProductService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5054)
=> Fixing Saving And Deleting Product Listing Pages

model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5047)
=> If no columns is selected, return IDs (instead of objects)

admin/views/entity/detailcontent.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5055)
=> adding count to productlistingpages in detailcontent

config/scripts/database/indexes.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5048)
=> Index creation only needed on sql server

org/Hibachi/client/src/core/core.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5056)
=> Missing Directive Import for SwOrderByControls

org/Hibachi/client/src/core/components/swlistingcontrols.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5057)
=> making the listing display options toggle if you click either button or close symbol

admin/client/src/content/components/assignedproducts.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5058)
=> changing the columns visible in the content merchandising listing

model/dao/AccountDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5060)
=> setting max records to 1 when getting the active authentication for an account

admin/client/src/sku/components/pricingmanager.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5062)
=> changing sku description to be sku definition in pricing manager

admin/client/src/sku/components/pricingmanager.html, admin/client/src/sku/components/swpricingmanager.ts, admin/views/entity/producttabs/skus.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5063)
=> hiding QOH in pricing manager if track inventory isn't turned on

model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5059)
=> fixing missing setting error on settings page

model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5067)
=> ensuring that calculated properties update with proper values when settings change

admin/client/src/orderitem/components/orderitem.html, admin/client/src/orderitem/components/orderitems.html, admin/client/src/orderitem/components/sworderitems.ts, admin/views/entity/orderfulfillmenttabs/orderfulfillmentitems.cfm, admin/views/entity/ordertabs/orderdeliveries.cfm, admin/views/entity/ordertabs/orderfulfillments.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5068)
=> Hotfix rm locationnametoorderitemlisting

model/service/OrderService.cfc
=> bug fix for when orders are forced through even though there was a

meta/tests/unit/core/EntityFormatTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5078)
=> tests that cfcs for properties are case-sensitive

model/entity/SkuPrice.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5077)
=> Fix typo for case

meta/tests/unit/entity/OrderItemTest.cfc, model/entity/OrderItem.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5083)
=> Hotfix rm luceebugextendedprice

model/service/ShippingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5088)
=> adding a simple comment

model/service/ShippingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5084)
=> fixing fulfillment items getting deleted/readded over the course of the request

org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5081)
=> adding level of caching to public service to prevent duplicate requests accross services

model/service/PriceGroupService.cfc
Price comparison fix.. and a few typo fixes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5072)
=> Price comparison fix

model/service/AccountService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5091)
=> only use undeer create context

admin/client/src/content/components/assignedproducts.html, admin/client/src/content/components/swassignedproducts.ts, org/Hibachi/client/src/core/components/swcollectioncolumn.ts, org/Hibachi/client/src/core/services/listingservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5085)
=> fixing blank fields when adding products to content 
