ten24/slatwall

admin/client/js/controllers/pagedialog.js

applying new url for hash navigation when hashbang routing is used

fix to anchorScroll with new hashbang urls

---

org/Hibachi/HibachiTags/HibachiListingDisplay.cfm

Removed the boolean being displayed.  There didn't seem to be a need to display true/false to end user. This was not in Master either.

Removed variable displaying boolean value in HibachiListingDisplay

---

admin/client/js/directives/partials/collection/filtergroupitem.html

bug where filter groups would not show when clicking on the filter group because of no reason for the ng-if 1 === 0

no reason for the ng-if 1 === 0

---

admin/client/js/controllers/collections.js

entities like orderItem and orderPayment.

Just running the lowercase function cause the code to break on camelCase

---

model/entity/Collection.cfc

keyword was dependent on orderid being a searchable field

keyword dependent on orderid

---

admin/client/js/services/slatwallInterceptor.js
api/controllers/main.cfc

dealing with query strings that are too long.
using the client side interceptor to detect if the request is a GET and not for a partial
then converting it to a POST method using the serializedJsonData parameter with a context of GET

Feature rm product bundle querystringlength

---

api/views/js/ngslatwall.cfm

data.12details is not valid javascript but data['12details'] is.

fix for attribute codes prefixed with numbers

---

admin/client/js/directives/partials/productbundle/productbundlegroup.html
admin/client/js/directives/productBundleGroup/swproductbundlegroup.js

so that it is an [x] if editing and a trash otherwise. This allows the one button to be used for both toggle
and delete.

Fixed Product Bundle Group [x] button 

---

model/service/UpdateService.cfc

adding the apps folder to the exclusions list when updating slatwall

excluding the apps folder from deletion when updating slatwall

---

api/controllers/main.cfc

squashing the rb key bug. Discovered to be an unvar scoped variable

fixing unvarscoped variable

---

integrationServices/mura/model/handler/MuraEventHandler.cfc

This is a simple typo fix for a recent addition to the mura install logic.

Fixes an issue from the mura install side.

---

model/entity/Schedule.cfc
model/service/TaskService.cfc
org/Hibachi/HibachiAuditService.cfc

1. thread request account does not have a primary address set
2. when run as scheduled task task history not being saved after run, so never setting end time/success flag
3. when run as scheduled task & task schedule end set to "forever" then endDateTime was undefined so final stage of scheduled task was aborting on error with no log/error email sent

3 part fix for update calculated properties task

---

admin/views/error/default.cfm

Removing the mailpart tags resolves issue 3343,
https://github.com/ten24/slatwall/issues/3343, where error emails to
gmail are blank. I also added some other cgi variables that are helpful
when debugging.

Resolve issue with blank error emails

---

admin/client/ts/directives/productBundleGroup/swproductbundlegroup.ts
admin/client/ts/services/collectionconfigservice.ts

refactoring product bundles to keep its collection configs to fix pagination and to not show duplicates in search results. Added a removeFilter method to collection config and fixed a bug with joins being forced when not needed in addFilter

Fixing Pagination and Duplicate Search Results in Bundle Search

---

model/process/SubscriptionUsage_Renew.cfc

prevents a locked state where you can't renew

handling case for when a renewal order has been cancelled

---

model/service/OrderService.cfc

when the
```
var = order ...
```
logic wasn't firing Lucee and Railo were still picking up a value for order, but it was a struct of order.orderID, I think the data might have been getting passed into the arguments scope.  Not sure if the error exists on ACF, but this should be fine either way because order is always passed around by reference so no-need to set it into an additional variable.

Fixes issue where order was being defined as struct

---

api/controllers/public.cfc

This fixes chained actions not working on the frontend when using the directives. This uses a hibachiScope flushOrmSession so that actions that depend on the persisted data from a prior action can work.

fixes chained actions being called from the frontend.

---

model/service/OrderService.cfc

content access and delete them all. This is tested working on my local by creating a content access product. Ordering it. checking that accountContentAccess exist in the DB. Then returning it and verifying that they were all deleted.
I also checked that there were no other references to the getter getAccountContentAccess, and all other versions use the smartlist.

change the check for account content access to account for multiple

---

org/Hibachi/HibachiReport.cfc

prevents errors for titleless reports
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4417)

adding null checking to getexportfilename in hibachireport

---

meta/tests/unit/service/HibachiUtilityServiceTest.cfc
org/Hibachi/HibachiUtilityService.cfc

6 test cases added on HibachiUtilityServiceTest.cfc to test one function in HibacheUtilityService: replaceStringTemplate (//replace single brackets ${}) Two bugs:
1:  (Not fixed) Structure with no keys. The IF-ELSEIF-ELSEIF doesn't cover all circumstances
2: (Fixed) Endless loop of arguments.template
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4441)

Hotfix yy replacestringtemplatetest

---

model/dao/OrderDAO.cfc

to remove AS keyword and make oracle safe.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4462)

[IN_PROGRESS]Updates OrderDAO

---

model/process/Order_AddOrderItem.cfc
org/Hibachi/HibachiTags/HibachiPropertyDisplay.cfm
org/Hibachi/HibachiUtilityService.cfc

Bug happens in SKU related Price format.
* HibachiUtilityService: insert FormatValueType "decimal" and add formatValue_decimal() function;
* HibachiPropertyDisplay: Change the "currency" type to "decimal" to go into calculation without $ sign;
* Order_AddOrderItem "price" property: Add formatType as "currency" in Order_AddOrderItem "price" property.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4479)

HibachiUtilityService: add 'decimal' formatValue type and create the

---

admin/layouts/default.cfm

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4491)

bug fix for ckeditor wysiwyg js needing to be loaded for modals

---

public/controllers/ajax.cfc

This was refactored to use getHibachiScope but doesn't have access to hibachi without.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4489)

added extends hibachi to ajax controller

---

model/service/OrderService.cfc

To recreate, build a product bundle that has sku a and sku b. Add that product bundle to an order. Now try to add more of just sku a or just sku b. What happens is that it
increases the quantity of the matching child order item instead of just
adding a new sku. The price for the bundle then goes way out of whack.
This fixes that. This was implemented on buddies and it fixed the pricing issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4493)

fixes an issue with order service.

---

model/entity/Product.cfc

The previous code didn't consider the circumstances: If startDateTime
existed but endDateTime is null; and vice versa.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4536)

Add separate validation of purchaseStartDateTime and purchaseEndDateTime

---

model/entity/Product.cfc

Fix the bug: will return undefined if BRAND entity does not have BRANDNAME property
So right now, the function will return empty string in two conditions: 
* No brand entity
* Has brand entity but no brandName
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4549)

Fix the bug: will return undefined if no BRANDNAME in BRAND entity

---

meta/tests/unit/core/EntityFormatTest.cfc
model/entity/AccountPhoneNumber.cfc

If a property that is persistent and not cfc-related, the type of data should be 'ormtype', not 'type'
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4666)

Add a function to check the 'type' used in persisted and non-cfc property

---

public/controllers/ajax.cfc

At some point the public ajax controller stopped working because of
changes to how ajax response are handled.  Just needed to add this line
so that Hibachi knows to render json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4677)

Fixes issue with legacy public ajax controller

---

model/service/ShippingService.cfc

This adds some checks to make sure that the shipping method options that are being added are allowed to be added. Previously, it was adding both manual and worldwide shipping methods to the fulfillment that it should not have been. Also, I updated the condition that decides when a new shipping method rate should be selected by default. Before, it would auto select if one and only one was available. I changed it to auto select the first one if at least one is available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4698)

Update Shipping Service

---

model/entity/Collection.cfc

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4848)

Prevent exclusion of NULLs when filtering using <>, !=, NOT IN or NOT LIKE

---

integrationServices/mura/model/handler/MuraEventHandler.cfc

This just prevents a hard error on every request if the logged in mura account doesn't exist in Slatwall
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4846)

Fix to prevent hard error in mura

---

org/Hibachi/Hibachi.cfc

adding this to core pull request before I forget about it. Previously, we insisted you have a JWT token even if using secret api keys. This allows the use of those keys independent of the JWT token.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4883)

Develop jwt override for api token

---

model/entity/WorkflowTrigger.cfc
org/Hibachi/client/src/core/services/hibachiservicedecorator.ts
org/Hibachi/client/src/form/components/swinput.ts
org/Hibachi/client/src/workflow/components/swworkflowtriggers.ts

didn't need data. bug fix when workflow has no object. binding search
name on edit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4897)

pull bindings was heavy handed and pulling unneccarily for bindings that

---

model/entity/SubscriptionUsage.cfc

updateSubscriptionUsage can't work for updating the account payment
method without this set to public. The controller method is already
making sure that the account on the subscription usage matches the
account making the change, so this should be ok. This should fix the
same functionality in the sample app as well. I will need this merged for the latest Inc update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4899)

I'm adding this because the public account controller method

---

model/entity/Sku.cfc

a sku bundle. We're already ignoring sku bundles from the conflict
search but just needed to make sure we weren't running that check from
the sku bundle side
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4960)

Modified the getEventConflictExistsFlag to only check if the skus is not

---

model/transient/ResponseBean.cfc

Response bean init method's weren't returning the object.  This was incorrectly removed in the following commit: https://github.com/ten24/slatwall/commit/b64e23404d654fdb03fe3060d42b4db25afeefa5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4985)

Incorrectly removed 'return this;'

---

integrationServices/paypalexpress/Payment.cfc
integrationServices/paypalexpress/controllers/main.cfc

The copyFromType below is required for paypalexpress to be able to create an order payment once it returns. I'm adding it to core because it was lost when a custom project updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4997)

updates paypalexpress to a working state.

---

org/Hibachi/HibachiAssets/js/global.js

This solves and issue we were having when a user recovers a forgot password with an email that is not recognized.  The fix now shows the error message when the user comes back to the screen
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5050)

Admin Login: Show forgot password when fails to recover

---

org/Hibachi/client/src/frontend/components/shippingcostestimator.html
org/Hibachi/client/src/frontend/components/swshippingcostestimator.ts
org/Hibachi/client/src/frontend/frontend.module.ts

This is a simple directive that lets frontend user pass in a skucode and or address and get back data for shipping costs. The template is blank as we will define it on a site by site basis. Usage is:
<sw-estimated-shipping-costs skuCode="someSku">
<span ng-bind="SwEstimatedShippingCostsController.estimatedShippingCosts">
</sw...>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5080)

Develop shipping cost estimator directive

---

admin/client/src/product/controllers/preprocessproduct_create.ts
org/Hibachi/client/src/core/components/listingdisplay.html
org/Hibachi/client/src/core/components/swlistingdisplay.ts
org/Hibachi/client/src/core/services/listingservice.ts

This also includes a refactor to the way that Listing Display / Service work with the selection service. It previously keyed off of the listing display's name, but that was before tableID was created. Now it will use tableID, and for older listing displays it will copy name and use it as tableID
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5096)

Fixing Product Create With Options Selected 

---

model/entity/Collection.cfc
org/Hibachi/HibachiCollectionService.cfc

This makes it so the case in the url for these pagination filters doesn't matter and so it doesn't throw an error on using p:current.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5114)

fix casing issue and remove function call thats not needed.

---

model/service/OrderService.cfc

Calling "public:cart.removeOrderItem" with an orderItemID that doesn't exist in cart throws an error - "variable [orderItem] doesn't exist".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4880)

Fix nonexistent order item removal

---

admin/views/entity/preprocessorderfulfillment_fulfillitems.cfm
model/service/OrderService.cfc

condition. Updates the view to show the default and fix hard error by
the name being wrong.
Problem:
1. This fixes a hard error in the view on fulfilling the items on a pickup order. This fixes that by updating the name of the property to be location.locationID. I also added a condition to check if it a pickup type before displaying the select.
2. This fixes a problem in saveOrderFulfillment that updates the fulfillment items to use the new fulfillment location if one exists and the stock can be found by sku and location. Because that logic was inside a condition that only runs when the order is not placed, the logic was not being called on placed order. I moved the logic outside that condition to fix the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" …

moves the auto update fulfillment items location on save to outside the

---

admin/views/entity/preprocessproduct_addsubscriptionsku.cfm

not being set when creating a subscription sku.
Issue: When creating a new sku under a subscription product, the modal allows the user to set a term, benefit, price, and renewalPrice. The renewalPrice was never being set if you enter it in the field because the field was posting using product.renewalPrice instead of renewalPrice.
Solution: I updated the name of the field. I tested that the value now gets set when creating the sku.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5209)

removes 'product' from the post data to fix issue with the renewalPrice

---

org/Hibachi/client/src/form/components/swinput.ts

This updates the generated template string in swInput to add some space between attributes. There were two issues I was having with this code, this only fixes one of them. The first issue was that the inputAttributes when they get attached touch the previous attributes. The other issue was that because placeholder is already being used with rbKey by default, you can't add you own placeholder to the input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5235)

Fixes spacing issues in swinput.

---

model/dao/SkuDAO.cfc

Ensure that optionGroup sortOrder is used to sequence groups and options for skuDefinition
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5294)

Ensure option group sort order is used in skuDefinition

---

model/entity/PromotionReward.cfc

Percent rewards were being currency converted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5248)

Fix - percent rewards for currency

---

meta/tests/unit/process/Order_AddOrderItemTest.cfc
model/process/Order_AddOrderItem.cfc

There is an issue when adding orderItems in separate requests where the sku is being added as two different items instead of increasing the quantity of the first. This is because of quantity based pricing and this pull request fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5272)

Updates Order_AddOrderItem

---

model/service/EmailService.cfc

I noticed a hard error on place order that I have never experienced before today while in a custom project. It was an error because one of the 'template' argument values being used was not defined. I added a null replace to then all so the value at least gets send to the method without a hard error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5316)

Added null replaced so never errors on missing arguments.

---

model/entity/AccountPhoneNumber.cfc
model/entity/Inventory.cfc

Found two remoteIDS were added in a custom project that needed to be added in core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5325)

Added two remoteIDs

---

model/entity/OrderItem.cfc

Skips checking inventory QATS for return items
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5361)

Max qty for return items

---

custom/assets/.gitignore

Under the original way that this worked, the .gitignore itself was ignored from repos if you just did a copy & paste of Slatwall instead of clone.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5358)

Fixes custom assets .gitignore

---

model/entity/Order.cfc

Was unable to recreate the issue with orders not closing, but per Ryan's recommendation I added val() to the function in order to ensure getTotal returns a numeric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5367)

Added val() to order getTotal

---

model/service/OrderService.cfc

This was causing an issue when return orders weren't created from an original order - eg: an exchange from a customer who bought through a reseller.  The filter line on the accountContentAccessSmartList was throwing an error, so the return was receivable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5370)

Isnull check for referencedOrderItem

---

org/Hibachi/HibachiObject.cfc
org/Hibachi/HibachiScope.cfc
org/Hibachi/HibachiUtilityService.cfc

This fix relates to an issue here: https://ten24.teamwork.com/#/tasks/11757721?c=5875888 and the specific fix was outlines by Ryan in the comments. I tested that this is working in a custom project and that viewing audits no longer throws an error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5387)

Fixes a type issue that makes it so order audits can not be viewed.

---

org/Hibachi/HibachiTags/HibachiActionCallerDropdown.cfm
org/Hibachi/HibachiTags/HibachiListingDisplay.cfm

@rmarchandTen24 This will fix the problem with our navbar dropdowns.
We have bootstrap.js and jquery in Slatwall, we don't need to wait for the Angular bootstrap to get it to work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5422)

Top nav don't need angular bootstrap to start working

---

org/Hibachi/client/src/listing/components/swlistingdisplay.ts

It was noted in this task: https://ten24.teamwork.com/#tasks/12254664 that the listing display icon buttons on workflow were not functioning. I found it was because the exampleEntity was never being defined.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5423)

Fixes the buttons not working on the listing display.

---

org/Hibachi/HibachiUtilityService.cfc

There was an issue in a project where the urlTitle was appending a -2 to the end of the property value (name-2, name-2-2, name-2-2-2) instead of just increasing the unique index name-2, name-3, name-4. This update is to resolve that. To fix it, if the value being appended to already has that value at the end, it replaces it instead of just appending.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5501)

Updates how the generate unique column works.

---

admin/views/entity/promotionrewardtabs/currencies.cfm

and that amount and amountOff types get read as currency amounts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5500)

added conditional logic so that percentageOff types read as percents,

---

org/Hibachi/client/src/core/core.module.ts

this removes, are used by the datetime picker. With this turned on, the
timepicker can not work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5537)

Removes this SEO friendly addition because the html decorations that

---

model/service/WorkflowService.cfc

id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5539)

bug fix for workflow where first struct key was assumed to be an object

---

model/validation/OrderItem.json

A client had a time sensitive issue where they needed to min order quantity to work. Currently, minOrderQuantity is not validated against. If you set the minOrderQuantity to 6 for example, you may still add 1-5 to your cart without any message indicating that you have gone below the minimum. I added the following validation to fix the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5545)

Adds a check for the minimum order quantity in the validation.

---

org/Hibachi/client/src/collection/components/sweditfilteritem.ts

Removes a call to toString that is causing you to not save filters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5549)

Updates SwEditFilterItem

---

model/entity/Collection.cfc

hibachiCollectionService. Either this needs to be in develop, or we need to remove the call to this from hibachiCollectionService (export collection function). I have tested the export is working again for collections that have a baseObject in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5551)

Added mergeCollectionFilter into develop as its being used already by

---

model/entity/OrderFulfillment.cfc

bundle items. Currently, it is adding the weight of all items in the
bundle individually + the weight of the bundle. So for a ball product
that weight 17 pounds, sold as a bundle, the fulfillment weight is 34.
17 for the bundle, 17 for the sku. This makes sure it only looks at the
top level for the weight (the top level already includes the child
weights).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5495)

This is a fix for weight doubling when calculating total weight for

---

admin/client/src/orderitem/components/orderitems.html
admin/client/src/orderitem/components/sworderitems.ts

Duplicates can be caused by adding a one-to-many to the display properties ( in
this case it returns the same order item multiple times - once for each
option). I believe that this is expected as that's what the collection returns. Adding the unique filter, removes the duplicates in this case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5605)

Updates the orderitems listing to only display unique orderitems.

---

model/dao/ProductDAO.cfc

There was a mistake in the update query that updates all the productTypeNamePaths when the product type name is updated. Was throwing a hard error because it needed a string (list) but was getting an array and some bad query syntax. I tested this is working in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5698)

Fixed bug in product dao

---

org/Hibachi/HibachiDataService.cfc

Every Reload & Update DBData was getting added to insertedData.txt.cfm, even if already exists, this will fix it and
keeping the data in memory to reduce file read/save
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5700)

Fix DBData!

---

org/Hibachi/client/src/form/components/swform.ts

From lightspeed task @ https://ten24.teamwork.com/index.cfm#tasks/14462686
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5704)

Allows swForm to parse object errors on init

---

org/Hibachi/client/src/form/components/swinput.ts

This fixes the input not working on lucee because the value is not returned as a string so the trim fails.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5714)

Swinput Hotfix

---

model/service/ShippingService.cfc

I tested this as a fix to a custom project.
All of the calls to isShippingMethodRateUsable fail because that method has 5 arguments, but only three are passed in now since this refactor: 
https://github.com/ten24/slatwall/commit/fd9500fe7fbaf43b691a8f2be752fbe23d25bbe6
The only issue this causes is that the methodRate and shipToAddress get passed in correctly, but, the shipment weight will always be either undefined if pricegroups are undefined or will be pricegroups instead of integer which causes its own problems. Also, because args were required, and those are no longer passed in, failed because of that as well.
function isShippingMethodRateUsable(
required any shippingMethodRate, 
required any shipToAddress, 
required any shipmentWeight, 
required any shipmentItemPrice, 
required any …

Hotfix ih shippingservice fix

---

org/Hibachi/client/src/core/services/hibachiservice.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5737)

fixing property identifier getting lost when looking up property display options

---

org/Hibachi/Hibachi.cfc

Fixed issue with slatwall-mura plugin throwing error because no 'action' in request.
Slatwall-mura plugin will throw error from eventHandler.onApplicationLoad when trying to use MuraEventHandler to setup request. 
Occurs during the plugin installation process and also with subsequent calls with `?appreload=true&update=true` will throw same error.

Fixed error in Mura admin due to 

---

admin/views/entity/listform.cfm

Adds a hidden formID to the form listing. Because the listing display is set to only return the specific columns specified by the listing columns, the id does not get returned. Adding a hidden id field allows the id to get returned and fixes the edit and view buttons not having an id.

adds a hidden id field

---

admin/views/entity/vendorordertabs/vendororderitems.cfm
config/resourceBundles/en.properties
model/entity/VendorOrder.cfc
model/service/VendorOrderService.cfc

Allows vendor orders to be populated with items that do not have an existing vendor/product relationship assigned. Any item added without that relationship will automatically create a vendor/product relationship when the vendor order is received. Keeps a vendor/product preference history.

Improvements to vendor order entry process and UI

---

admin/views/entity/preprocessorder_addorderitem.cfm
tags/SlatwallLocationTypeahead.cfm

Had to revert some old slatwall changes (ten24/slatwall@0640a41#diff-339a8a8a2f77b2b647e26f5d89abdde0) to make collection filters work.

Property in location typeahead that allows user to ignore parent locations

---

model/service/PromotionService.cfc

Save is passed by reference so no need to return and it throws an error because promotion period is already defined in variables scope.

Updates Promo service

---

model/process/OrderDelivery_Create.cfc

We should not be using the capturable amount when the flag is set to false. This returns 0 in that case.

Fix bug in create

---

model/service/OrderService.cfc

The issue doesn't persist, but the response for that request contains duplicate Order Item Gift Recipients. This fixes that.
Shouldn't be an issue as if you haven't already set the order item on the orderItemGiftRecipient you will fail validation in hibachiService's process() method.

Fix order item gift recipient getting set twice

---

model/service/EncryptionService.cfc

Found by Sumit: The init method is recreating the legacy key file.
The new encyption key logic checks if that file exists, if it does, it copies the contents into the new encryption file as a legacy key. And the new encryption key file grows larger and larger.

remove the logic creating the key on init

---

model/service/VendorOrderService.cfc

Fixed issue with detailvendororder displaying duplicate vendor orders if vendor order items partially received.

Fixed issue with detailvendororder displaying duplicate vendor orders

---

admin/views/entity/detailorder.cfm

passing in the orderitems to the comments tab slows the page load on order detail because it must load all orders items and related data.

fix for some of the performance issues on order detail

---

admin/client/src/fulfillmentbatch/components/fulfillmentbatchdetail.html
admin/client/src/orderfulfillment/components/orderfulfillmentlist.html
admin/views/entity/preprocessorderfulfillment_fulfillitems.cfm
org/Hibachi/client/src/listing/components/listingdisplay.html
org/Hibachi/client/src/listing/components/swlistingdisplay.ts

A number of small changes based on core changes in custom project.
Adds functionality to the listing display so we can define the detail action as a different entity and id.
There is an example of how I'm using it in the fulfillment batch detail. Instead of redirecting to a batch or item, it redirects to the fulfillment using the fulfillmentID.
I updates the tabs so it doesn't show the attribute tabs when no attributes are defined.
I changed the positions of qty and qty ordered.
I fixed a path for pickup location in orderfulfillment view.
Removed the stock location filter on the orderfulfillments listing.

Develop team ih core orderfulfillmentpickuplocation

---

integrationServices/authorizenet/Payment.cfc

Special chars need to be removed before the deserialization happens otherwise an error is thrown in lucee.

Updates the payment cfc to remove special chars

---

admin/views/entity/listproduct.cfm
admin/views/entity/listproducttype.cfm

Product type was the only listing that needed personal collections enabled in slatwall core.

added personal collections to listings

---

org/Hibachi/HibachiEntity.cfc

This is needed for a bug where stackTraces are inaccurate if the error occurs during this process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6414)

Updated how we are displaying errors in the postLoad

---

model/service/WorkflowService.cfc

Workflow emails were not going out because the casing of events will not always match when using arrayFind instead of arrayFindNoCase. In my example, cancelorder was not firing because it was cased as cancelorder instead of cancelOrder.

Updates WorkflowService

---

model/service/AccountService.cfc

Just doesn't feel right letting runTransaction have all the fun
Fixes issue allowing the creation of active account payment methods from failed token generation calls

Add all errors from payment transaction when creating account payment method

---

org/Hibachi/HibachiTransient.cfc

Previously the file upload functionality looked only at form.[propertyName] to use for uploading. But if a file upload property existed as a nested populated subproperty, the file upload functionality can't handle that scenario. The form scope key it looks for does not exist. It needs some sense of context in order to properly map to the proper key in the form scope. Te changes allow more flexibility in handling file uploads.
For example
Item.cfc has a property Project.cfc which has multiple file uploads associated with it like ProjectFile.cfc (with property name="theFileUpload" ... hb_fileUpload="true"). Now populate will successfully upload those files because it will reference form.project.projectFiles[1].theFileUpload instead of assuming it exists as form.theFileUpload
Before creating …

file upload enhancement

---

model/entity/Collection.cfc

This is to prevent the "string cannot be converted to a number" error when trying to filter in collections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6486)

Added logic to force Aggregates to use STR func

---

admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts

Because this was not appending the /Slatwall, it was redirecting to homepage of a custom site.

redirect correctly

---

org/Hibachi/HibachiControllerEntity.cfc

Fixed issue with fw1 integration subsystem not having a properly named default action for redirecting the entity save failure

fixed HibachiControllerEntity issue

---

model/entity/Integration.cfc

when codebase doesn't have an integration installed but is registered in database. Due to integrationService listIntegration entities do postLoad check for record level permissions and access a setting which indirectly causes integration entity to attempt to instantiate integrationCFC before knowing whether its actually installed.

Prevents hard error during integration reload 

---

org/Hibachi/Hibachi.cfc
org/Hibachi/HibachiObject.cfc
org/Hibachi/HibachiProfiler.cfc
org/Hibachi/HibachiScope.cfc
org/Hibachi/HibachiTransient.cfc
org/Hibachi/HibachiUtilityService.cfc

I've added super easy and handy functionality to assist us in trying to find bottlenecks and prevent during development. And perhaps something we could incorporate in unit tests for processing time assertions
There's no overhead or effort required.
Every Hibachi component has access to 
addCheckpoint(blockName="Default", description="", tags="a,list,of,tags", object=entity|any)
And the rest shows up logging after some magic!

Added hibachi profiler component and methods

---

model/service/OrderService.cfc

Fixes an issue where taxes don't calculate for return items on a sales order because the order was paid for previous to the return item being added. The current check only recalculates if the payment due is great than 0, but in the case where you are adding a return sku on  paid order, the payment amount due will be -negative. Updating the check to recalculate whenever the payment is not zero, fixes because if the custom is owed or the customer owes, taxes are applied. But when its balanced (0), it does not recalculate.

Update order amounts with taxes

---

org/Hibachi/Hibachi.cfc

Updated Hibachi.cfc to verifyApplicationSetup to not call getBeanFactory().load() but instead directly on newly instantiated beanFactory object.

Fix to prevent SlatwallCMS invoking beanFactory twice

---

admin/views/entity/settingstabs/globaladvanced.cfm
config/resourceBundles/en.properties
model/entity/EntityQueue.cfc
model/entity/OrderItem.cfc
model/entity/WorkflowTrigger.cfc
model/service/SettingService.cfc
model/service/WorkflowService.cfc
org/Hibachi/Hibachi.cfc
org/Hibachi/HibachiDAO.cfc
org/Hibachi/HibachiEntity.cfc
org/Hibachi/HibachiEntityQueueDAO.cfc
org/Hibachi/HibachiEntityQueueService.cfc
org/Hibachi/HibachiScope.cfc
org/Hibachi/HibachiService.cfc
org/Hibachi/client/src/workflow/components/workflowtriggers.html

Please review and run locally to test to verify Workflows functionality works as expected. 
I assume a workflow must manually be configured first to process queue if the global setting 'globalEntityQueueDataProcessCount' = 0 otherwise nothing is going to execute for the entity queue processing.
Some of the merging conflicts with the WorkflowService.cfc and HibachiEntityQueueDAO.cfc were a bit less straightforward.
But this should be everything.

entity queue and calculated properties performance
