ten24/slatwall

- org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5094)
> optimizing attribute model cache

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
- org/Hibachi/HibachiUtilityService.cfc
Adding tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5098)
> adding changes to make applydata work with querystring and structure.

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5102)
> adding tests for removefilter

- org/Hibachi/client/src/form/components/swformfield.ts
- org/Hibachi/client/src/form/components/swinput.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5108)
> fixing save schedule

- org/Hibachi/client/src/form/components/addressform.html
- org/Hibachi/client/src/form/components/swaddressform.ts
- org/Hibachi/client/src/form/form.module.ts
this is the address directive that was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5106)
> address directive

- model/service/UpdateService.cfc
better messaging in the log message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5104)
> update service make a better log message.

- org/Hibachi/client/src/form/components/swinput.ts
adds null checks to fix errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5107)
> input null checks to fix errors

- model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5110)
> fix for null cc bcc

- org/Hibachi/client/src/core/services/publicservice.ts
updates the year to 15 instead of 5 for expiration dates on cards.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5105)
> Develop ih client updates

- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5111)
> resolving linux lucee directory bug

- model/entity/Category.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5113)
> Hotfix rm parentchild categories

- model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5118)
> fix in mail attribute

- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5119)
> added some logging

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiTransient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5121)
> fixes to applyData

- admin/client/src/sku/components/addskupricemodallauncher.html
- admin/client/src/sku/components/swaddskupricemodallauncher.ts
- admin/client/src/sku/components/swskupricequantityedit.ts
- config/resourceBundles/en.properties
- org/Hibachi/client/src/core/components/listingcontrols.html
- org/Hibachi/client/src/core/components/listingdisplay.html
- org/Hibachi/client/src/core/components/swlistingcontrols.ts
- org/Hibachi/client/src/core/components/swlistingdisplay.ts
- org/Hibachi/client/src/core/services/listingservice.ts
Also fix for search which seems to have come out
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5115)
> Sku Prices Not getting loaded into the listing display, display options showing columns that are not user controllable

- model/dao/AccountDAO.cfc
- model/service/AccountService.cfc
project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4956)
> fix a constraint issue on deleting some account addresses for a custom

- public/views/templates/partials/checkout/fulfillmentlocation.html
- public/views/templates/partials/checkout/shoppingcart.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5116)
> Develop ih partials update

- org/Hibachi/HibachiCollectionService.cfc
Reviewed this with Ryan.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5117)
> auth property list

- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiControllerREST.cfc
Adding filters being applied from url even when using the api.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5126)
> Develop filters with api

- model/entity/SubscriptionUsage.cfc
- model/service/ProductService.cfc
- model/service/SubscriptionService.cfc
This fixes the issue where the renewal price (and renewal sku price) was never being used on a renewal order.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/4951)
> Hotfix ih subscription usage amount bug

- model/entity/HibachiEntity.cfc
- public/controllers/ajax.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5130)
> fixing ajax get country

- admin/client/src/slatwall/slatwalladmin.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5134)
> adding preprecossaccount_addaccountparyment back in

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5144)
> Hotfix rm customproperties server scope

- model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5145)
> Develop rm parsingbug

- model/entity/Account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5147)
> superuser can delete regardless of owner

- meta/tests/Application.cfc
- meta/tests/mxunit/Application.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5149)
> Added mxunit mappings

- admin/layouts/default.cfm
- admin/views/entity/detaileventtrigger.cfm
- admin/views/entity/eventtriggertabs/basic.cfm
- admin/views/entity/listeventtrigger.cfm
- config/resourceBundles/en.properties
- model/entity/EmailTemplate.cfc
- model/entity/EventTrigger.cfc
- model/service/EventTriggerService.cfc
- model/service/WorkflowService.cfc
- model/validation/EventTrigger.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5151)
> Develop rm workfloweventtriggers

- config/dbdata/SlatwallUpdateScript.xml.cfm
- model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5152)
> bug fix for script order and var scoping

- org/Hibachi/client/src/form/components/swinput.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5154)
> fixing improper variable

- model/service/IntegrationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5159)
> Fix bean path on windows

- model/validation/LocationConfiguration.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5127)
> configuration capacity type validation

- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
also compatibilty with loading account collection collection configs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5129)
> adding dirty read considerations to collection config services 

- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5161)
> utility functions for putting files into s3

- admin/client/src/sku/components/pricingmanager.html
- admin/client/src/sku/components/skucodeedit.html
- admin/client/src/sku/components/swskucodeedit.ts
- admin/client/src/sku/services/skupriceservice.ts
- admin/client/src/sku/sku.module.ts
- org/Hibachi/HibachiControllerREST.cfc
- org/Hibachi/client/src/core/services/hibachiservice.ts
- org/Hibachi/client/src/core/services/listingservice.ts
- org/Hibachi/client/src/validation/components/swvalidationunique.ts
- org/Hibachi/client/src/validation/components/swvalidationuniqueornull.ts
- org/Hibachi/client/src/validation/services/validationservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5164)
> making sku code editable inline in pricing manager

- admin/views/entity/preprocessorderfulfillment_fulfillitems.cfm
- model/service/OrderService.cfc
If the fulfillment has a pickup location set, then it adds the stock for the orderItem based on that pickup location. Also, if the user changes the fulfillment, updates the stock location on the orderitems on that fulfillment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5165)
> Develop ih fulfillment pickup

- admin/views/entity/accountpaymenttabs/paymenttransactions.cfm
- config/resourceBundles/en.properties
Fix for issue #5139 - Adds payment transaction details to account payment detail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5140)
> Fix for issue #5139

- Application.cfc
- model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5170)
> save scripts status after integration beans

- org/Hibachi/Hibachi.cfc
This is the auth-token code that allows the access key and secret to work again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5171)
> Testing API Code

- meta/tests/unit/entity/ImageTest.cfc
- meta/tests/unit/entity/SkuTest.cfc
- meta/tests/unit/service/ImageServiceTest.cfc
- model/service/ImageService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5172)
> Added getResizedImagePath tests for ImageService and image/sku entities

- model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5175)
> allowing for hb_populateEnabled="public" as custom property metadata

- admin/views/entity/locationtabs/locationaddresses.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5176)
> Add email Address and Email to location address detail

- org/Hibachi/client/src/core/services/hibachipathbuilder.ts
- org/Hibachi/client/src/core/services/hibachiservice.ts
- org/Hibachi/client/src/frontend/frontend.module.ts
Updates the name of the subsystem to api subsystem. 
adds a property for the integration action path that allows you to set the action in the header to be used throughout the slatwallcms project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5177)
> Develop ih fe file update

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5178)
> fixing currentpage declartion

- org/Hibachi/client/src/core/components/swcollectionconfig.ts
- org/Hibachi/client/src/core/components/swcollectionfilter.ts
- org/Hibachi/client/src/core/components/swcollectionorderby.ts
- org/Hibachi/client/src/core/components/swtypeaheadinputfield.ts
- org/Hibachi/client/src/core/core.module.ts
- org/Hibachi/client/src/core/services/observerservice.ts
- org/Hibachi/client/src/form/services/fileservice.ts
config
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5185)
> adding typeahad updates for filtering and order by in the sw collection

- org/Hibachi/client/src/core/components/swtypeaheadinputfield.ts
- org/Hibachi/client/src/core/components/typeaheadinputfield.html
- org/Hibachi/client/src/core/components/typeaheadsearch.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5184)
> adding support for passing required into the typeahead input field

- org/Hibachi/HibachiEntity.cfc
> bug fix for encrypting attribtue values only if they have a changed

- admin/client/src/product/controllers/preprocessproduct_create.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5195)
> don't try to get product types without one selected

- admin/client/src/content/components/swsiteselector.ts
- admin/client/src/sku/components/swaddskupricemodallauncher.ts
- admin/client/src/sku/components/swimagedetailmodallauncher.ts
- org/Hibachi/client/src/basebootstrap.ts
- org/Hibachi/client/src/collection/controllers/entity_createcollection.ts
- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
- org/Hibachi/client/src/core/components/swdraggable.ts
- org/Hibachi/client/src/core/components/swlistingcontrols.ts
- org/Hibachi/client/src/core/components/swlistingdisplay.ts
- org/Hibachi/client/src/core/components/sworderbycontrols.ts
- org/Hibachi/client/src/core/model/transient/basetransient.ts
- org/Hibachi/client/src/core/services/cacheservice.ts
- org/Hibachi/client/src/core/services/draggableservice.ts
- org/Hibachi/client/src/core/services/hibachiservice.ts
- org/Hibachi/client/src/core/services/utilityservice.ts
- org/Hibachi/client/src/form/components/swaddressform.ts
- org/Hibachi/client/src/validation/components/swvalidationemail.spec.ts
- org/Hibachi/client/src/validation/services/validationservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5198)
> Develop rm productjsbug

- admin/views/entity/preprocessorderdelivery_create.cfm
- meta/tests/unit/entity/OrderTest.cfc
- meta/tests/unit/service/OrderServiceTest.cfc
- model/entity/Order.cfc
- model/process/OrderDelivery_Create.cfc
- model/service/ShippingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5203)
> Hotfix rm termpaymentbug

- model/process/Order_AddOrderPayment.cfc
- model/transient/HibachiScope.cfc
- org/Hibachi/client/src/core/model/entity/cart.ts
- org/Hibachi/client/src/core/model/entity/entities.ts
- org/Hibachi/client/src/core/model/entity/orderitem.ts
- org/Hibachi/client/src/core/model/transient/basetransient.ts
- org/Hibachi/client/src/core/services/hibachiservicedecorator.ts
- org/Hibachi/client/src/core/services/orderservice.ts
- org/Hibachi/client/src/core/services/publicservice.ts
- org/Hibachi/client/src/form/components/swaddressform.ts
- org/Hibachi/client/src/form/form.module.ts
This pull request, Ryan, we can review on Monday with the other client pull request I am doing. This is mostly the changes you had done in develop that I ported into hotfix so they can be used in custom project. I've tested these in one custom project on hotfix and they are working. I also backported the address form directive because I need it in that project and that project is not yet on develop. If you don't like the idea of backporting the directive we can talk alternatives at the meeting on Monday.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5197)
> Hotfix ih client updates backport for custom

- integrationServices/mura/config/setup/cfapplication.cfm
- integrationServices/slatwallcms/BaseApplication.cfc
- meta/sample/Application.cfc
- meta/tests/Application.cfc
- meta/tests/mxunit/Application.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5205)
> Removing integrationServices from cfclocation

- admin/client/src/slatwall/slatwalladmin.module.ts
- circle.yml
- org/Hibachi/client/src/core/services/publicservice.ts
- org/Hibachi/client/src/form/components/swformsubscriber.ts
- org/Hibachi/client/src/form/components/swinput.ts
- org/Hibachi/client/webpack-production.config.js
- org/Hibachi/client/webpack.config.js
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5211)
> Develop rm failonbadcompile

- admin/client/src/slatwall/slatwalladmin.module.ts
- circle.yml
- org/Hibachi/client/src/basebootstrap.ts
- org/Hibachi/client/src/form/components/swformsubscriber.ts
- org/Hibachi/client/src/form/components/swinput.ts
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5212)
> backporting changes to prevent errors from webpack 2 release

- meta/tests/unit/core/FileSystemTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5216)
> Hotfix rm ensurepropertyfilecasingonviews

- model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5217)
> making sure emails are property scoped

- integrationServices/endicia/model/SyncUtility.cfc
- integrationServices/gigya/Authentication.cfc
- integrationServices/gigya/model/handler/GigyaHandler.cfc
- integrationServices/mura/com/BundleUtility.cfc
- model/dao/CommentDAO.cfc
- model/dao/SettingDAO.cfc
- org/Hibachi/HibachiDAO.cfc
- org/Hibachi/HibachiReport.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5219)
> local scoping cfloop variables

- model/entity/OrderFulfillment.cfc
Issue: While creating the array of shipping method options to return, it is adding multiple of the same option.
Fix: I fixed this by adding a method that checks for that option in an option array, and then used that method three places.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5201)
> Hotfix ih dupe shipping rates

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5221)
> Fix between filter in collections

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5220)
> Service case fix to prevent errors on linux

- model/entity/Location.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5190)
> Update the breadcrumb to decoded html, because we don't allow HTML anymore on SimpleRepresentation

- integrationServices/stripe/Payment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5227)
> missing var scope

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5224)
> collection between filter fix & unit tests

- model/entity/WorkflowTrigger.cfc
- model/service/WorkflowService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5240)
> workflow can display exceptions in error mode

- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5241)
> using collectionoptions

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5244)
> making sure the logical operator gets added on to the filter when needed

- org/Hibachi/HibachiDataService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5233)
> More Robust CSV to Query Support

- org/Hibachi/HibachiAssets/js/global.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5234)
> making sure date and timepicker functions are present to avoid null errors

- org/Hibachi/client/src/core/services/hibachiservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5230)
> getting getLastEntityName in property identifier to support aliases with multiple joins

- model/service/OrderService.cfc
This will update the calls to getStockByLocatioAndSku to use a non-missing method that always returns a stock of the name getStockBySkuAndLocation. This fixes a couple issues in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5231)
> Develop pickup location updates

- meta/tests/unit/service/CollectionServiceTest.cfc
- model/entity/Collection.cfc
- model/service/HibachiService.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/client/src/collection/controllers/collections.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5246)
> Hotfix rm exportcollectionsbug

- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5232)
> Upload to s3 returns boolean success

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5253)
> bgu fix for attributes

- config/resourceBundles/en.properties
- model/entity/EntityQueue.cfc
- org/Hibachi/HibachiEntityQueueService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5249)
> Store process method and run from QUEUE Entity

- admin/views/entity/detaillocationaddress.cfm
Displays the phone on the location address create form.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5252)
> adds a field to the form

- org/Hibachi/client/src/core/services/hibachiservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5258)
> fixing getResizeImage

- admin/views/entity/categorytabs/childcategories.cfm
- org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5263)
> fixing the child category tab

- model/entity/Collection.cfc
- org/Hibachi/HibachiSmartList.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5261)
> removing reference to session

- meta/tests/unit/service/ContentServiceTest.cfc
- model/dao/ContentDAO.cfc
- model/service/ContentService.cfc
- model/validation/Category.json
validation to prevent deletion of parent categories
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5264)
> code to allow deleting of categories and removing associations.

- meta/tests/unit/service/ContentServiceTest.cfc
- model/dao/ContentDAO.cfc
- model/validation/Category.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5265)
> Hotfix rm categorydelete

- model/entity/Collection.cfc
- org/Hibachi/HibachiSmartList.cfc
Reverts ten24/slatwall#5261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5266)
> Revert "removing reference to session"

- model/validation/Vendor.json
- model/validation/VendorEmailAddress.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5271)
> account number required and emailaddress isn't for vendors

- model/service/WorkflowService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5277)
> Syntax Error!

- model/service/WorkflowService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5269)
> put the var in the scope workflowservice

- meta/tests/unit/dao/InventoryDAOTest.cfc
- model/dao/InventoryDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5281)
> Hotfix rm qnrovo

- model/dao/InventoryDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5284)
> null assignments

- meta/tests/unit/client/specrunner.cfc
- model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5286)
> fix var scope bugs

- config/resourceBundles/en.properties
- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
- model/entity/WorkflowTrigger.cfc
- model/service/WorkflowService.cfc
- org/Hibachi/client/src/workflow/components/workflowtriggers.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5276)
> Workflow Collection Fetch Size (Batches)

- admin/client/src/sku/components/addskupricemodallauncher.html
- admin/client/src/sku/components/pricingmanager.html
- admin/client/src/sku/components/swaddskupricemodallauncher.ts
- admin/client/src/slatwall/components/swcurrencyformatter.ts
- config/resourceBundles/en.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5280)
> Pricing Manager Misc Improvements to Add Sku Price Process

- model/dao/InventoryDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5289)
> bug fix for QOH not returning for null locaitonIDPath

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5291)
> updating ipaddress

- meta/tests/unit/dao/SkuDAOTest.cfc
- model/dao/SkuDAO.cfc
- model/entity/Collection.cfc
back porting collections order by alias work from hotfix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5297)
> converting skuDao method to use collections.

- admin/views/entity/detailpromotionreward.cfm
- admin/views/entity/promotionrewardtabs/eligiblePriceGroups.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5181)
> Adds missing UI for eligible price groups on promo rewards

- model/validation/OrderFulfillment.json
with rate override on fulfillment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5247)
> problem with placing order in admin

- admin/client/src/product/controllers/preprocessproduct_create.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5300)
> bug fix for optiongroups

- integrationServices/avatax/Integration.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5303)
> Updated casing

- model/service/UpdateService.cfc
- org/Hibachi/HibachiEntityParser.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5295)
> Fix custom properties

- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5302)
> making sure the join gets processed for filters and adding display properties

- admin/views/entity/orderitemtabs/basic.cfm
minor, but helpful
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5309)
> Adding currency to order item detail view

- meta/tests/unit/service/AccountServiceTest.cfc
- model/service/PaymentService.cfc
transaction successflag
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5310)
> when we don't have an integration involved. We still need to set the

- admin/client/src/orderitem/components/sworderitems.ts
pagination works on the orderitem table in order detail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5306)
> Sets the current page in the get collection request so that the

- model/entity/OrderFulfillment.cfc
- model/service/OrderService.cfc
This is the refactor I worked through with Ryan so I could override how the sort works in a custom project while maintaining update safety.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5290)
> moves fulfillment method into a service.

- model/service/OrderService.cfc
subscription with a term that has auto pay set to yes without a saved
method. I needed to abstract out this check so I can override it in a
custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5238)
> Abstracts a call out to check if the user is try to pay for a

- model/entity/Product.cfc
This updates makes it so you can get images via width and height explicitly instead of just using the predefined sizes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5243)
> Updates a method to give extra functionality.

- admin/views/entity/subscriptionusagetabs/basic.cfm
- config/resourceBundles/en.properties
- model/entity/SubscriptionUsage.cfc
- model/service/SubscriptionService.cfc
This makes a clear pull request from another related branch.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5315)
> Hotfix renewal subscription charge 2

- model/entity/Collection.cfc
- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5319)
> when using backend addDisplayProperty add nonpersistent checks

- model/entity/Product.cfc
Reverts ten24/slatwall#5243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5321)
> Revert "Updates a method to give extra functionality."

- tags/SlatwallAdminAddressDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5326)
> add horizontal form to address modal

- model/service/ShippingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5278)
> only adding the rate to be processed if it needs to be split at a different weight

- integrationServices/usps/Integration.cfc
- integrationServices/usps/IntlRatesV2RequestTemplate.cfm
- integrationServices/usps/config/resourceBundles/en.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5279)
> adding ability to specify package size and girth through settings in usps

- admin/views/entity/locationtabs/locationaddresses.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5327)
> Remove title twice and fix spacing on location

- integrationServices/elavon/Payment.cfc
Sumit found this in TW and not in core. Pushing to core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5322)
> Elevon Update from TW.

- model/entity/Order.cfc
This is an issue I found while doing a custom project update.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5323)
> Updates order.cfc to use val instead of len.

- meta/tests/unit/service/HibachiValidationServiceTest.cfc
- org/Hibachi/HibachiValidationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5329)
> adding passthrough if unique and uniqueornull are false

- meta/tests/unit/service/OrderServiceTest.cfc
- model/validation/Order_AddOrderItem.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5336)
> Hotfix rm validationonreturnorder

- admin/views/entity/orderfulfillmenttabs/basic.cfm
- model/entity/OrderFulfillment.cfc
- model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5337)
> adding account address to orderfulfillment

- model/entity/Sku.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5330)
> Updated skuDefinition to use skuName if no options are in use

- model/entity/Collection.cfc
- org/Hibachi/client/src/core/services/hibachiservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5339)
> bug fix for populating nonpersistent collections

- model/service/SkuService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5342)
> set image when a new option is added

- meta/tests/unit/service/CollectionServiceTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5344)
> adding test to confirm entity permissions

- admin/views/entity/collectiontabs/basic.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5345)
> prevent editing of base collection when it is set

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5346)
> add display options to collection on base collection

- admin/views/entity/locationtabs/locationaddresses.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5348)
> Hotfix rm locationaddressredirectbug

- model/service/LocationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5349)
> migrate stock when making child location

- model/dao/LocationDAO.cfc
- model/entity/Location.cfc
- model/entity/Stock.cfc
- model/service/LocationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5352)
> revised location validation for performance

- org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5353)
> bug fix for mura path to api

- org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5354)
> use urlStirng instead for mura

- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5355)
> adding helper for decrypt property

- admin/views/entity/promotionperiodtabs/basic.cfm
- admin/views/entity/promotiontabs/promotionperiods.cfm
- config/resourceBundles/en.properties
- model/entity/PromotionPeriod.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5341)
> Adding Promotion Period Name to Promotion Period

- admin/views/entity/preprocessorder_include/addorderpayment.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5359)
> fixing case

- model/entity/DatabaseCache.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5364)
> adding createdDatetime and modified

- admin/views/entity/settingstabs/globaladvanced.cfm
- config/resourceBundles/en.properties
- model/entity/Collection.cfc
- model/service/SettingService.cfc
- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5335)
> API Settings for Dirty Read (Read Uncommitted) and Max Page Show

- org/Hibachi/client/src/entity/components/list.html
- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
- org/Hibachi/client/src/listing/services/listingservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5373)
> forking the logic that makes multislot behave differently

- model/entity/OrderItem.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5379)
> adding val to get item total

- org/Hibachi/FW1/framework.cfc
Ref: https://github.com/framework-one/fw1/blob/develop/framework/one.cfc#L1289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5376)
> SetLayout Updates from FW/1

- model/service/ShippingService.cfc
Not 100% sure, but suspect this was causing a bit of an issue on lucee 4.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5362)
> adding arguments scope

- meta/tests/unit/service/AccountServiceTest.cfc
- model/entity/AccountPaymentMethod.cfc
account payment
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5380)
> removing cascade on so orderpayments don't get deleted wehn deleting an

- admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts
- model/process/AccountEmailAddress_Verify.cfc
- model/process/OrderItem_AddOrderItemGiftRecipient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5384)
> Develop team pick pack ship rm client

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
modified
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5385)
> able to reinflate collectionconfigstruct if persisted property is

- org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5390)
> Collection Export with Base Collection

- org/Hibachi/client/src/core/filters/datefilter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5388)
> swapping date parse for new date to get around issues with unparsable formats from elasticsearch

- model/service/FileService.cfc
- tags/SlatwallAdminFilesDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5371)
> Develop ck delete file

- meta/tests/unit/service/OrderServiceTest.cfc
- model/entity/OrderItem.cfc
- model/service/InventoryService.cfc
- model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5392)
> validate ordritem on placeorder

- model/service/ProductService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5393)
> Fixed typo

- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5394)
> Added a hasService check to the condtional

- meta/tests/unit/service/OrderServiceTest.cfc
- model/dao/InventoryDAO.cfc
- model/service/OrderService.cfc
- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5396)
> ensureing inventory calculations are accurate

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
- org/Hibachi/HibachiTransient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5401)
> Develop rm collectionsrefactor

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5403)
> optimizing BETWEEN filter. making getJoins reusable

- admin/views/entity/preprocessorder_addorderitem.cfm
- admin/views/entity/stockadjustmenttabs/basic.cfm
- admin/views/entity/vendorordertabs/basic.cfm
- tags/SlatwallLocationTypeahead.cfm
This adds a tag to wrap a location typeahead so it can be used in a number of places. This comes from this task: https://ten24.teamwork.com/#/tasks/12065131?c=5873715
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5407)
> Develop ih location typeahead tag

- config/resourceBundles/en.properties
- model/dao/HibachiCacheDAO.cfc
- model/dao/SettingDAO.cfc
- model/entity/ServerInstance.cfc
- model/service/SettingService.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiCacheService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5408)
> Develop rm clientsecretsave

- model/service/TaxService.cfc
regular orderItems. This relates to this task https://ten24.teamwork.com/#tasks/12195443.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5406)
> Updates the tax service to calculate tax for returnItem as well as

- config/resourceBundles/en.properties
- model/entity/Sku.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5409)
> added vendororderitem to sku

- admin/layouts/default.cfm
- admin/views/print/default.cfm
- model/entity/Print.cfc
- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5410)
> updating print queue to be loadbalancable

- model/entity/VendorOrderItem.cfc
- model/service/VendorOrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5419)
> Added SKu relationship to vendorOrderItem

- model/entity/Collection.cfc
- org/Hibachi/client/src/collection/components/swcolumnitem.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5420)
> 	Fixes aggregate orderbys and AVERAGE aggregate filter

- org/Hibachi/HibachiDataService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5414)
> giving validate csv function flexibility to override whether the passed path is expanded or not

- org/Hibachi/DI1/ioc.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5416)
> rethrowing bean not found errors

- org/Hibachi/HibachiAssets/js/global.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5417)
> checking to make sure functions from external libraries exist in global js so that it can be compatible with hibachi front end

- org/Hibachi/HibachiDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5413)
> getting boolean values to start importing as 0, 1 and fixing null case for empty strings

- org/Hibachi/client/src/core/core.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5427)
> removing comment compile in prod

- org/Hibachi/client/src/listing/components/listingsearch.html
- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
- org/Hibachi/client/src/pagination/services/paginationservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5431)
> Develop rm listingupdates

- admin/views/entity/preprocessproduct_include/addeventschedule.cfm
Fix from DCM
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5429)
> Added default event start/end for proper display of recurrence info

- integrationServices/elavon/Integration.cfc
- integrationServices/elavon/Payment.cfc
- integrationServices/elavon/config/resourceBundles/en.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5424)
> add debugmode to elavon

- admin/client/src/product/components/productlistingpages.html
- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
- org/Hibachi/client/src/listing/components/swlistingdisplaycell.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5331)
> Ability to create columns with links in sw-listing-display

- model/service/OrderService.cfc
project. We are commenting it for future use.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5433)
> Comment core as unneeded right now and is causing issues in custom

- org/Hibachi/client/src/collection/controllers/entity_createcollection.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5425)
> Show All Base collections in dropdown

- org/Hibachi/client/src/collection/components/swaddfilterbuttons.ts
- org/Hibachi/client/src/collection/components/swcollection.ts
- org/Hibachi/client/src/collection/components/swcollectiontable.ts
- org/Hibachi/client/src/collection/components/swconditioncriteria.ts
- org/Hibachi/client/src/collection/components/swcriteria.ts
- org/Hibachi/client/src/collection/components/swcriteriaboolean.ts
- org/Hibachi/client/src/collection/components/swcriteriamanytomany.ts
- org/Hibachi/client/src/collection/components/swcriteriamanytoone.ts
- org/Hibachi/client/src/collection/components/swcriterianumber.ts
- org/Hibachi/client/src/collection/components/swcriteriaonetomany.ts
- org/Hibachi/client/src/collection/components/swcriteriastring.ts
- org/Hibachi/client/src/collection/controllers/collections.ts
- org/Hibachi/client/src/core/components/swcolumnsorter.ts
- org/Hibachi/client/src/core/components/swconfirm.ts
- org/Hibachi/client/src/dialog/controllers/pagedialog.ts
- org/Hibachi/client/src/entity/components/swdetailtabs.ts
- org/Hibachi/client/src/entity/components/swlist.ts
- org/Hibachi/client/src/entity/controllers/routercontroller.ts
- org/Hibachi/client/src/form/components/swformfieldsearchselect.ts
- org/Hibachi/client/src/form/components/swformregistrar.ts
- org/Hibachi/client/src/form/components/swinput.ts
- org/Hibachi/client/src/workflow/components/swadmincreatesuperuser.ts
- org/Hibachi/client/src/workflow/components/swworkflowbasic.ts
- org/Hibachi/client/src/workflow/components/swworkflowcondition.ts
- org/Hibachi/client/src/workflow/components/swworkflowconditiongroupitem.ts
- org/Hibachi/client/src/workflow/components/swworkflowtask.ts
- org/Hibachi/client/src/workflow/components/swworkflowtaskactions.ts
- org/Hibachi/client/src/workflow/components/swworkflowtriggerhistory.ts
- org/Hibachi/client/src/workflow/components/swworkflowtriggers.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5432)
> Removing dependency not in use from Angular Directives

- model/entity/WorkflowTrigger.cfc
wrapping nonpersistent getter in a structkeyexists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5438)
> Fixes error on workflow trigger

- org/Hibachi/client/src/core/components/swtypeaheadsearch.ts
- org/Hibachi/client/src/core/components/typeaheadsearch.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5439)
> driving dropdown by angular

- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
- org/Hibachi/client/src/pagination/services/paginationservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5440)
> messaging back to pagination service

- org/Hibachi/readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5441)
> updating hibachicore

- org/Hibachi/HibachiDataDAO.cfc
- org/Hibachi/HibachiEntityParser.cfc
- org/Hibachi/HibachiEventHandler.cfc
- org/Hibachi/HibachiJsonService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5445)
> Develop rm slatwallmapping

- admin/views/entity/ordertabs/basic.cfm
- config/resourceBundles/en.properties
- model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5444)
> Generate Quote Number for Order

- org/Hibachi/client/src/collection/components/swcriteriadate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5446)
> Prevent wrong date format loading in range filter

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
Added the ability to use gregorian dates in a collection range. Added a test that verifies that its working. Previously, we only used epoch dates in our ranges. This allows dates in the format mm/dd/yyyy-mm/dd/yyyy (or in the case of range through the api mm/dd/yyyy^mm/dd/yyyy). This was needed for a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5447)
> Develop ih date range

- org/Hibachi/client/src/core/services/hibachiinterceptor.ts
- org/Hibachi/client/src/core/services/hibachiservice.ts
- org/Hibachi/client/src/core/services/hibachiservicedecorator.ts
- org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5453)
> hibachji abstraction

- org/Hibachi/client/src/collection/controllers/collections.ts
- org/Hibachi/client/src/collection/controllers/createcollection.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5454)
> converting pagination to messageing

- org/Hibachi/client/src/core/services/baseentityservice.ts
- org/Hibachi/client/src/core/services/hibachiinterceptor.ts
- org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5458)
> fixes for missing objects

- admin/client/src/orderitem/components/sworderitem.ts
- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5449)
> Api:main.post delete response fix

- model/validation/VendorOrder_AddVendorOrderItem.json
bad cost. This is related to an issue in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5450)
> Adds validation to the Cost field so that it doesn't throw unexpected on

- org/Hibachi/HibachiEventHandler.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5459)
> Fixing path

- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5460)
> fix for listing page refactor

- model/service/UpdateService.cfc
- org/Hibachi/HibachiEntityParser.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5461)
> fixing file getting wiped when merging custom properties

- model/entity/AttributeValue.cfc
- model/service/AccountService.cfc
- model/service/AttributeService.cfc
Added copyAttributeValue to AttributeService
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5463)
> Replace duplicates with property copy

- org/Hibachi/client/src/core/services/baseentityservice.ts
- org/Hibachi/client/src/core/services/hibachiservicedecorator.ts
- org/Hibachi/client/src/core/services/publicservice.ts
- org/Hibachi/client/src/hibachi/hibachi.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5465)
> fixes to for hibachi

- admin/views/entity/contenttabs/settings.cfm
- admin/views/entity/settingstabs/content.cfm
- config/resourceBundles/en.properties
- integrationServices/slatwallcms/BaseApplication.cfc
- model/service/SettingService.cfc
- org/Hibachi/HibachiTags/HibachiCache.cfm
- org/Hibachi/HibachiTags/HibachiCacheExclude.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5468)
> adding hibachicache tags

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5464)
> Remove any bad Joins from HQL

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5480)
> fixes to collection fetch size

- model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5481)
> prevent deletion of rewrite rules

- admin/views/entity/collectiontabs/basic.cfm
- config/resourceBundles/en.properties
- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5483)
> Collection cleanup & aggregations

- config/resourceBundles/en.properties
- model/entity/EntityQueue.cfc
- model/service/HibachiEntityQueueService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5485)
> EntityQueue process with History

- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5487)
> getDefaultCollectionProperties accepting related properties

- admin/views/entity/vendorordertabs/vendororderitems.cfm
- model/process/VendorOrder_AddVendorOrderItem.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5491)
> bug fix for when a bill location doesn't exist

- admin/views/entity/stockadjustmenttabs/stockadjustmentitems.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5493)
> calculating QATS via pagination

- org/Hibachi/client/src/listing/services/listingservice.ts
fix an issue where the listing display is not displaying cell data. I've had this issue during a couple of different project fixes recently so I throw in this fix for it. It not directly related to any task.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5490)
> Adds a fix for the pageRecordValueByColumn method in listing service to

- api/controllers/public.cfc
- model/entity/App.cfc
- model/entity/Content.cfc
- model/entity/HibachiEntity.cfc
- model/process/Account_ForgotPassword.cfc
- org/Hibachi/HibachiEntityQueueDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5494)
> Develop rm genericfixes

- meta/tests/unit/service/jwtServiceTest.cfc
- org/Hibachi/HibachiJWT.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5502)
> Validate Account ID in JWT Token

- org/Hibachi/HibachiTags/HibachiCache.cfm
These cfcache tags don't like the self closing symbol '/' on them on CF10. Locally in a custom project, I was getting a hard error and unable to load the project until these were modified as in this pull request.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5503)
> Develop ih cache fix

- tags/SlatwallCollectionPagination.cfm
non-persistent collections. This tag just takes the collections, and
displays the standard next, previous, first, last links with 5 pages in
between. The tag is made to be configurable and you can pass in the
text/rbkey text to use for those buttons or they use a default. This is going to be used in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5504)
> I added this cfTag to help frontend devs add pagination to

- model/dao/HibachiCacheService.cfc
- org/Hibachi/HibachiCacheDAO.cfc
- org/Hibachi/HibachiCacheService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5506)
> bug fix for database cache key dupes

- integrationServices/slatwallcms/BaseApplication.cfc
- integrationServices/slatwallcms/templates/basetemplate.cfm
mappings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5509)
> fixing bug in lucee that doesn't allow cfimport to use application

- meta/tests/unit/entity/CollectionTest.cfc
- meta/tests/unit/entity/HibachiEntityTest.cfc
- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5512)
> GetPropertyOptions & GetPropertyCount using collection & Custom column alias in collections

- admin/views/entity/preprocessproduct_create.cfm
Updates the attributes on this option listing display to get the multiselect checkboxes working again.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5513)
> Develop option listing update

- org/Hibachi/HibachiDataService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5514)
> Increase retry for default data population

- model/service/PublicService.cfc
quantity is checked. This fixes an issue in a custom project and there is a related task for it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5517)
> Adds a check in the updateOrderItemQuantity to make sure the max order

- model/service/LocationService.cfc
Check if the location isNew before updating the stock location to fix issues when there is data at the wrong level.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5518)
> Tiny fix for the updateStockLocation running when it shouldn't.

- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiTagService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5521)
> Allow for setting secure cookie

- admin/views/main/log.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5522)
> support for lucee log.cfm

- org/Hibachi/client/src/collection/components/filtergroups.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5524)
> Check if collection config is available before showing the "No Filters Have Been Created" message

- model/service/HibachiSessionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5527)
> Fixed: Cart not attached to session when token api used for login

- meta/tests/unit/transient/SlatwallScopeTest.cfc
- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5528)
> Added account payments to getAccountData available property list

- tags/SlatwallLocationTypeahead.cfm
booleans and shows instead of ifs. This updates to how this is being used in custom projects so they match.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5520)
> Update to the location typeahead to use explicit value checks on the

- model/dao/HibachiDAO.cfc
- org/Hibachi/HibachiEntity.cfc
- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5529)
> adding helper methods to get table name

- model/dao/AccountDAO.cfc
- model/dao/AttributeDAO.cfc
- model/dao/CommentDAO.cfc
- model/dao/ContentDAO.cfc
- model/dao/CurrencyDAO.cfc
- model/dao/EmailBounceDAO.cfc
- model/dao/GiftCardDAO.cfc
- model/dao/InventoryDAO.cfc
- model/dao/LocationDAO.cfc
- model/dao/OptionDAO.cfc
- model/dao/OrderDAO.cfc
- model/dao/PaymentDAO.cfc
- model/dao/ProductDAO.cfc
- model/dao/ProductTypeDAO.cfc
- model/dao/RoundingRuleDAO.cfc
- model/dao/ScheduleDAO.cfc
- model/dao/SettingDAO.cfc
- model/dao/SiteDao.cfc
- model/dao/SkuDAO.cfc
- model/dao/SkuPriceDAO.cfc
- model/dao/StockDAO.cfc
- model/dao/SubscriptionDAO.cfc
- model/dao/TaskDAO.cfc
- model/dao/TypeDAO.cfc
- model/dao/VendorDAO.cfc
- model/dao/VendorOrderDAO.cfc
- model/dao/WorkflowDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5530)
> Develop rm gettablename

- model/dao/ProductDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5532)
> not an orm entity

- model/dao/HibachiDAO.cfc
- org/Hibachi/HibachiDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5533)
> moving gettablename to hibachi

- model/dao/AccountDAO.cfc
- model/dao/AttributeDAO.cfc
- model/dao/CommentDAO.cfc
- model/dao/ContentDAO.cfc
- model/dao/CurrencyDAO.cfc
- model/dao/EmailBounceDAO.cfc
- model/dao/GiftCardDAO.cfc
- model/dao/InventoryDAO.cfc
- model/dao/LocationDAO.cfc
- model/dao/OptionDAO.cfc
- model/dao/OrderDAO.cfc
- model/dao/PaymentDAO.cfc
- model/dao/ProductDAO.cfc
- model/dao/ProductTypeDAO.cfc
- model/dao/RoundingRuleDAO.cfc
- model/dao/ScheduleDAO.cfc
- model/dao/SettingDAO.cfc
- model/dao/SiteDao.cfc
- model/dao/SkuDAO.cfc
- model/dao/SkuPriceDAO.cfc
- model/dao/StockDAO.cfc
- model/dao/SubscriptionDAO.cfc
- model/dao/TaskDAO.cfc
- model/dao/TypeDAO.cfc
- model/dao/VendorDAO.cfc
- model/dao/VendorOrderDAO.cfc
- model/dao/WorkflowDAO.cfc
Reverts ten24/slatwall#5530
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5534)
> Revert "Develop rm gettablename"

- model/entity/FormResponse.cfc
Fixes an issue with the smartlist by making it a collection. This fixes an issue in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5535)
> Updates the collection that returns the form email value

- model/entity/Collection.cfc
- org/Hibachi/client/src/collection/components/sweditfilteritem.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5538)
> Check is value is not defined and uses displayValue if is a string filter

- model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5546)
> supporting adding an order item via chain actions

- model/service/UpdateService.cfc
prevent override
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5536)
> Added support for mysql, updated the arguments, and added a flag to

- model/service/PrintService.cfc
- model/transient/HibachiScope.cfc
A fix for the print queue. I tested locally and will be pushing this to a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5550)
> Develop ih printqueue fix

- admin/client/src/orderitem/components/sworderitems.ts
Recall to update the orderitems listing when the pagination has changed. This is tested on a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5553)
> Fixes the orderitems pagination.

- org/Hibachi/HibachiCollectionService.cfc
@rmarchandTen24 I kept this fix simple, let me know if this is good enough
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5552)
> merge collection headers and export

- model/entity/Order.cfc
Adds tax to the deposit calculation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5555)
> Saving the tax update

- admin/controllers/ajax.cfc
This was found in a custom project and fixed like this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5557)
> Develop ih listing display

- admin/views/entity/detailorder.cfm
Fixes the casing issue in core.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5558)
> casing on order tabs.

- org/Hibachi/client/src/collection/components/swcriteriadate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5556)
> Add time to date range loader

- org/Hibachi/client/src/collection/components/swconditioncriteria.ts
- org/Hibachi/client/src/collection/components/swcriteriadate.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5543)
> Always use timestamp to prevent filter problems

- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5563)
> making sure apply data gets called for rest request

- config/configORM.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5567)
> set status to 500 when no datasource

- model/entity/Content.cfc
- model/transient/HibachiScope.cfc
- org/Hibachi/HibachiTags/HibachiCache.cfm
specific to an entitytypetemplate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5574)
> updating hibachicache to make cachekeys unique for content that is

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5580)
> making $.hibachi available and fixing casing for HibachiEntityParser

- org/Hibachi/HibachiTags/HibachiSetting.cfm
- org/Hibachi/HibachiTags/HibachiSettingTable.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5582)
> adding hibachi tags for setting and setting table functionality not specific to slatwall

- model/transient/HibachiScope.cfc
- org/Hibachi/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5579)
> adding content to core hibachi scope

- org/Hibachi/HibachiSessionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5578)
> safeguarding hibachi session service against non-existent settings

- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5583)
> Fix Collection merge

- org/Hibachi/client/src/core/services/hibachiservice.ts
This adds a type guard to the hibachi service to return a new entity if the service does not have a new function for that entity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5587)
> Updates hibachiService

- model/service/UpdateService.cfc
- org/Hibachi/HibachiDAO.cfc
- org/Hibachi/HibachiDataService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5588)
> performance updates to update service

- org/Hibachi/HibachiDataService.cfc
adding an already threaded fallback
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5589)
> adding an already threaded fallback

- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5595)
> Support to file name with spaces and commas

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
rather than between
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5602)
> changing split to listToArray. updating tests to look for greater than

- tags/SlatwallLocationTypeahead.cfm
sets the lineitem as searchable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5598)
> Updates the typeahead to add a maxRecords attribute. also explicitly

- meta/tests/unit/entity/AccountTest.cfc
- model/dao/AccountDAO.cfc
- model/entity/Account.cfc
- model/validation/Account.json
- org/Hibachi/HibachiSmartList.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5604)
> Develop rm hibachiabstractions

- model/entity/PaymentTransaction.cfc
for a permission group. This was needed for a custom project where the sales managers need access to this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5607)
> Updates payment transaction to be included when selecting permissions

- admin/views/entity/permissionrecordrestrictiontabs/restrictionconfig.cfm
- config/resourceBundles/en.properties
- meta/tests/unit/entity/PermissionRecordRestrictionTest.cfc
- meta/tests/unit/service/HibachiAuthenticationServiceTest.cfc
- model/entity/PermissionRecordRestriction.cfc
- model/validation/PermissionRecordRestriction.json
- org/Hibachi/client/src/collection/collection.module.ts
- org/Hibachi/client/src/collection/components/restrictionconfig.html
- org/Hibachi/client/src/collection/components/swcollectiontable.ts
- org/Hibachi/client/src/collection/components/sweditfilteritem.ts
- org/Hibachi/client/src/collection/components/swfiltergroups.ts
- org/Hibachi/client/src/collection/components/swrestrictionconfig.ts
- org/Hibachi/client/src/collection/controllers/collections.ts
- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
- org/Hibachi/client/src/core/services/hibachiservicedecorator.ts
- org/Hibachi/client/src/core/services/hibachivalidationservice.ts
- org/Hibachi/client/src/core/services/observerservice.ts
- org/Hibachi/client/src/listing/components/listingcontrols.html
- org/Hibachi/client/src/listing/components/listingdisplay.html
- org/Hibachi/client/src/listing/components/listingsearch.html
- org/Hibachi/client/src/listing/components/swlistingcontrols.ts
- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5606)
> adding the basics for the ui to work

- model/entity/PermissionRecordRestriction.cfc
- org/Hibachi/client/src/collection/components/restrictionconfig.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5608)
> Develop rm recordlevelpermissions ui

- meta/tests/unit/entity/CollectionTest.cfc
- meta/tests/unit/service/HibachiAuthenticationServiceTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5613)
> Develop rm recordlevelpermissionsfkcolumns

- meta/tests/unit/controller/EntityTest.cfc
- org/Hibachi/HibachiControllerEntity.cfc
- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5615)
> DOR protection

- org/Hibachi/client/src/core/components/swtypeaheadinputfield.ts
- tags/SlatwallLocationTypeahead.cfm
location typeahead to use that list to fix the ordering of the results.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5612)
> Added a attribute to pass in orderByList to typeaheadinputfield. Updates the

- admin/views/entity/preprocessorder_placeorder.cfm
Simple update to display the deposit amount instead of order total if the order has a deposit amount.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5611)
> Displays the deposit amount if available.

- admin/client/src/product/components/productlistingpages.html
- config/resourceBundles/en.properties
- org/Hibachi/client/src/form/components/swformfieldfile.ts
- org/Hibachi/client/src/form/components/swformfieldjson.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5618)
> bug fix for listing pages

- meta/tests/unit/service/SiteServiceTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5620)
> assert application deployment

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5622)
> adding missing semicolon

- meta/tests/unit/SlatwallUnitTestBase.cfc
- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
- org/Hibachi/HibachiTransient.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5625)
> Session Based Filters for collections

- model/process/Order_AddOrderPayment.cfc
- model/service/PaymentService.cfc
- model/transient/payment/EligiblePaymentMethodBean.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5629)
> Fixed add order payment issue

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5638)
> check for request context

- admin/client/src/bundle.js
- admin/client/src/fulfillmentbatch/actions/fulfillmentbatchactions.ts
- admin/client/src/fulfillmentbatch/components/fulfillmentbatchdetail.html
- admin/client/src/fulfillmentbatch/components/swfulfillmentbatchdetail.ts
- admin/client/src/orderfulfillment/components/orderfulfillmentlist.html
- admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts
- admin/client/src/orderfulfillment/orderfulfillmentservice.spec.ts
- admin/client/src/orderfulfillment/services/orderfulfillmentservice.ts
- admin/layouts/default.cfm
- admin/views/entity/detailfulfillmentbatch.cfm
- admin/views/entity/listorderfulfillment.cfm
- org/Hibachi/HibachiControllerREST.cfc
- org/Hibachi/client/src/core/components/swconfirm.ts
- org/Hibachi/client/src/core/services/hibachiservice.ts
This updates the filtering on the fulfillment list page. This adds some tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5627)
> Develop team pick pack ship filters and tests

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5639)
> Develop rm recordlevelpermissions rc metadatajoins

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5641)
> typo in exlclude logic

- meta/tests/unit/transient/SlatwallScopeTest.cfc
- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5643)
> fixing content hql for product smart and collection list

- model/service/SkuService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5645)
> bug fixes to make up and break up

- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5646)
> updating to use encodeForHTML

- model/entity/Order.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5653)
> adding index for orderNumber

- org/Hibachi/client/src/form/components/swaddressform.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5652)
> Added ability to choose custom partial for swaddressform directive

- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5654)
> adding collection fixes and debugging tools

- Application.cfc
- model/service/IntegrationService.cfc
- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5659)
> code to allow skipping db data

- admin/views/error/default.cfm
- integrationServices/authorizenet/Payment.cfc
- integrationServices/merchantesolutions/Payment.cfc
- integrationServices/orbital/xmltemplates/NewOrderRequest.cfm
- integrationServices/sagepay/Payment.cfc
- integrationServices/usaepay/Payment.cfc
- model/entity/Order.cfc
- model/service/HibachiSessionService.cfc
- org/Hibachi/HibachiAuditService.cfc
- org/Hibachi/HibachiObject.cfc
- org/Hibachi/HibachiSessionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5660)
> giveing aws override priveledge over remoteaddress

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5656)
> Fix Record Count with non persistent properties collection

- admin/views/entity/permissionrecordrestrictiontabs/basic.cfm
- admin/views/entity/preprocesspermission_addpermissionrecordrestriction.cfm
- config/resourceBundles/en.properties
- model/entity/PermissionRecordRestriction.cfc
- model/process/Permission_AddPermissionRecordRestriction.cfc
- model/service/AccountService.cfc
- model/service/SettingService.cfc
- org/Hibachi/HibachiEntity.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5667)
> Develop rm recordlevelpermissions r ccachepermgroups

- admin/layouts/default.cfm
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5670)
> Hotfix rm skusbug

- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5672)
> updating entity property count to use collection aggregates

- api/controllers/public.cfc
its own scope
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5677)
> url does not live in arguments.rc for all engines. It is supposed to be

- model/entity/Collection.cfc
- org/Hibachi/HibachiService.cfc
- org/Hibachi/HibachiTags/HibachiFilterCountDisplay.cfm
- org/Hibachi/HibachiTags/HibachiFilterCountDisplayItem.cfm
- tags/SlatwallCollectionPagination.cfm
- tags/tagtemplates/SlatwallCollectionPagination.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5680)
> apply data enhancements

- org/Hibachi/client/src/listing/components/listingsearch.html
- org/Hibachi/client/src/listing/components/swlistingsearch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5682)
> Hotfix rm searchable

- model/entity/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5690)
> bug fix for custom prop files

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5692)
> check if has application value before getting it

- config/dbdata/SlatwallWorkflow.xml.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5691)
> Update False on Active Flag to prevent workflow reactivation on reload/update

- model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5693)
> Added numeric validation to accountTermCreditLimit

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5695)
> able to specify devops config

- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiService.cfc
- org/Hibachi/HibachiTags/HibachiCache.cfm
- org/Hibachi/HibachiTags/HibachiFilterCountDisplayItem.cfm
- org/Hibachi/HibachiTags/tagtemplates/hibachifiltercountdisplayitem.cfm
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5703)
> adding filtercount work

- integrationServices/slatwallcms/BaseApplication.cfc
- integrationServices/slatwallcms/BaseEventHandler.cfc
- integrationServices/slatwallcms/model/handler/SlatwallCMSHandler.cfc
- model/transient/HibachiScope.cfc
- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5705)
> able to load site by sitecode

- integrationServices/slatwallcms/model/handler/SlatwallCMSHandler.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5706)
> bgu fix for path

- config/scripts/database/indexes.cfm
Related to lightspeed task: https://ten24.teamwork.com/#tasks/14350789
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5708)
> Unique ContentProduct restraint on SwProductListingPage

- model/service/PublicService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5697)
> Fixed getAddressOptions function in PublicService so address forms work on front end

- org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5710)
> Updated hasShippingAddress function

- model/entity/Collection.cfc
- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5719)
> updates to filters to support many to many

- meta/tests/unit/entity/CollectionTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5720)
> updating tests to reflect updates

- admin/views/entity/preprocesssku_createbom.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5723)
> missing parens in create bom

- org/Hibachi/HibachiDataService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5722)
> fixing file path error

- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5731)
> make sure to check if property exists

- model/entity/Product.cfc
- model/service/ProductService.cfc
- org/Hibachi/HibachiTags/HibachiFilterCountDisplay.cfm
- org/Hibachi/HibachiTags/HibachiFilterCountDisplayItem.cfm
- org/Hibachi/HibachiTags/tagtemplates/hibachifiltercountdisplayitem.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5732)
> updating filters abstracting producturl

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5733)
> adding a buildUrl delegater to collecitons

- org/Hibachi/client/src/core/services/publicservice.ts
https://ten24.teamwork.com/#/tasks/14644176
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5730)
> Updated billing address form to select edited/created address

- model/entity/Account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5728)
> adding a getOrdersPlacedCollectionList function for account

- org/Hibachi/client/src/core/components/modallauncher.html
- org/Hibachi/client/src/core/components/modalwindow.html
- org/Hibachi/client/src/core/components/swmodallauncher.ts
- org/Hibachi/client/src/core/components/swmodalwindow.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5726)
> modal launcher enhancements for client side

- org/Hibachi/HibachiCollectionService.cfc
Update to fix this ref to reference collection entity.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5740)
> Quick bug fix

- custom/model/process/readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5743)
> Added process folder with readme to Slatwall/custom

- org/Hibachi/HibachiAuditService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5746)
> only audit if the function exists

- meta/tests/unit/entity/ProductTest.cfc
- model/entity/Product.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5748)
> return published and active products by default allow developer to pass in

- tags/tagtemplates/SlatwallCollectionPagination.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5749)
> bug fixes for paginator

- model/entity/Collection.cfc
- org/Hibachi/HibachiTags/HibachiFilterCountDisplayItem.cfm
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5751)
> getting attribute option labels for filters

- admin/views/entity/listbrand.cfm
- admin/views/entity/listfulfillmentbatch.cfm
- admin/views/entity/listproductreview.cfm
- admin/views/entity/listproducttype.cfm
- admin/views/entity/listpromotion.cfm
- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
- org/Hibachi/client/src/listing/services/listingservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5753)
> Develop rm listingbugs

- admin/views/entity/listcategory.cfm
- admin/views/entity/listoptiongroup.cfm
- admin/views/entity/listpricegroup.cfm
- admin/views/entity/listpromotion.cfm
- admin/views/entity/listsubscriptionbenefit.cfm
- admin/views/entity/listsubscriptionterm.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5754)
> bug fixes for listing display

- admin/views/entity/listorder.cfm
- admin/views/entity/listorderitem.cfm
- admin/views/entity/listorderpayment.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5755)
> listing bug fixes

- model/service/UpdateService.cfc
- org/Hibachi/HibachiEntityParser.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5757)
> Develop rm parserfix

- org/Hibachi/HibachiDataService.cfc
- org/Hibachi/HibachiUtilityService.cfc
data service to handle running on lucee. These fixes were needed to get
the data service running in a custom project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5759)
> Updates to add some new utilities and to fix some issues in the hibachi

- admin/views/entity/listbrand.cfm
- admin/views/entity/listcategory.cfm
- admin/views/entity/listeventregistration.cfm
- admin/views/entity/listfulfillmentbatch.cfm
- admin/views/entity/listoptiongroup.cfm
- admin/views/entity/listorder.cfm
- admin/views/entity/listorderdelivery.cfm
- admin/views/entity/listorderitem.cfm
- admin/views/entity/listorderpayment.cfm
- admin/views/entity/listpricegroup.cfm
- admin/views/entity/listproduct.cfm
- admin/views/entity/listproductreview.cfm
- admin/views/entity/listproducttype.cfm
- admin/views/entity/listpromotion.cfm
- admin/views/entity/listsku.cfm
- admin/views/entity/listsubscriptionbenefit.cfm
- admin/views/entity/listsubscriptionterm.cfm
- admin/views/entity/listvendororder.cfm
- admin/views/entity/listvendororderitem.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5761)
> updates to listings

- admin/views/entity/listcollection.cfm
- admin/views/entity/listproduct.cfm
- org/Hibachi/client/src/collection/components/swcolumnitem.ts
- org/Hibachi/client/src/listing/components/listingcontrols.html
- org/Hibachi/client/src/listing/components/listingdisplay.html
- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
- org/Hibachi/client/src/listing/components/swlistingcontrols.ts
- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
- org/Hibachi/client/src/listing/services/listingservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5762)
> converting from saveCollection to messaging

- config/scripts/database/v3_1.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5765)
> fixing update script

- tags/SlatwallAdminAttributeSetDisplay.cfm
path from customProperty if that exists
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5764)
> Updated the AttributeSetDisplay to pull upload

- admin/client/src/orderfulfillment/services/orderfulfillmentservice.spec.ts
- admin/views/entity/detailcollection.cfm
- admin/views/entity/listproduct.cfm
- model/entity/Collection.cfc
- org/Hibachi/client/src/collection/components/swcolumnitem.ts
- org/Hibachi/client/src/collection/components/swdisplayitem.ts
- org/Hibachi/client/src/collection/components/swdisplayoptions.ts
- org/Hibachi/client/src/collection/components/sweditfilteritem.ts
- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
- org/Hibachi/client/src/listing/components/listingdisplay.html
- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
- org/Hibachi/client/src/listing/components/swlistingcontrols.ts
- org/Hibachi/client/src/listing/components/swlistingsearch.ts
- org/Hibachi/client/src/listing/services/listingservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5771)
> Develop rm fluxit

- admin/views/entity/attributetabs/relatedobjectcollection.cfm
- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/client/src/collection/components/swcolumnitem.ts
- org/Hibachi/client/src/collection/components/swdisplayitem.ts
- org/Hibachi/client/src/collection/components/swdisplayoptions.ts
- org/Hibachi/client/src/collection/components/sweditfilteritem.ts
- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
- org/Hibachi/client/src/listing/components/listingcontrols.html
- org/Hibachi/client/src/listing/components/listingdisplay.html
- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
- org/Hibachi/client/src/listing/components/swlistingcontrols.ts
- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
- org/Hibachi/client/src/listing/components/swlistingsearch.ts
- org/Hibachi/client/src/listing/services/listingservice.ts
objects via listing display in attributes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5772)
> fixing bugs in swlisting dipslay and making it so you can save related

- org/Hibachi/client/src/collection/components/swcolumnitem.ts
- org/Hibachi/client/src/collection/components/swdisplayoptions.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5774)
> annotaion bug fix

- model/service/PublicService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5775)
> fixing public service

- org/Hibachi/client/src/core/components/swexpiringsessionnotifier.ts
- org/Hibachi/client/src/core/core.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5721)
> expiring session notification for core

- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5776)
> Updated routEntity to be routeEntity

- org/Hibachi/HibachiAssets/js/global.js
decoded by browser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5778)
> Fixes error when double quotes are added to htmlencoded JSON text

- admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5781)
> minify bug fix for pcik pack

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5786)
> fixing fitlergroups bug

- admin/views/entity/detailcategory.cfm
- model/entity/AttributeSet.cfc
- model/entity/AttributeValue.cfc
- model/entity/Category.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5783)
> Add Custom Attributes to Category

- model/entity/Integration.cfc
- model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5770)
> bug fix for getting setting options

- model/service/PublicService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5777)
> Add order placement errors from cart to response

- model/service/PublicService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5779)
> AddShippingAddressUsingAccountAddress fix (hotfix)

- integrationServices/slatwallcms/skeletonsite/templates/partials/checkout/addbillingbyaccountaddresspartial.html
- integrationServices/slatwallcms/skeletonsite/templates/partials/checkout/billingaccountaddresspartial.html
- org/Hibachi/client/src/core/services/publicservice.ts
- public/views/templates/partials/checkout/addbillingbyaccountaddresspartial.html
- public/views/templates/partials/checkout/billingaccountaddresspartial.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5785)
> Front end account address messaging changes

- tags/SlatwallAdminAddressDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5788)
> Updated conditionals on admin address display

- admin/views/entity/accounttabs/accountpayments.cfm
- admin/views/entity/accounttabs/cartsandquotes.cfm
- admin/views/entity/accounttabs/orders.cfm
- admin/views/entity/detailaccount.cfm
- model/entity/Account.cfc
- model/entity/Collection.cfc
- org/Hibachi/HibachiControllerEntity.cfc
- org/Hibachi/HibachiTags/HibachiEntityDetailGroup.cfm
- org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5793)
> adding tag to use collectionlist via backend

- org/Hibachi/client/src/collection/components/swcolumnitem.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5794)
> bug fix for column sorting

- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5795)
> default columsn to searchable

- model/entity/Content.cfc
same name as property and resulting in bad data
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5800)
> Fixed issue with local variables not being scoped locally as they share

- model/entity/Content.cfc
- model/entity/Setting.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5804)
> adding performance indexes

- admin/views/entity/skutabs/options.cfm
- model/entity/Product.cfc
able to edit option groups if now orders related
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5805)
> able to add option groups if you have more than one sku

- model/entity/Content.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5808)
> removing index til we have a migration script

- admin/views/entity/skutabs/options.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5809)
> updating option groups

- org/Hibachi/HibachiSmartList.cfc
Fix issues #5806 #5747
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5814)
> Revert savedState to use session instead of databaseCache

- org/Hibachi/HibachiTags/HibachiEntityDetailGroup.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5816)
> if wysiwyg then don't use ng-if

- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiObject.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5817)
> custom props fix for clearing lucee cache

- admin/controllers/entity.cfc
- admin/views/entity/listorder.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5820)
> filter orders and carts and quotes

- org/Hibachi/client/src/core/filters/datefilter.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5821)
> if date is blank string then just render a blank

- org/Hibachi/client/src/listing/components/listingcontrols.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5822)
> showing filters in simple mode

- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5825)
> fixing casing on urlTitle

- admin/client/src/sku/components/imagedetailmodallauncher.html
- admin/client/src/sku/components/skucodeedit.html
- admin/client/src/sku/components/skupriceedit.html
- admin/client/src/sku/components/skupricequantityedit.html
- admin/client/src/sku/components/skustockadjustmentmodallauncher.html
- admin/client/src/sku/components/swskucodeedit.ts
- admin/client/src/sku/components/swskustockadjustmentmodallauncher.ts
- model/entity/Stock.cfc
- org/Hibachi/client/src/core/components/typeaheadsearch.html
- public/views/templates/partials/login.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5826)
> Hotfix rm pricingmanagerbugfix

- admin/views/entity/attributeoptiontabs/basic.cfm
- integrationServices/slatwallcms/BaseApplication.cfc
- model/entity/AttributeOption.cfc
- org/Hibachi/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5827)
> able to get attribute option by urltitle

- org/Hibachi/client/src/core/components/swtypeaheadsearch.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5824)
> allowing for typeahead results to be links

- org/Hibachi/HibachiTags/HibachiFilterCountDisplayItem.cfm
- org/Hibachi/HibachiTags/tagtemplates/hibachifiltercountdisplayitem.cfm
filters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5841)
> able to configure whether to show the custom "x to y" apply range

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5843)
> fix for missing app key

- config/scripts/database/v5_1.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5844)
> max order number as a number

- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiCacheDAO.cfc
- org/Hibachi/HibachiCacheService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5848)
> adding serverinstance updates for when a record is created

- meta/tests/unit/service/HibachiAuthenticationServiceTest.cfc
- model/entity/Collection.cfc
- model/service/AccountService.cfc
- org/Hibachi/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5854)
> Develop rm permissiongroupcaching

- org/Hibachi/HibachiTags/HibachiEntityDetailGroup.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5859)
> ng-if only angular content

- admin/views/entity/producttabs/skusettings.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5810)
> Added setting to the product detail page

- admin/views/entity/attributetabs/basic.cfm
- model/entity/Attribute.cfc
- model/service/ContentService.cfc
- org/Hibachi/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5870)
> able to get app templates and attribute option source enhancements

- model/service/AppService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5878)
> when updating cms there is no need to rebuild tags and templates

- admin/controllers/ajax.cfc
- assets/js/admin.js
- model/dao/SkuDAO.cfc
- model/entity/Sku.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5880)
> able to get averagecost by location

- org/Hibachi/HibachiCacheService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5884)
> bug fix for serverinstance

- admin/client/src/fulfillmentbatch/components/fulfillmentbatchdetail.html
- admin/client/src/fulfillmentbatch/components/swfulfillmentbatchdetail.ts
- admin/client/src/orderfulfillment/components/orderfulfillmentlist.html
- admin/client/src/orderfulfillment/services/orderfulfillmentservice.ts
- admin/views/entity/detailfulfillmentbatch.cfm
Fulfillments updates to square away pickpakc and make the custom project update safe.
> Develop ih fulfillments updates

- model/entity/LedgerAccount.cfc
- model/service/InventoryService.cfc
- model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5891)
> Develop rm accouting

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5918)
> fixing date range to be at the beginning of the day

- model/service/PublicService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5919)
> allow quantities of zero

- custom/client/readme.md
- integrationServices/slatwallcms/skeletonsite/client/readme.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5920)
> Develop rm clientwhere

- admin/client/src/optiongroup/components/addoptiongroup.html
- admin/client/src/optiongroup/components/swaddoptiongroup.ts
- admin/client/src/optiongroup/components/swoptionsforoptiongroup.ts
- admin/views/entity/skutabs/options.cfm
- config/dbdata/SlatwallUpdateScript.xml.cfm
- config/resourceBundles/en.properties
- config/scripts/database/v5_1.020.cfm
- model/entity/Sku.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5933)
> options performance fix

- config/resourceBundles/en.properties
- model/entity/VendorOrder.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/5937)
> adding calculated Properties for totals on vendor Order

- admin/views/entity/stockadjustmenttabs/basic.cfm
Changed the invoked view getter method 'getFromLocation' to the appropriate 'getToLocation'
> Fixed display issue with location transfer stock adjustment

- model/transient/HibachiScope.cfc
> Updated the productCollectionList to filter

- admin/views/entity/preprocessorderdelivery_create.cfm
- admin/views/entity/preprocessorderfulfillment_fulfillitems.cfm
users to select a pickup location instead of also choosing a locaiton.
moved the location selector over to the order delivery create as this
matches the data structure and allows for better validation
> Updated the preprocessOrderFulfillment_Fullitems view to only allow the

- integrationServices/boe/Integration.cfc
- integrationServices/boe/QuotationRequest.cfm
- integrationServices/boe/Tax.cfc
- integrationServices/boe/config/resourceBundles/en.properties
- integrationServices/boe/model/controller/import.cfc
- integrationServices/boe/model/handler/BoeEventHandler.cfc
A new tax integration for grabbing tax rates from Boe (board of equalization in the state of California.)
> added boe tax integration.

- org/Hibachi/client/src/core/services/publicservice.ts
This is ready to go. Related to an issue with NSS checkout.
> Updated place order error handling (front end)

- admin/client/src/fulfillmentbatch/components/fulfillmentbatchdetail.html
- admin/client/src/orderfulfillment/components/orderfulfillmentlist.html
- model/entity/OrderFulfillment.cfc
Addes a property to fulfillment and fulfillment listing.
> adds prop to slatwall and to fulfillment listing.

- admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts
> updates the name to type

- model/service/IntegrationService.cfc
> IntegrationService actionPermissionDetails cache reset

- model/entity/Account.cfc
> Revert "reduce overhead on get Primary"

- admin/views/entity/detailskuprice.cfm
- admin/views/entity/skutabs/currencies.cfm
- model/entity/Sku.cfc
- model/entity/SkuPrice.cfc
Just transposing Miguel's work.
> Develop team ed skuprice.

- model/service/VendorOrderService.cfc
relationship.
Using stock entity vendorOrderItem.stock instead of vendorOrderItem.sku to avoid null reference
> Refactored logic when vendor order received to save vendor product

- admin/client/src/fulfillmentbatch/components/fulfillmentbatchdetail.html
This comments out the payment section for now.
This also adds a link that populates the quantity fields on click.
> Updates the fulfillment batch detail

- config/resourceBundles/en.properties
- model/process/Account_CreatePassword.cfc
- model/validation/Account_CreatePassword.json
> Add validation to prevent dublicate email id when guest user made permanent

- admin/client/src/fulfillmentbatch/components/fulfillmentbatchdetail.html
- admin/client/src/orderfulfillment/components/orderfulfillmentlist.html
- admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts
- admin/views/entity/detailfulfillmentbatch.cfm
- org/Hibachi/client/src/core/services/typeaheadservice.ts
Listing updates that I had made in a custom project that needed to get back into core before an update. Updates to use the latest version of listing display and to fix a couple UI bugs.
> Develop ih pickpack listing

- admin/client/src/orderfulfillment/components/orderfulfillmentlist.html
- admin/views/entity/listfulfillmentbatch.cfm
- integrationServices/fedex/Shipping.cfc
Fulfillment Batch updates made for a custom project.
> Develop ih fulfillments work

- config/resourceBundles/en.properties
- model/entity/VendorOrder.cfc
- model/process/VendorOrder_Receive.cfc
- model/validation/VendorOrder.json
- model/validation/VendorOrder_Receive.json
Added validation to VendorOrder so that status "closed" does not allow "receive". Added validation to make sure received quantities do not exceed orderered quantities and negatively impact inventory numbers.
> VendorOrder validation enhancements for inventory

- model/service/StockService.cfc
Fix missing transferQuantity when creating a transfer item
> Develop kk sku minmax reporting

- meta/tests/unit/entity/CollectionTest.cfc
@rmarchandTen24 
Pls Revieew the PR for new Collecton Test cases
> Add test cases to collectionTest.cfc

- admin/client/src/orderitem/components/sworderitem.ts
reloads the page on deleting an item so the order totals refresh.
> Update orderitem delete button

- admin/client/src/orderitem/components/sworderitems.ts
This fixes the pagination on the order detail for the orderitems listing.
> Updates sworderitems

- admin/views/entity/orderfulfillmenttabs/basic.cfm
- admin/views/entity/preprocessorder_addorderitem.cfm
- admin/views/entity/preprocessorder_placeorder.cfm
- config/resourceBundles/en.properties
- model/process/Order_AddOrderItem.cfc
- model/service/OrderService.cfc
- model/validation/OrderFulfillment.json
- model/validation/Order_AddOrderItem.json
Updated addOrderItem shipping fulfillment to display estimatedShippingDate and also to placeOrder preprocess view. And necessary date validation.
> Estimated shipping date enhancements

- admin/views/entity/detailorder.cfm
- model/service/OrderService.cfc
This adds a simple function to reopen a closed order.
> Develop team reopen a closed order.

- config/resourceBundles/en.properties
- model/process/Order_CreateReturn.cfc
- model/service/OrderService.cfc
- model/validation/Order_CreateReturn.json
greater than the orginal quantity
> Added new validation to Return Orders to make sure that they aren't

- admin/views/entity/listvendor.cfm
Create Vendor will now open a modal.
> create vendor now opens modal

- model/entity/HibachiEntity.cfc
- tags/SlatwallAdminAttributeSetDisplay.cfm
> Related object attributes that are also custom properties will show simpleRepresentation

- integrationServices/fedex/ProcessShipmentRequestTemplate.cfm
- model/transient/fulfillment/ShippingRequestBean.cfc
Updates the Fedex integration to pass the shipping method integration name into the request that populates the tracking number and label.
> Develop team ih shipping

- meta/tests/unit/entity/OrderTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6141)
> fixing unit test

- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiControllerREST.cfc
- org/Hibachi/HibachiService.cfc
- org/Hibachi/HibachiSessionService.cfc
- org/Hibachi/HibachiSmartList.cfc
- org/Hibachi/HibachiTags/HibachiFormField.cfm
- org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
- org/Hibachi/HibachiTransient.cfc
- org/Hibachi/HibachiUtilityService.cfc
- org/Hibachi/client/src/alert/service/alertservice.ts
- org/Hibachi/client/src/basebootstrap.ts
- org/Hibachi/client/src/collection/components/collectiontable.html
- org/Hibachi/client/src/collection/components/swcollectiontable.ts
- org/Hibachi/client/src/collection/components/swdisplayoptions.ts
- org/Hibachi/client/src/collection/services/collectionconfigservice.ts
- org/Hibachi/client/src/core/components/swtypeaheadsearch.ts
- org/Hibachi/client/src/core/components/swtypeaheadsearchlineitem.ts
- org/Hibachi/client/src/core/services/hibachiservice.ts
- org/Hibachi/client/src/core/services/hibachiservicedecorator.ts
- org/Hibachi/client/src/listing/components/listingdisplaycellcurrency.html
- org/Hibachi/client/src/listing/components/swlistingcolumn.ts
- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
- org/Hibachi/client/src/listing/components/swlistingsearch.ts
- org/Hibachi/client/src/listing/services/listingservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6142)
> adding hibachi updates

- admin/views/entity/orderpaymenttabs/basic.cfm
> Added conditional for handling external payment

- admin/views/entity/settingstabs/account.cfm
- config/resourceBundles/en.properties
- model/entity/Account.cfc
- model/entity/Sku.cfc
- model/service/OrderService.cfc
- model/service/SettingService.cfc
- model/service/SkuService.cfc
- org/Hibachi/HibachiEntity.cfc
Also carrying over some updates made to core in recent project.
>  Updated services and entities to guarantee skulocationquantity calculated properties get updated in a timely manner

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
PR  regarding - Collection bug fix - when you have a display aggergate and no order by then exclude order by createDatetime from being added , Task on Teamwork , @rmarchandTen24  please review
> Exclude orderBy createdDateTime in case of hasDisplayAggregate : true and no other orderBy applied

- meta/tests/unit/SlatwallUnitTestBase.cfc
- meta/tests/unit/entity/CollectionTest.cfc
- meta/tests/unit/mockService.cfc
- meta/tests/unit/service/ContentServiceTest.cfc
- meta/tests/unit/service/CurrencyServiceTest.cfc
- model/entity/Collection.cfc
…ntService and CurrencyService
> Handle negative inputs for Pagination and Implement Mocking.

- integrationServices/elavon/Payment.cfc
Elavon randomly does either suffers a connection failure or does not return any response, even in a case where that payment eventually goes through as a valid payment. This pull request is to add a catch all in addition to a check on the connection failure. Additionally, this pull request checks again the string literal value of "0" instead of 0, as 0 will be handled in a more fuzzy way
> Updates elevon

- admin/views/entity/listminmaxsetup.cfm
- admin/views/entity/listminmaxstocktransfer.cfm
- config/resourceBundles/en.properties
noticed min/max needed personal collections enabled as well. Found a couple rbkeys to fix.
> added personal collections to minmax and rbkeys

- org/Hibachi/HibachiAssets/js/global.js
I tested this on my local and working, when selecting no for if new account when creating order, the account property is now available in modal.
> revised global.js to fix account selector when creating order

- admin/client/src/sku/components/swaddskupricemodallauncher.ts
> Work around for quantity based pricing data getting incorrectly set to

- model/service/ShippingService.cfc
AndShippingMethod to get smartlist from the service and not the entity
> Updated getShippingMethodRatesByOrderFulfillment

- integrationServices/mura/config/setup/cfapplication.cfm
- integrationServices/mura/model/handler/Handler.cfc
- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6184)
> Develop rm muraupdates

- integrationServices/fedex/Integration.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6186)
> fixed label name

- admin/views/entity/preprocessproduct_create.cfm
Updates the property name so that the brand saves when the product is created. Tested on a custom project.
> Update preprocess product create

- meta/tests/unit/entity/CollectionTest.cfc
- org/Hibachi/HibachiEntity.cfc
@rmarchandTen24 please review the PR regarding cached and new collection list conditions added in HibachiEntity and test cases to verify it in the collectiontest.cfc
> Add condition and tests for cached and new collection list

- config/resourceBundles/en.properties
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6194)
> Added missing rbkey

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6198)
> clear cache for framework one

- integrationServices/fedex/ProcessShipmentRequestTemplate.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6199)
> Update ProcessShipmentRequestTemplate to include street2Address

- integrationServices/BaseAuthentication.cfc
- integrationServices/BaseIntegration.cfc
- model/entity/HibachiEntity.cfc
- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6203)
> adding first level caching

- org/Hibachi/client/src/collection/components/displayitemaggregate.html
PR wrt to the conversation in PR ( https://github.com/ten24/slatwall/pull/6201 )
> Add condition to filter numeric option for Aggregate if using sum or avg

- model/dao/AccountDAO.cfc
- model/dao/ContentDAO.cfc
- model/dao/PromotionDAO.cfc
- model/dao/SettingDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6205)
> lower case oracle

- admin/client/src/slatwall/filters/swcurrency.ts
- admin/client/src/slatwall/slatwalladmin.module.ts
- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/client/src/basebootstrap.ts
- org/Hibachi/client/src/listing/components/listingdisplay.html
- org/Hibachi/client/src/listing/components/listingdisplaycell.html
- org/Hibachi/client/src/listing/components/swlistingdisplaycell.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6209)
> ble to get avg and totals for numbers

- admin/views/entity/detailskubundle.cfm
- config/resourceBundles/en.properties
- org/Hibachi/HibachiTags/HibachiFormField.cfm
- org/Hibachi/HibachiTags/HibachiPropertyDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6212)
> Develop ck typeaheaddisplay

- admin/views/entity/preprocessvendororder_fulfill.cfm
- model/entity/Stock.cfc
Adds getCurrentSkuPrice and calculatedCurrentSkuPrice to Stock.cfc, and adds null check to prevent hard error on preprocessvendororder_fulfill.cfm
> Fixed vendor order fulfill error, added getCurrentSkuPrice

- meta/tests/test-runner/directoryMapping.cfc
- meta/tests/test-runner/index.cfm
- org/Hibachi/client/src/collection/components/displayitemaggregate.html
Add UI drop downs separately for test folder, file, and method in TestBox (test-runner) UI.
>  Update TestBox Directory Mapping UI with drop downs

- admin/controllers/entity.cfc
- model/dao/StockDAO.cfc
- model/process/StockAdjustment_AddStockAdjustmentItem.cfc
+ Changed flag for getSites to look for arraylen rather than checking to see isNull
> + Added additional test for select query for maxReferenceNumber

- config/resourceBundles/en.properties
- model/entity/Order.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6239)
> added missing rbkeys and property

- admin/layouts/default.cfm
- org/Hibachi/HibachiTags/HibachiScript.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6245)
> only update script if file changed

- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6248)
> dding reporting logic

- admin/client/src/bundle.js
- model/entity/Order.cfc
- model/entity/OrderFulfillment.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6249)
> Develop rm cachekeynotauditable

- meta/tests/unit/service/AttributeServiceTest.cfc
set the cache values before checking it in cache in attributeservicetest cfc file
> set the cache values for fixing the issue in circleci 9985

- integrationServices/avatax/Tax.cfc
- integrationServices/avatax/model/handler/AvataxEventHandler.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6254)
> Updated how we are committing tax documents in avalara

- model/dao/VendorOrderDAO.cfc
@rmarchandTen24 Please review the PR resolving issue for the Task - https://ten24.teamwork.com/index.cfm#tasks/17907955
> update VendorOrderDao.cfc to resolve the error - when creating an order for Vendor

- meta/tests/unit/mockService.cfc
added mocking function for ledgerAccountService file to solve the error in core/RBKeyTest file
> added mocking function for ledgerAccountService file

- meta/tests/unit/entity/VendorOrderTest.cfc
added currencyCode in vendororderitem to solve the undefined error issue in vendorordertest file
> added data for sku file in VendorOrderTest file

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6272)
> sum aggregate fix

- model/validation/ProductType.json
added validation for product type names to be unique
added validation for no use of non alphanumeric characters and no spaces for urlTitle field.
> added product type validation

- meta/tests/unit/dao/InventoryDAOTest.cfc
made changes in unit tests of InventoryDAOTest  cfc file for solving the error issue : coldfusion.runtime.UninitializedValueException: Value must be initialized before use
> made changes in unit tests of inventoryDAOTest cfc file

- meta/tests/unit/dao/PromotionDAOTest.cfc
made changes in PromotionDAOTest file to solved the error : coldfusion.runtime.UndefinedVariableException: Variable BASETITLE is undefined
> changes in PromotionDAOTest file

- model/entity/Sku.cfc
- model/entity/SkuBundle.cfc
locations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6301)
> Changed how quantity was being calculated for

- admin/views/entity/preprocessorder_addorderitem.cfm
https://ten24.teamwork.com/#tasks/18055914
> Fixed typeahead on inner order pages

- org/Hibachi/client/src/core/components/typeaheadsearch.html
https://ten24.teamwork.com/#tasks/17941457
> Fixed dropdown per this ticket

- org/Hibachi/HibachiAuthenticationService.cfc
check permissions on preprocess views and actions
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6308)
> Updated the hibachiAuthentication service to

- meta/tests/unit/mockService.cfc
> change in component path case sensitivity 

- meta/tests/unit/entity/VendorOrderTest.cfc
@rmarchandTen24 please review the PR
> Add test annotation in vendorOrderTest

- model/service/SubscriptionService.cfc
order link when the user is an admin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6317)
> Updated renewal error message to only display the

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6330)
> npm install before build

- org/Hibachi/HibachiValidationService.cfc
strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6343)
> updated validation service to handle case sensitivity when comparing

- admin/views/entity/detailproduct.cfm
- model/entity/Product.cfc
- model/entity/Sku.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6356)
> helper method for skubundles

- admin/client/src/ajs-upgraded-providers.ts
- admin/client/src/app.module.ts
- org/Hibachi/client/src/core/core.module.ts
- org/Hibachi/client/src/core/services/cacheservice.ts
- org/Hibachi/client/src/core/services/draggableservice.ts
- org/Hibachi/client/src/core/services/expandableservice.ts
- org/Hibachi/client/src/core/services/filterservice.ts
- org/Hibachi/client/src/core/services/hibachivalidationservice.ts
- org/Hibachi/client/src/core/services/historyservice.ts
- org/Hibachi/client/src/core/services/localstorageservice.ts
- org/Hibachi/client/src/core/services/scopeservice.ts
- org/Hibachi/client/src/core/services/utilityservice.ts
- org/Hibachi/client/src/dialog/dialog.module.ts
- org/Hibachi/client/src/dialog/services/dialogservice.ts
- org/Hibachi/client/src/logger/logger.module.ts
- org/Hibachi/client/webpack.config.js
upgrade the dialog.module.ts and dialogservice.ts file to angular2
> upgrade the dialog.module.ts and dialogservice.ts file to angular2

- model/entity/Content.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6396)
> if it exists then use it

- model/dao/HibachiEntityQueueDAO.cfc
- org/Hibachi/HibachiDAO.cfc
- org/Hibachi/HibachiEntityQueueDAO.cfc
> fixing threads

- model/transient/HibachiScope.cfc
> Fix hibachiScope.getCategory()

- admin/views/entity/detailaccountaddress.cfm
To say account address instead of the address
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6401)
> Updated the title of the edit account address modal

- model/entity/SubscriptionUsage.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6392)
> Added fixes and enhancements to subscriptionUsage

- admin/client/src/ajs-upgraded-providers.ts
- admin/client/src/app.module.ts
- org/Hibachi/client/src/core/core.module.ts
- org/Hibachi/client/src/core/services/formservice.ts
- org/Hibachi/client/src/core/services/hibachivalidationservice.ts
- org/Hibachi/client/src/core/services/metadataservice.ts
- org/Hibachi/client/src/core/services/observerservice.ts
- org/Hibachi/client/src/core/services/utilityservice.ts
- org/Hibachi/client/src/form/form.module.ts
- org/Hibachi/client/src/form/services/fileservice.ts
- org/Hibachi/client/src/pagination/pagination.module.ts
- org/Hibachi/client/src/pagination/services/paginationservice.ts
fixed the error at utility service and upgraded metadataservice, observerservice files
> fixed the error at utility service and upgraded metadataservice, observerservice files

- public/controllers/account.cfc
function name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6412)
> Updated action for Subscription Renewals to match

- model/entity/Product.cfc
- model/service/ProductService.cfc
- model/service/SkuService.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6409)
> replaced array len sku code generation with entity generator

- org/Hibachi/HibachiService.cfc
- org/Hibachi/HibachiTags/HibachiFilterCountDisplayItem.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6420)
> Develop ck filter count

- org/Hibachi/client/src/core/core.module.ts
- org/Hibachi/client/src/core/services/entityservice.ts
- org/Hibachi/client/src/core/services/typeaheadservice.ts
upgraded typeaheadservice and entityservice
> upgraded typeaheadservice and entityservice

- integrationServices/slatwallcms/skeletonsite/tags/SwfAddressForm.cfm
- integrationServices/slatwallcms/skeletonsite/tags/SwfErrorDisplay.cfm
- integrationServices/slatwallcms/skeletonsite/tags/tagtemplates/errorDisplay.cfm
- integrationServices/slatwallcms/skeletonsite/templates/inc/myaccount/login.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-checkout-old.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-checkout.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-productlisting.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-shoppingcart.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6427)
> dding templates

- integrationServices/slatwallcms/skeletonsite/tags/SwfAddressForm.cfm
- integrationServices/slatwallcms/skeletonsite/tags/SwfErrorDisplay.cfm
- integrationServices/slatwallcms/skeletonsite/tags/tagtemplates/errorDisplay.cfm
- integrationServices/slatwallcms/skeletonsite/templates/inc/myaccount/login.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-checkout-old.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-checkout.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-productlisting.cfm
- integrationServices/slatwallcms/skeletonsite/templates/slatwall-shoppingcart.cfm
- model/process/Order_UpdateOrderFulfillment.cfc
- model/service/OrderService.cfc
- model/service/PublicService.cfc
- model/transient/HibachiScope.cfc
- model/validation/Account_Create.json
- org/Hibachi/client/src/core/core.module.ts
- org/Hibachi/client/src/core/model/entity/accountaddress.ts
- org/Hibachi/client/src/core/model/entity/entities.ts
- org/Hibachi/client/src/core/services/accountaddressservice.ts
- org/Hibachi/client/src/core/services/baseentityservice.ts
- org/Hibachi/client/src/core/services/hibachiservice.ts
- org/Hibachi/client/src/core/services/publicservice.ts
- org/Hibachi/client/src/form/components/swfform.ts
- org/Hibachi/client/src/frontend/components/swfaddressform.ts
- org/Hibachi/client/src/frontend/components/swfnavigation.ts
- org/Hibachi/client/src/frontend/frontend.module.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6426)
> updates for checkout

- admin/controllers/main.cfc
- config/dbdata/SlatwallUpdateScript.xml.cfm
- config/scripts/database/v5_1_2.cfm
- config/scripts/database/v5_1_3.cfm
- model/service/UpdateService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6405)
> Develop ck update enhancements

- integrationServices/mura/model/handler/Handler.cfc
- model/service/IntegrationService.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiSessionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6448)
> Develop rm factorybugmura

- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6449)
> fix for basurl

- admin/views/entity/detailpromotionqualifier.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6442)
> Set the views in the link to be lower case

- model/service/OrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6444)
> Updated variable argument to be arguments

- config/resourceBundles/en.properties
- model/entity/Order.cfc
- model/service/OrderService.cfc
adds a canceled datetime and sets it when the order is canceled.
> Develop ih canceled datetime

- model/dao/AccountDAO.cfc
- model/entity/AccountEmailAddress.cfc
- model/validation/AccountEmailAddress.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6395)
> preventing dupes

- integrationServices/mura/model/handler/Handler.cfc
- model/service/PublicService.cfc
- model/transient/HibachiScope.cfc
- org/Hibachi/client/src/frontend/components/swfaddressform.ts
- org/Hibachi/client/src/frontend/components/swfnavigation.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6462)
> adding extras

- org/Hibachi/HibachiEntityQueueDAO.cfc
This string is not closed. Closed it.
> Fix hibachi dao

- org/Hibachi/client/src/core/components/swtypeaheadsearch.ts
- org/Hibachi/client/src/core/components/typeaheadsearch.html
Adds Miguels fixes on typeahead into core.
> Develop ih typeahead

- CODEOWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6469)
> adding code owners

- model/entity/Sku.cfc
- model/entity/Stock.cfc
- model/service/LocationService.cfc
- model/service/StockService.cfc
- org/Hibachi/HibachiDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6479)
> inventory updates

- model/dao/InventoryDAO.cfc
multiple stock
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6445)
> Updated how QNDOO gets calculated when skus have

- org/Hibachi/client/src/workflow/services/scheduleservice.ts
- org/Hibachi/client/src/workflow/services/workflowconditionservice.ts
- org/Hibachi/client/src/workflow/workflow.module.ts
@rmarchandTen24 Please review the PR
> Upgrade workflow condition service and add to workflow module

- org/Hibachi/client/src/workflow/services/scheduleservice.ts
- org/Hibachi/client/src/workflow/workflow.module.ts
@rmarchandTen24 Please review the PR
> Upgrade Schedule Service and add in workflow module

- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6493)
> bug fixes for selected data discovery

- org/Hibachi/HibachiDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6498)
> Updated import to handle scale on decimal

- admin/views/entity/vendorordertabs/vendororderitems.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6495)
> Added keywordProperties to the vendororderitems

- org/Hibachi/HibachiCollectionService.cfc
primary id exportable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6503)
> Added functionality to force merge collection to have the

- admin/client/src/ajs-upgraded-providers.ts
- admin/client/src/app.module.ts
- admin/client/src/orderfulfillment/orderfulfillment.module.ts
- admin/client/src/orderfulfillment/services/orderfulfillmentservice.ts
- org/Hibachi/client/src/collection/collection.module.ts
- org/Hibachi/client/src/collection/services/collectionservice.ts
- org/Hibachi/client/src/core/services/hibachiinterceptor.ts
upgraded collectionservice to angualar 2 service
> upgraded collectionservice, orderfulfillmentservice to angualar 2 service and resolved the issue with hibachiinterceptor arrow syntax function

- model/entity/SkuPrice.cfc
this is to make sure the the stock price is also getting recalculated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6516)
> Added preUpdate to skuprice

- admin/client/src/orderfulfillment/components/sworderfulfillmentlist.ts
to force return 0 if all other conditionals fail
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6524)
> Updated getTotalFulfillmentsSelected

- admin/views/entity/stocktabs/basic.cfm
- model/entity/Stock.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6513)
> Added average Cost to the detail stock view

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6527)
> changing name of slatwall robot

- admin/client/src/ajs-upgraded-providers.ts
- admin/client/src/app.module.ts
- admin/client/src/orderfulfillment/services/orderfulfillmentservice.ts
added angualr2 listingService to orderfulfillmentService and removed angularjs listingservice provider
> added angualr2 listingService to orderfulfillmentService

- model/service/PromotionService.cfc
when a promotion is applied
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6534)
> Added order item to modified entities

- org/Hibachi/client/src/core/services/utilityservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6542)
> Simplified the list remove logic in utilityservice

- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6547)
> abstracting applydata for abstraction

- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6549)
> filtering out bad data

- model/transient/HibachiScope.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6560)
> Added missing parenthesis

- api/controllers/public.cfc
- org/Hibachi/HibachiControllerREST.cfc
- org/Hibachi/HibachiJWT.cfc
- org/Hibachi/client/src/core/services/hibachiinterceptor.ts
- org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6559)
> Develop rm getrequest

- model/entity/Collection.cfc
collection export
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6563)
> Updated how we were looping over the columns in the

- admin/views/main/log.cfm
This is to get the log files working when working in lucee on c9
> Adds a path to the log.cfm

- model/service/ShippingService.cfc
include the total shipping quantity and the subtotalafterdiscounts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6565)
> Updated the fulfillmentMethodOptionsCacheKey to

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6575)
> Develop rm workflowprimaryidbug

- org/Hibachi/HibachiTags/HibachiListingDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6576)
> escape apostrophe

- admin/views/entity/accounttabs/childaccounts.cfm
- admin/views/entity/accounttabs/parentaccounts.cfm
- admin/views/entity/preprocessaccount_addaccountrelationship.cfm
- admin/views/entity/preprocessaccount_create.cfm
- config/resourceBundles/en.properties
- model/process/Account_AddAccountRelationship.cfc
- model/service/AccountService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6569)
> adding relationship work

- model/service/WorkflowService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6583)
> flush on after if ther are no errors

- admin/views/entity/preprocessorderdelivery_create.cfm
- model/process/OrderDelivery_Create.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6578)
> Develop ck orderdeliveryvalidation

- org/Hibachi/Hibachi.cfc
to check if the bean factory exists.
> Reload key update

- model/process/Order_AddOrderItem.cfc
- model/service/ShippingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6589)
> Develop rm manualshippingtocachekey

- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6590)
> fixing group by for aggregates

- model/process/Account_Create.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6593)
> missing property

- org/Hibachi/HibachiDataService.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6600)
> decode for lucee4 support

- model/process/OrderDelivery_Create.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6602)
> fixing bug where you could not fulfill before stock existed

- model/entity/Collection.cfc
to help fix an issue with display property one-to-manys
Allows unit tests to run.
> Replaces getGroupBys with a slightly older version

- admin/client/src/optiongroup/components/swaddoptiongroup.ts
- model/process/OrderDelivery_Create.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6605)
> Develop rm skuoptionbug

- admin/layouts/default.cfm
- model/entity/HibachiEntity.cfc
- org/Hibachi/HibachiControllerEntity.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6607)
> check if uuid is valid

- admin/client/src/optiongroup/components/swaddoptiongroup.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6609)
> Develop rm attributeoptiongroupbuilderror

- model/service/HibachiSessionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6614)
> bug fix for mura login on first load

- model/entity/Product.cfc
- model/entity/Sku.cfc
- model/process/Order_AddOrderItem.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6619)
> updated logic for getLive price

- integrationServices/mura/model/handler/MuraEventHandler.cfc
doesn't run twice
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6624)
> Added conditional check to thread to make it

- config/dbdata/SlatwallType.xml.cfm
- config/dbdata/SlatwallUpdateScript.xml.cfm
- config/scripts/database/v5_1_5.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6603)
> Removed extra commas from type xml

- config/resourceBundles/en.properties
- model/report/AppliedTaxReport.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6626)
> support for returns on tax applied

- admin/views/report/deferredrevenuereportexport.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6637)
> removing bad key

- model/dao/SubscriptionDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6644)
> deferred revenue for items with no deliveries

- org/Hibachi/client/src/frontend/main.ts
- org/Hibachi/client/webpack-frontend-develop.config.js
created main.ts file and update the webpack-frontend-devlop.config.js file for entry app
> created main.ts file and update the webpack-frontend-devlop.config.js file for entry app

- admin/views/entity/settingstabs/global.cfm
- model/entity/Collection.cfc
- model/service/SettingService.cfc
- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6646)
> disable record level perms setting

- admin/views/entity/settingstabs/global.cfm
- config/resourceBundles/en.properties
- model/service/SettingService.cfc
- org/Hibachi/HibachiTags/HibachiCache.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6653)
> Develop rm hibachicacheforlucee

- model/entity/Account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6670)
> Moved URL title to be with the rest of the persistent

- org/Hibachi/HibachiObject.cfc
- org/Hibachi/HibachiScope.cfc
> Updated logMessage method to allow overriding logPrefix

- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6631)
> Develop ck collectionexport

- org/Hibachi/HibachiCollectionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6703)
> Moved where collection data

- model/service/AttributeService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6708)
> Develop ck getattributeoptionlabels

- org/Hibachi/HibachiUtilityService.cfc
This is used to generate random promotion codes using some specification.
> Adds generate random strings into project.

- org/Hibachi/HibachiObject.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6709)
> Updated getRemoteAddress to prevent duplicates

- model/entity/Order.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiObject.cfc
- org/Hibachi/framework/aop.cfc
- org/Hibachi/framework/hibachiaop.cfc
- org/Hibachi/framework/ioc.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6696)
> fixing di1

- admin/views/entity/detailorderitem.cfm
- admin/views/entity/orderitemtabs/stockholds.cfm
- admin/views/entity/settingstabs/sku.cfm
- admin/views/entity/skutabs/skusettings.cfm
- config/resourceBundles/en.properties
- model/dao/InventoryDAO.cfc
- model/entity/OrderItem.cfc
- model/entity/StockHold.cfc
- model/service/OrderService.cfc
- model/service/SettingService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6714)
> adding stock hold logic

- Application.cfc
- model/service/IntegrationService.cfc
- org/Hibachi/Hibachi.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6720)
> latest bean factory updates

- model/service/TaxService.cfc
> Revert "updates to tax logic"

- api/controllers/public.cfc
json into the request context
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6729)
> Added logic to public api to populate deserialized

- config/resourceBundles/en.properties
- model/service/OrderService.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/client/src/core/services/publicservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6731)
> adding stock changes to slatwall

- org/Hibachi/client/src/core/services/observerservice.ts
- org/Hibachi/client/src/pagination/services/paginationservice.ts
resolved the this scope issue in pagination in function setPageRecordsInfo
> resolved the this scope issue in pagination in function setPageRecordsInfo

- model/dao/SkuDAO.cfc
- model/service/ImageService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6735)
> image service use less objects

- admin/controllers/entity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6737)
> adding action perms

- model/entity/MinMaxStockTransfer.cfc
- model/entity/OrderDelivery.cfc
- model/entity/StockReceiver.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6736)
> adding permissions

- admin/client/src/sku/components/skupriceedit.html
- admin/client/src/sku/components/skupricesedit.html
- admin/client/src/sku/components/swaddskupricemodallauncher.ts
- admin/client/src/sku/components/swdeleteskupricemodallauncher.ts
- admin/client/src/sku/components/sweditskupricemodallauncher.ts
- admin/client/src/sku/components/swimagedetailmodallauncher.ts
- admin/client/src/sku/components/swpricingmanager.ts
- admin/client/src/sku/components/swskucodeedit.ts
- admin/client/src/sku/components/swskucurrencyselector.ts
- admin/client/src/sku/components/swskupriceedit.ts
- admin/client/src/sku/components/swskupricequantityedit.ts
- admin/client/src/sku/components/swskupricesedit.ts
- admin/client/src/sku/components/swskustockadjustmentmodallauncher.ts
- admin/client/src/sku/components/swskuthumbnail.ts
- admin/client/src/sku/services/skupriceservice.ts
- org/Hibachi/client/src/form/components/swfform.ts
- org/Hibachi/client/src/form/components/swpropertydisplay.ts
- org/Hibachi/client/src/listing/components/listingrowsave.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6740)
> updates to pricing manager for price groups

- model/dao/SkuPriceDAO.cfc
- model/entity/Attribute.cfc
- model/entity/Sku.cfc
- model/service/VendorOrderService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6741)
> sku price by price group

- model/entity/Content.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6743)
> add mura to key

- model/entity/Content.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6744)
> category to key

- model/service/TaxService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6746)
> Updated condtional to make sure tax cache runs

- model/service/WorkflowService.cfc
> Patch workflow service

- admin/client/src/app.provider.ts
- admin/client/src/orderitem/components/orderfulfillment-shippinglabel.html
- admin/client/src/orderitem/components/orderitem-detaillabel.html
- admin/client/src/orderitem/components/orderitem.html
- admin/client/src/orderitem/components/swoishippinglabelstamp.ts
- admin/client/src/orderitem/components/sworderitemdetailstamp.ts
- admin/client/src/orderitem/orderitem.module.ts
- admin/layouts/default.cfm
- org/Hibachi/client/src/core/components/swrbkey.ts
updated appProvider from baseBootstrap of develop branch ,  upgraded the swOrderItemDetailStamp  and  swioshippinglabelstamp directives into angular 2
> updated appProvider from baseBootstrap of develop branch ,  upgraded the swOrderItemDetailStamp  and  swioshippinglabelstamp directives into angular 2

- admin/client/src/app.provider.ts
- admin/client/src/slatwall/components/herodetail.component.ts
updated the appProvider from baseBootstrap.ts file of develop branch
> updated the appProvider from baseBootstrap.ts file of develop branch

- integrationServices/slatwallcms/skeletonsite/templates/_slatwall-header.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6747)
> ie support for cms

- model/dao/SkuDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6734)
> updated average cost to be weighted

- admin/views/entity/liststockadjustmentitem.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6754)
> fixing casing

- admin/client/src/sku/components/swaddskupricemodallauncher.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6757)
> fixing missing price group when adding new skuprices

- config/dbdata/SlatwallUpdateScript.xml.cfm
- config/scripts/database/v5_1_6.cfm
- org/Hibachi/HibachiDataDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6753)
> short ref should auto increment

- org/Hibachi/HibachiEntity.cfc
- org/Hibachi/HibachiService.cfc
useful for preloading client side directives
> get a collections-esque Json Representation of any entity

- meta/tests/unit/core/RBKeyTest.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6769)
> adding variables.debugArray messages to circle

- org/Hibachi/client/src/listing/components/swlistingdisplay.ts
causes listing export to throw hard error 'unexpected end of json output'
> fixing issue when there's a single quote in the collection config 

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6771)
> added getPropertyIdentifierAlias to selectionsHQL

- admin/views/entity/inventoryanalysistabs/analysisresults.cfm
- model/entity/InventoryAnalysis.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6780)
> fixes for inventoryanalysis

- Application.cfc
- model/dao/AttributeDAO.cfc
- model/entity/Sku.cfc
- model/service/IntegrationService.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiEventService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6783)
> making beans out of eventhandlers

- Application.cfc
- api/controllers/public.cfc
- api/controllers/workflow.cfc
- integrationServices/slatwallcms/BaseApplication.cfc
- integrationServices/slatwallcms/model/handler/SlatwallCMSHandler.cfc
- model/dao/AttributeDAO.cfc
- model/dao/StockDAO.cfc
- model/entity/HibachiEntity.cfc
- model/entity/Order.cfc
- model/entity/Sku.cfc
- model/process/Order_AddOrderItem.cfc
- model/process/Order_UpdateOrderFulfillment.cfc
- model/service/AddressService.cfc
- model/service/IntegrationService.cfc
- model/service/LocationService.cfc
- model/service/PublicService.cfc
- model/service/ShippingService.cfc
- model/service/StockService.cfc
- model/transient/HibachiScope.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiControllerREST.cfc
- org/Hibachi/HibachiEventService.cfc
- org/Hibachi/HibachiObject.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6782)
> Develop rm add order item

- model/service/OrderService.cfc
- model/service/TaxService.cfc
- org/Hibachi/HibachiTransient.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6784)
> adding tax optimizations

- org/Hibachi/HibachiEntity.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6791)
> fix for permission cache key

- model/entity/Collection.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6792)
> utc fixes for > and <

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6793)
> bug fix for collections

- model/entity/Collection.cfc
- model/service/EncryptionService.cfc
- model/service/HibachiUtilityService.cfc
- model/service/UpdateService.cfc
- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiDataDAO.cfc
- org/Hibachi/HibachiDataService.cfc
- org/Hibachi/HibachiUtilityService.cfc
- org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6803)
> migration to use system folder for mounting

- org/Hibachi/client/src/workflow/components/swworkflowcondition.ts
- org/Hibachi/client/src/workflow/components/swworkflowtasks.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6812)
> Develop rm conditionsdropdownfix

- tags/SlatwallAdminAddressDisplay.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6814)
> need id to be empty string to save them

- model/entity/Collection.cfc
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiControllerREST.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6818)
> collection updates for restricting and grouping by

- model/service/OrderService.cfc
Shows errors on payment transaction during cancel order and stop it from canceling.
> Shows errors on payment transaction during cancel

- admin/views/report/deferredrevenuereport.cfm
- admin/views/report/deferredrevenuereportexport.cfm
- model/dao/SubscriptionDAO.cfc
- model/service/SubscriptionService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6828)
> Develop rm deferredupdates

- admin/views/entity/detailintegration.cfm
- integrationServices/BaseIntegration.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6835)
> adding actions to dropdown by the integration configuration

- admin/views/report/revenuereportcontrols.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6838)
> bug fix to deferred revenue export when clicked twice

- admin/controllers/entity.cfc
- admin/views/entity/detailaccount.cfm
- admin/views/entity/detailproducttype.cfm
- org/Hibachi/HibachiAssets/js/global.js
- org/Hibachi/HibachiTags/HibachiEntityDetailGroup.cfm
- org/Hibachi/HibachiTags/HibachiEntityDetailItem.cfm
- org/Hibachi/HibachiTags/HibachiTab.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6854)
> lazy load all tabs

- model/entity/Print.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6865)
> Made print content publicly accessible

- org/Hibachi/client/src/form/components/swinput.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6868)
> Updated swinput.ts to not add currency filter on edit

- org/Hibachi/client/package.json
- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6869)
> upgrading wbepack dev server

- admin/client/src/orderfulfillment/services/orderfulfillmentservice.ts
- admin/views/entity/preprocessorderdelivery_generateshippinglabel.cfm
- config/resourceBundles/en.properties
- integrationServices/BaseShipping.cfc
- integrationServices/canadapost/Shipping.cfc
- integrationServices/endicia/Shipping.cfc
- integrationServices/fedex/Shipping.cfc
- integrationServices/parcel2go/Shipping.cfc
- integrationServices/ups/ProcessShipmentRequestTemplate.cfm
- integrationServices/ups/Shipping.cfc
- integrationServices/usps/Shipping.cfc
- model/entity/Address.cfc
- model/entity/Collection.cfc
- model/entity/OrderFulfillment.cfc
- model/process/OrderDelivery_GenerateShippingLabel.cfc
- model/service/OrderService.cfc
- model/transient/fulfillment/ShippingProcessShipmentRequestBean.cfc
- model/validation/Collection.json
- org/Hibachi/HibachiService.cfc
- public/controllers/account.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6875)
> Develop rm catchup

- org/Hibachi/HibachiTags/HibachiFormField.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6874)
> adding sanitize code

- config/resourceBundles/en.properties
- model/entity/Collection.cfc
- model/validation/Collection.json
to prevent collections from being created or updated in 'broken' state
> Added collectionConfig validation

- meta/ci/version_merge.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6921)
> update slatwall develop-team

- admin/client/css/main.css
- admin/client/css/main.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6924)
> putting css in less file

- admin/controllers/entity.cfc
- admin/views/entity/reportlist.cfm
- config/resourceBundles/en.properties
- org/Hibachi/HibachiCollectionService.cfc
- org/Hibachi/HibachiTags/HibachiEntityActionBar.cfm
- org/Hibachi/client/src/listing/components/swlistingreport.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6929)
> button to clear cache

- org/Hibachi/HibachiTransient.cfc
- org/Hibachi/client/src/basebootstrap.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6930)
> Develop rm basebootstrapdeps

- org/Hibachi/Hibachi.cfc
- org/Hibachi/HibachiUtilityService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6952)
> Develop rm dataoptions

- admin/client/src/sku/components/swimagedetailmodallauncher.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6954)
> updates to fix uploads on pricing manager

- admin/client/css/main.css
- admin/client/css/main.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6963)
> adding css for reporting

- admin/views/entity/reportlist.cfm
- org/Hibachi/HibachiTags/HibachiEntityActionBar.cfm
- org/Hibachi/client/src/listing/components/listingsearch.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6966)
> Develop rm reportingupdater

- org/Hibachi/client/src/listing/components/listingdisplaycelldate.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6969)
> update for lucee formatted dates

- admin/controllers/entity.cfc
- admin/views/entity/detailcollection.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6970)
> fixing redirect on clone collection if it isn't a report

- meta/tests/unit/entity/CollectionTest.cfc
- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6980)
> Develop rm convertalias

- model/entity/Collection.cfc
- org/Hibachi/HibachiService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6983)
> aggregates fix

- org/Hibachi/HibachiValidationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6986)
> dont validate delete on a new object

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6985)
> sorting for report

- org/Hibachi/HibachiValidationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6987)
> fix for validation

- admin/views/entity/reportlist.cfm
- config/resourceBundles/en.properties
- model/service/HibachiCollectionService.cfc
- org/Hibachi/HibachiTags/HibachiEntityActionBar.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6989)
> Develop rm duplicatereport

- model/entity/SkuPrice.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/6994)
> Update SkuPrice to allow equal quantity values

- org/Hibachi/client/src/listing/components/listingsearch.html
> Revert "Added tooltips on hover to collection icons"

- config/dbdata/SlatwallWorkflowTrigger.xml.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7000)
> workfowtrigger depends on schedule

- org/Hibachi/HibachiAuthenticationService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7006)
> Excluded content for non-process / non-preprocess actions

- model/entity/Collection.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7015)
> group by order by fix

- model/entity/ServerInstance.cfc
- org/Hibachi/HibachiCacheDAO.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7051)
> bugs in serverinstance

- integrationServices/mura/config/setup/cfapplication.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7056)
> setting client cookies by plugin

- integrationServices/BaseDataProvider.cfc
- integrationServices/BaseDataProviderHandler.cfc
- integrationServices/BaseDataProviderService.cfc
- integrationServices/DataProviderHandlerInterface.cfc
- integrationServices/DataProviderInterface.cfc
- integrationServices/algolia/Data.cfc
- integrationServices/algolia/Integration.cfc
- integrationServices/algolia/algoliacfc/LICENSE
- integrationServices/algolia/algoliacfc/ModuleConfig.cfc
- integrationServices/algolia/algoliacfc/README.md
- integrationServices/algolia/algoliacfc/algolia.cfc
- integrationServices/algolia/algoliacfc/helpers/index.cfc
- integrationServices/algolia/algoliacfc/members.json
- integrationServices/algolia/config/dbdata/SlatwallCollection.xml.cfm
- integrationServices/algolia/config/dbdata/SlatwallSchedule.xml.cfm
- integrationServices/algolia/config/dbdata/SlatwallWorkflow.xml.cfm
- integrationServices/algolia/config/dbdata/SlatwallWorkflowTask.xml.cfm
- integrationServices/algolia/config/dbdata/SlatwallWorkflowTaskAction.xml.cfm
- integrationServices/algolia/config/dbdata/SlatwallWorkflowTrigger.xml.cfm
- integrationServices/algolia/config/mappings/algoliaMappings.json
- integrationServices/algolia/config/resourceBundles/en.properties
- integrationServices/algolia/controllers/main.cfc
- integrationServices/algolia/model/handler/AlgoliaHandler.cfc
- integrationServices/algolia/model/service/AlgoliaService.cfc
- integrationServices/algolia/readme.md
- integrationServices/algolia/views/main/default.cfm
- integrationServices/algolia/views/main/manageindex.cfm
- integrationServices/algolia/views/main/preprocessrebuildindex.cfm
- model/entity/DataResource.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7061)
> adding algolia

- model/service/EmailService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7066)
> Updating arguments for test domain

- config/dbdata/SlatwallSetting.xml.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7068)
> adding emailtemplate dependency

- model/service/WorkflowService.cfc
The break here is causing a hard error. This fixes that.
> Workflow bug fix

- admin/layouts/default.cfm
- admin/views/entity/permissiongrouptabs/processpermissions.cfm
- config/resourceBundles/en.properties
- model/entity/PermissionGroup.cfc
- model/service/AccountService.cfc
- org/Hibachi/HibachiAuthenticationService.cfc
- org/Hibachi/HibachiJsonService.cfc
- org/Hibachi/HibachiScope.cfc
- org/Hibachi/HibachiTags/HibachiActionCaller.cfm
- org/Hibachi/HibachiTags/HibachiPermissionGroupActionPermissions.cfm
- org/Hibachi/HibachiTags/HibachiPermissionGroupProcessPermissions.cfm
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7075)
> Develop rm permissionclientsideprocesspermission

- admin/views/entity/detailpermissiongroup.cfm
- org/Hibachi/HibachiTags/HibachiPermissionGroupEntityPermissions.cfm
- org/Hibachi/HibachiTags/HibachiPermissionGroupProcessPermissions.cfm
- org/Hibachi/client/src/core/services/hibachiauthenticationservice.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7076)
> on edit show process permissions

- org/Hibachi/HibachiAssets/js/global.js
https://ten24.teamwork.com/index.cfm#tasks/24833750
> added support for form posts on alert-confirm modals

- org/Hibachi/HibachiEntityQueueDAO.cfc
https://ten24.teamwork.com/#tasks/25047611
> prevent hard error when entityQueueType is not passed in

- admin/views/entity/ajax.cfm
https://ten24.teamwork.com/#/tasks/24990181
> add support for lazy load on tabs

- model/transient/HibachiScope.cfc
https://ten24.teamwork.com/#tasks/24953231
> format only after the custom properties are included in list

- model/entity/Product.cfc
- model/service/ProductService.cfc
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ten24/slatwall/7090)
> Making sure product is modified when default image gets changed

- model/transient/HibachiScope.cfc
https://ten24.teamwork.com/#/tasks/25370804
> only format after custom properties are added to list

- model/service/AddressService.cfc
for issue #7096
will address in master as well if needed
> adding isAddressInZoneByZoneID helper 

- readme.md
https://ten24.teamwork.com/#/tasks/29618185
> Update Slatwall readme documentation
